#!/usr/bin/env python3
"""
Bug #0017 — xla: jax.jit diverges from pytorch_eager.

Patterns  : [['normalization', 'softmax_axis0_residual'], ['broadcast', 'mish_activation'], ['layout', 'resize_cubic_halfpixel'], ['fusion', 'add_mul_add_chain'], ['fusion', 'conv_bn_eval_explicit'], ['constant', 'unsqueeze_three_squeeze']]
S_diff    : 1.000000   (jit vs pytorch_eager)
Delta_opt : 0.000000   (jit vs no-jit)
Tolerance : 0.001

    python unique_0017.py
Exit 0 = reproduced, 1 = not reproduced.
"""
import base64, sys
import numpy as np
import onnx
from onnx import numpy_helper as _nh

TOLERANCE = 0.001

_ONNX_B64 = (
    "CAg6xYsBCi4KC21vZGVsX2lucHV0EgluMF9zeDBfc20iB1NvZnRtYXgqCwoEYXhpcxgAoAECCikK"
    "CW4wX3N4MF9zbQoLbW9kZWxfaW5wdXQSCm4wX3N4MF9vdXQiA0FkZAogCgpuMF9zeDBfb3V0Eg1u"
    "MTAwX21pc2hfZXhwIgNFeHAKMQoNbjEwMF9taXNoX2V4cAoNbjEwMF9taXNoX29uZRIMbjEwMF9t"
    "aXNoX3NwIgNBZGQKIgoMbjEwMF9taXNoX3NwEg1uMTAwX21pc2hfbG9nIgNMb2cKIwoNbjEwMF9t"
    "aXNoX2xvZxIMbjEwMF9taXNoX3RoIgRUYW5oCi4KCm4wX3N4MF9vdXQKDG4xMDBfbWlzaF90aBIN"
    "bjEwMF9taXNoX291dCIDTXVsCooBCg1uMTAwX21pc2hfb3V0Cg1uMjAwX3Jlc2lfcm9pChBuMjAw"
    "X3Jlc2lfc2NhbGVzEg1uMjAwX3Jlc2lfb3V0IgZSZXNpemUqLwoeY29vcmRpbmF0ZV90cmFuc2Zv"
    "cm1hdGlvbl9tb2RlIgpoYWxmX3BpeGVsoAEDKhAKBG1vZGUiBWN1YmljoAEDCi0KDW4yMDBfcmVz"
    "aV9vdXQKCm4zMDBfYW1hX2ESC24zMDBfYW1hX3gxIgNBZGQKKwoLbjMwMF9hbWFfeDEKCm4zMDBf"
    "YW1hX2ISC24zMDBfYW1hX3gyIgNNdWwKLAoLbjMwMF9hbWFfeDIKCm4zMDBfYW1hX2MSDG4zMDBf"
    "YW1hX291dCIDQWRkCngKDG4zMDBfYW1hX291dAoLbjQwMF9jYmVlX3cKC240MDBfY2JlZV9iEgxu"
    "NDAwX2NiZWVfY3YiBENvbnYqFQoMa2VybmVsX3NoYXBlQANAA6ABByoRCgRwYWRzQAFAAUABQAGg"
    "AQcqEAoHc3RyaWRlc0ABQAGgAQcKfAoMbjQwMF9jYmVlX2N2CgxuNDAwX2NiZWVfc2MKDW40MDBf"
    "Y2JlZV9ibmIKDG40MDBfY2JlZV9ybQoMbjQwMF9jYmVlX3J2EgxuNDAwX2NiZWVfYm4iEkJhdGNo"
    "Tm9ybWFsaXphdGlvbioRCgdlcHNpbG9uFazFJzegAQEKIwoMbjQwMF9jYmVlX2JuEg1uNDAwX2Ni"
    "ZWVfb3V0IgRSZWx1CjcKDW40MDBfY2JlZV9vdXQKDm41MDBfdTNzX3VzX2F4EgtuNTAwX3Uzc191"
    "cyIJVW5zcXVlZXplCjQKC241MDBfdTNzX3VzCg5uNTAwX3Uzc19zcV9heBIMbjUwMF91M3Nfb3V0"
    "IgdTcXVlZXplEgt0cmlvbl9ncmFwaCqcYAgBCAMIIAggEAFCDW4xMDBfbWlzaF9vbmVKgGAAAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8qFQgAEAFCDW4yMDBfcmVzaV9yb2lKACooCAQQ"
    "AUIQbjIwMF9yZXNpX3NjYWxlc0oQAACAPwAAgD8AAABAAAAAQCoWCAEQAUIKbjMwMF9hbWFfYUoE"
    "zczMPSoWCAEQAUIKbjMwMF9hbWFfYkoEAADAPyoWCAEQAUIKbjMwMF9hbWFfY0oEzcxMPiqaGwgg"
    "CAMIAwgDEAFCC240MDBfY2JlZV93SoAbzkm2PnZjVLz6XN4+wwA6vq0liz5w5pc+41jdui+JXzuW"
    "ECo+RRLWvu2lIb25oEk+9xioPuXUOb1MSqo+c7OSPm1K3b1K73A+krkrPR6uFL7tDjk+fdnvPtcs"
    "9b5+m3K+fEsRvqQJyD4XFrk8EV8mPjp1bj5xLsm+ZPdpPqlLwz7dHEU+TH7iPY9vV76VOre+47ck"
    "PVI3BL0UYXC+fvKdvrm7DL5Wola+WZH+vZGVLr9Jwx89O1sjv37Ifz4TcC2+TdjmPSJ0Uz7A+BA/"
    "yXsBvu8Cuj6VXNW8MVeoPIskZ7597BK+8ciFvp7TxbwxoQu/2K6gPk3UML9ozfM+vJgzP3FAyT4T"
    "oDq+N8bLvs402Tt2ChS+8c1NvdAQKr+I+8A+J2WuvUO+fT4Z/nA+CbURvfeCjb5QNUc9wFnyPSJN"
    "Qz6sTAK/e/XRPds4kT7O/6W+t0ENvhiBFr75wwo9mMb6PObUvT3Rt5K+JgODPkA/ob7ZqLY+eA8n"
    "vnnhRb3Dap0+6XPgPKnIKTwNxQ4+kagxvnvd77z0lYS8wBx4Pbi/lz6Vg8a6YrQHv//dXL4hIRS8"
    "dSeIPh82Uj2nNtW+wUUkPFZFKb6UMNS+miyPvsJ9m75zOzy98ckJPvkpv76JJna95KrKPvWrkDog"
    "BYG9fVTNvVKM0bx3yTw/wjcBvz0fVL57aj++Ov7qPba6hL49YMM+ZxMCPxb1ar336Wk+O086vp+D"
    "nD7l0Rk/G78Hvl8WMb4wlSM+f0WoPgaZ/b5tmK+94R+APUV1JL4HONY+wzbPveWX5b3Pu00+dTGc"
    "PWBZyL30HdI9a8kxvmWVwL50EIS+I7WZvZsZN7/qjyO+6j3uvRiDgr1L4RA+fvZevQwSPL/jwAC/"
    "QGawPSpB0z5JYZw9UCtKvQKqDT7tiKe8CgpjvryVHb7bNuQ+JwWgvgOO1j10j0I+lwZ5PgqEIj1w"
    "O/K+HTTdPQDtCDz83wY+xSy0vhkzVb4yuGI9uD7bPpYOQT5c1sc+HtucPmQiDD7WzdE+ZhS/vu4w"
    "+L1MzIM+RweIvqZnmb7w5/O+lGUwvhrb2z7zWGU8GdOiPrh70r0b1dg+CvOQvnLfzr0cw8m+LhaY"
    "vfSKe76oyx2/mFwpPASkn75YuTU+WiLDvqTdHL4sdm29FpxKvgJyp72NRb2+enoKvtgIpr2Yg2M+"
    "34BTvhllPj1bPwa+9wTdvVAX1z3foga/uvKaPvXQjD5BeOS935fDujBKBj844i0+MAgKvdrOAT7H"
    "A629RY7bPr5/NT4sccy+HzruvSH/iT6wLUw90fHiPUNEBz1cOAq+auIpPv2RFL6r5Ms9RLLJvp02"
    "Qr2lkSG9ARALvZ82YL48KG89oyH8vJTyvD7/neG+IkxwvVzUZ76ZVyQ9xey6PX5wu743wkk+OMW4"
    "uzeVTz52KqI89YN9PjCBrLw970g/4bNMvYYoY7u3f0c93TQnv8BTND2KLo+9WAo3vY7Uaz2xUjY+"
    "IWvDPFtIgj5egxM+fgxwPk49+b7RxUa+b6RQvhTBob5iLaa+KTGfPQFGVT6d9ME+BqV5PlCmtL0x"
    "QeM8DugiPog+mr1+y7W+pk0APle8Aj+Tx4w+FZLOPjDvAD/UNBq+u97kPuleEr4VkRA+P293PuKB"
    "t74tkdQ9NnC1PnZ8r77bcce+zdUzvXG5wL7CM9w9VOvOvjXj8715xTe8uiKMvO/Taj5kai6/1HwY"
    "PiWaDb4RM4k8EnMLP9piuT18Iqg9LVvpvszBaT5NhYy+uzCMPkGQN733zWo+kVwYP/EeQr77Icq9"
    "oaF3vj2rR74hcbA+4m+qPSgwMD6gsIc+1rn6vmWnkj0T99u+tvQAPuGO+TxgmjY/19qJvdyTPL9b"
    "5/m7q26OPleAAz6Gao++GlKlPoS2hj561y++IX7QvRfJBL9dijk+5craPilfzDtRvR6+l7M2vusJ"
    "LT6pnsA+gIJOvySIxzvE9gG8+CJHviul376tURA95YOrvRJKF74eNk88u1pqPqzoQj+bX7k+MQny"
    "PObNPL1V2dI+yF5IPVAwtT1npEy+7duzvie9kj4Yvk4+vPvHPf3Skz6SuJ8+tHVavU6efL3Cx7q9"
    "YvHIvlcIkj1vkgg+L8Sjvs2W5D05hFQ+CLc/Pr/+sD6C4as9yBpZPiYEor4rVKa9dlFFvmfiWz4F"
    "mMk9VaRuPhvUFb6w2/K95/wBvWvn/L3TC509quHdvocXVj3Jm5C9Dz0kPuIw+71cMve9UzSWvi3A"
    "Yz2EcYU+b0Qlu4dU7b77yTw+fWN2Pqk+TT7M9+s+MWjFvmJ6fj4v5j2++eScvvritL7WZoC+9kLA"
    "PjJFFD6aixW+WWqSvhsCBj61Z9U+HryVvR55Ub4yRAo+bv6LvXK2e762cko++d9xvpeXXz7xKBu+"
    "Fc3Xvm08FL+ZQZc+gdBoPmzwgj6PvOO9l1y5vge6tb6CHGo88MICPwuCvT1LqlC9NX9evtW5Rr4V"
    "kj6+Z2Z2vrg6KT514Du+SYOmvNp7+b5I1bu+mx91vR1nsD5zgAQ/pNKHvjedd72OVRI+ZoU2vk21"
    "x7qj+KI+m4eMPQH8j76fFsQ+v6BVvS7bxb36saG+d2uSPvAVDj4cxgK/4NyOPr3ZMD0Mh4M+U+4P"
    "vy0cAb50ba090N+1Pmbibr2cEMc+F20MvPec2DzYWj8+27IEPwOtDT/6KOY+KwXHPvb7+b47xAe9"
    "T02fPrdrGT3A0tE+7vG+PQeXOr6Ekl08J7prPr30/r6xEPK9l+93vfdNmz0UgD2+N3SWvgWzYj0r"
    "boS+6Dmcvsj4zb6pnwS/jOU4PeAeGD5a0/A9QxU1vW1pLD7ZpNq+e6unvnVtkL6c3Us+rH8ev0XT"
    "i7wiZ0y8lWMPPcSPRr6mjpg8uY8JPsGBvD4SiC27vt3svFA5D75iunc+J8fIvm7Bpr7ecfC+VYFF"
    "PZ7BCz3XM449GxFwvvCjrjo/ONU+qtW9veZ8mjwKqD6+DMeSvDs9lr6az7e+EhbJPOzKFL6/uKm+"
    "LSWSPLHtHT6EPFq/ughZPrYyWL60KFk+nzyKPo18B76QqaO+nBTivaPqtj20yDm98Efjvj2Hkz5U"
    "WdG9QafKPka86D5Vrba8mzhavpoWJb9EHaI+qJi4vu30FT+g6i++7a1JvADGnj7Tiju+vQYGvghX"
    "rj6P9Qc+Ts7lvSWj1j5ylCq9IimPvRsvTj5niBo+cyvQPqgDBr3tvC2+2+WCPk7GPDxtZUM9kxrV"
    "PUx5xT7clJW9aQl9PYS8xr6yixm+imm4vVDONr4bChq+F3Jdvr3wor6FHJQ79xWUPufa377lLcO+"
    "6HCSvr07Pr6fRc09RwYpvqDrl70RDG89SDuvPkSaEz5P0me+qwM1Pma3Kz7tgl2+1FpoPiUXJz6F"
    "RlK+q7VfPmrHoL161yi+wGnCvlp8vL5/b0U+MWgNPtxKmLzgoz88sQIEvl/+6r6f5vy83WRMPtWI"
    "Mb3qnUs+L+SnvgeehL4qlHc+Ek66vqcqoz69iN89bp4VP6HXlT0ZQOu+SqcNPY7gVT2A74o9/1ST"
    "PuJ2fb49mBO+eTlNvnfQdz0nOgy+76hoPlLU0T388zE+iwVTPqlag76JrA8+PPXivuFdQLxSISY/"
    "poHRvvmZeD1rPe47vOZfvoJ3Iz/JeEK91eEnPqYkij5LQmU8Fqwgv5CFir709JM+ZL2PvjNMPr77"
    "KqW9JUVovjoqv754iWk+OMFXPR73Zj5HG+M9EseUPZnw576J7Ra+/O0NvrlWEj4DlU29gJRaPkxp"
    "qL4bBW++kY+wPZVO/bzkKK49Vo1aO2uGoT368dK9LamrPgzEFr6FL0u+H6K0PkW1Gb+DnN699AJ/"
    "viiwrT3KgZ0+Dt8jPh0UDL1NhVS+qlqMvTE2kr0h8JI+nZj7vU6mxj7r4s09I065PqVydz7hGDy+"
    "TWu/vGY1Bz4qPHq+Z7qQvU8dl70F/fG9W3YYvrhDVr6xjLq961U9Pm4djz4c2J++J63SPjSSpr5i"
    "xMk9wQYJP4odML4Fu2m8RJqxvT0ehz3A/FA8HwqivqNdnr0K/7c+EOpbvujzVb0uatW7teOYPhew"
    "Aj/hpmk+80y2vJ1A8z0VtbW+aiNGvgozjD6J1h49CopcPkjGnz5Q7iO+QLtYPsCL1b2o2E28SLjm"
    "Pk/6br44JlI+3z1iPQaYkb4tj4U+gd/avtnbAj4k1/29Mj7xPnDdFj2bdgk/F3AoPXyarT4gmYw+"
    "jjj6PogYm743EDE8Qb/NPobg0b2qu5c+EsIFv5bH/z5SLg8/wD5WvsRm4r3hfKi+9DfMPUpA1r0S"
    "qIe+vHo8Pf9mhj52Zme+tSLVvXGCQj6/clE+856HvmlPDD/8Ccm+Fcr1PSQMRr4WgR89Ruk+v5+g"
    "Wj6PhEe+GHBQvp01mz7HNsq9qgh9vuV7sb3zKr++iLiYPiF2lr0uC++9izCivnziEj+HI9M+XWrm"
    "PqKAUT28+6A+n3pvvtP/vb2r2ZW9IwyRPsoMXD1ynzU9NpyDvdp1Dz7HO9A+GNPMvRwZqD5Zhyw9"
    "Ay5MPqPA/T11OIC9G6ebuyQVTT01OII+jSsKv4lQ1b3y1YC9mYeXPTdjAr3iCiW+Y5oqvsHgcr63"
    "k38+KpQBCCAQAUILbjQwMF9jYmVlX2JKgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqVAQggEAFCDG40MDBfY2Jl"
    "ZV9zY0qAAQAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/KpYBCCAQAUINbjQwMF9jYmVlX2JuYkqAAQAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAKpUBCCAQAUIMbjQwMF9jYmVlX3JtSoABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqlQEIIBABQgxuNDAwX2Ni"
    "ZWVfcnZKgAEAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPyouCAMQB0IObjUwMF91M3NfdXNfYXhKGAQAAAAAAAAABQAA"
    "AAAAAAAGAAAAAAAAACouCAMQB0IObjUwMF91M3Nfc3FfYXhKGAQAAAAAAAAABQAAAAAAAAAGAAAA"
    "AAAAAFolCgttb2RlbF9pbnB1dBIWChQIARIQCgIIAQoCCAMKAgggCgIIIGImCgxuNTAwX3Uzc19v"
    "dXQSFgoUCAESEAoCCAEKAgggCgIIQAoCCEBCBAoAEBE="
)
_INPUTS = {
    'model_input': (
    "SqhdPqDkvD+j1QC/HlvFPlN2nr+OMPE9vREuv8o24j+6Nwm/MtWxvMUGYD8cHxpAlFIewEZvrj+c"
    "3UM/Tr+wP3KzWj8QLUq+fg+fP/DBPj+u0ry/MkUyPoIaib+5Orw/yGPbPhV5iT4j/6g/aRGAP7Hq"
    "i78BTZu/WS6FvztD0j9+Oxw+Mx1pv0KHPT+qI5Q/qOysP/viwz44l4+/kfCRP/Y/ZT6S3bq/nitK"
    "PxL+Pj5xHjY/c8mnv9LOY7+Ihoo+nTvtvnNWjD7hs/W9KNXBPxBcNb/fKwK/onQgwJO7s79+KVq/"
    "9yIPv3s6gj47FQW/BgLnv8jz3b+QaUq+ymSrv9+KNb6lcxNAbwdvvklwVD0R/rG9fg1KvxISlb5H"
    "4QRAZl66P+hzqT5E26Y/NvB0v3UGMD/Qmq0/ttw7P1NUoj9ZXU8+exzevgewBz9ONh8/19qcvwwa"
    "Mr5D49a//vVEP03GkD480R+/OfYTP/AsUD/8Gl0/TSSfv9Q5Xr9bKJq/mXg1Pw1NmD+bFqg/76Xe"
    "v3Wk9L4gStw/p6Ozvn2Ggz8ydL6/Q/yNv5YpzD5cUTDAjvBHQBa52j4meKQ+cjwFPx2u6D/QerU9"
    "R6Oevn/2vT5iLRk/kSXKvgpsKj5xa40/SuJFPn7lib9u5By/LW0aP+9TLb9yofI/uxwJv947Fr6a"
    "WwfAVxYPvw5sc7+eN24/dJ+VP+btBL/LqgW/GhTjPp+noD+AZFS/MiZ2P276ur9lPDQ/r9w/v7EV"
    "Yj8jeqO+PNmwPnA1DL8084S/ruGrPz5fgT9uAIm+7/KDv5VXET7MDKM/4peWPlybnr/fR0W/HymH"
    "v1tAHT7IJyS+u/7ZvnU2/T7ap7w/8JkMPoHpob9ugZs+ctv6v1eTUL07wEk/1ch1v4uG8T8nW/O/"
    "1P1evnFYdr7ONZQ/N4yrvkOTsL8DRbq/jVgGvzjdkT+u9Xc/o2vcP9TJWT974OE/jvfuP0ptTD8Y"
    "z3Y++lDbPrSyWj50why/j6KuP8bAgj+9wps/nTeaPwJoDr9pnaS+0F2hP2AVD7+7UIq/R1u9PBIE"
    "0b7cUDK9qiXrvryZ4D/mOsO9fRh4P7wNYL+qcyq/dlluPPrirr8L1JK9GfSgvwe0jD81T9E+bq0o"
    "v04zjj+X/R8+lrq+Pi9PV7/aRt0/bkjGP55dtj9vM/8+pfCMve8TNb8aXDa/rtkfP/hpS7+46rE/"
    "JQVdPte51r5UM8i97LG+PvB4Zj8ZzhY/9DuVPrHDBT545K+/HTuXP533Bb5sKnY/ZztMv10Vgb5J"
    "3EI/ZhkiQCpFSECILr4+hFqzvJ73Jz+H3lW/k6zKPKIIyz684gfAx5e4P9W/Jr+IFf8/8TMyP1w1"
    "j74dHwu/i15Lvy/0174bg5a/DfiGP1RGLD8piIk/THi+P/dUXL8ev2m/7qfrv2ZKxT8iUea+MmSG"
    "P6rdgj4iz+W+Cz2rvjkmor1xPNg+MEkFvxs+wr47Z3w+IyxIP4WDqL0jYm+/Qez9v5X6ID/J8dI9"
    "hpyLPhCvG71l2mq/XZ2IP13fQT9EnP88lZ1Gv4eQ1r5Ge08/KBO4v2iNpb9W4iK/Co7Yv304vz1x"
    "Uj6+CbnFvWrGnz9KEJE/wQTjvnvDgL/RLTc/eIjAPgK2lb98rHC/tTgiPhwWVT3JVtI+fhNUP9lt"
    "Jb2xzVY/PhUvP2UEaL9+1qS+sqibP3s/2z7RRjS/snibvwrVrz99Z2A/Rr0Ev210r7+EGrm/aA1X"
    "vy6LZr7CVQO/s2/hPhTYMkD1OwbAzviMP1GzkD7g4+E9sTnHv+6Dnr940Zg+PkLpv2u48L6mcJ4/"
    "Vyl5Px4V7L54TuU9ONuuPU+wrD5GY4u81xJFv8kLsD8MCxLAjo1DPyU1U79PfYq9tHhfvybkJEBq"
    "Y4y/7WhXvzxtaL5/t9W/jhIQPfA7wb/AlnU/BPOyPhGYJz+G8k6/mDtGvQT8Ab9Qs7E/4hMQwGfG"
    "vb6aiay/Im6BP9Kmuj89pB8/MO4UP4qHrr6ymoI/V2Tqvk514j7rpgk/TlPbvnbpAsBc7hm/5A7t"
    "PZ2Rtr55qdk+NFFuPx19lb/gxBQ/n/xkvwYTJT94tvY+5SigvikEJL93JL0+FYDCPY/5Pb+ulPa+"
    "VQ/ovmZzFsDMi0s/k1mwv9OifD8EI5U+FM8fPx80Ob85MR+/IhrDP5DbeL7q8F0/O8DOvo9KwD6t"
    "uqU+j6uCvrK8sz4i+I6/GK0EwHjQ4T5k7lO/dBhGP3rPLT5Lec8+yDfrPsHeHj+ELts+LjziPb7F"
    "X7/Jh5W/RkRSP2QzLj+v8BC+EoOpP5f8BT13quc//hzmvaLXnDxZxoA/ypKLPocE1b5YPLc+FaCK"
    "vzKfMr/A+eq+02OZPy/hsz0lGgM/J90IwBLz9j8bPye+P6i4v9Q94z0zcuE/mnaRPRthkL8TcSu/"
    "XnSDPWjq6z3LVYW+XDQgQADIMr/o8JW/Rq2FP8WUhD8bcKM+iKXhP142Yr/K3YC/ATC+vr3iPT/7"
    "TlO/08bnvxCHsr/whQC/9SOyPtLux76YSey/oUF7Pu/xdz8d0UU/Dl3Qvxczfb9Wr0s+Vjvdv7hP"
    "CL8/0V++9TzjPq//PT7Q+sy/QbRhP/2VaL/UFTS/GMFAv4Nng79sCp2+KQqXvlHNOj9qHgPABjkF"
    "QCWzhT4l8jQ/1dkLwCud7D8ZO6S+bbxAvsMekT7g2pQ8/9VVP4GLSL5OVas/CsXNPyL8m76xdYM/"
    "P+sXv6TYOL99Qs894inLPW/rGsAD/hG/j+WQvpdBT78IWL89A3iRvmNZab+0xpc/b7eLvhd64j4s"
    "Tvg+CZxJvgsiM794vXE8pKK+P9JKHsDc9ow/YZ8Vvk9Gkz+CXh9AGBvIPxigwj8T232/cze3vgKn"
    "Gj8jWKW/frwgP90HGL+vc+69X2QqP1vbzL98x+M/cSUYP0YuIECS5ac/QSOQv01eTT92TuM/Zvzx"
    "vsR0ZT8VFQO/WDP/Pb0PhL0Jjjg/ec21PnmSDD83jg+/sRskP2CgpLxzIZO/+L0VP/6ocr9tz+y/"
    "MYGFP8tJbT8GnQy/B2fZv+Hjhb8ENMu/OAIGQJhDrL9kdfO+ghjHvqfkF0CY2Js/0MEvvp6lBUB3"
    "DXg/hIcKP8nmUb4grOs+g68OwPfjcL4Kz7I+r8NIv2mTQj+5/WC/1EWFv9NmSD7QfTC+KhCqP7Td"
    "tT+ZHBQ/JjoRwHsAAj7JHiE/81Ygv4fYf75rYna/2rrkv8t8mr5T94c+kkbYP63Gr78bu8u+bNgb"
    "wNe1Lj4P/Q2+XZLvvqkteL9U73Q/z/jYP80Twz6UV3O9vyVZP2DDYT1ajJy/Io39PnLgUT9XrJg+"
    "L8Mev6BYqD58q5o/5BWNPGtY2j+NxaA/AtnEP56fMj9m6ZQ+/3fzPrYIbz9Td5M+SmQhv14roT72"
    "XLi9PwhHv6ncaz9xuX+/duJpvzgZZr5QnH2+0sQ4PgJU272OmWU+cdjFvxXXzT4H8n4/+mTCv+X2"
    "uj3f5Hi/q1Jpv0UjAL+89ivAAsIRPvJfGL+xaEm/CaUBP4hqVz46fVi/ANVZPsx8u75vswi/ss9O"
    "v8n5s71GHsY+yLEZvii0ED8FzQA/83+DPyE8Mb+xeSA/XvEjQPCJgD5RTaW/JQQnP5stFEBLR8a/"
    "ZWUWQALsFb9G/B+/6cGxv7+il7+Kq529+7SZPgsIlj5MJr6/XgIiv0uYkL+b+aS+802vPoiTNz6+"
    "Lx4+uPhQPZkrwD+KUAk/ic87P8N6WL4dx8s9tucGvt2ewz5NW2Q/ZsaqvloFsr4gJNE+wZ9Ivt/b"
    "xz9v6Sq/Kp2jP4ykQz8Fy8k+ufWBP+vOFT7lwti/5MyMvw49lr8dhA5AJDmxPsEMgr/XNsI/CuC2"
    "v4Wl0r8iy58/GIwcv45Icj/ln0m+AVYBwNNM3D+Te4i+rQCuP8M237/8zac/g0LUvTNhur46AOg9"
    "72mQvwlsd78eeFu/7lCQPwo13z7knVE/l+woP+NUJ717b2C+W7qUP5maor+EodK/wl2jPo6P7j6K"
    "wD8/4BBXP5Li6r97a7U+bOzhvgMbjL+K48G8sscJvnmK0D7RwqG/HFcMPkyC8bxNnOm+38bhPiGi"
    "7r6kHBK/3J1WvgRjYD+Mkxi+4itYvcBPlr/UvO6++NpmPyV3QD6trAu8FnEqv9GIsb8LmRa+gUFW"
    "Pyn79b1Qc7G98jGDPqCgPT/glWq/Usyuvwl/UD+dJrk/xaL0vu9oOL+tMvy+nhMRvzAN8j/qZ/y+"
    "e3kVvzHWx7//PCm/PmqpP1taGj9Yw6G6EqT7v0HvJT+Gs8q/JjCkP0xpSr+jnqI+Z4JEP4pElL/3"
    "2S8+9pVJvyVQrj4yFC4+o5XBv3/0gb8tZz8+bDUcvU0OFD+bsJS/vBbxv4PRrD6BTJq+yUXkvgmn"
    "CcA+quQ/I3mpv4towT++PKk/g0PXPn4xC7+uGvC90rKNP2Qvjz49/qY/xtTBPd47A7/tZuQ+Aql+"
    "PsCniz62SoY9a8FPv3zzdT/Q6yi+Vtw8P4F9A0A9mGM+EevPPzcZor+jlro8vdNaPdlezL0w7Yc/"
    "rOLrv4cEnD5LEqG/GUE1v//NlL9ib2k9eY/cvXQoZL+/jFQ/muYfv/tGsD0maR3AnMugP1VuLz/8"
    "IAzAaOE1P5iRgj/iECg/recrwF7Vmr+pJ0VArfO6PaAlkL+7GIE/TjZqPrQY9T8Pq50+OwKtvve2"
    "G0B3b8++adktPxRyZr//vMU9uIebPK2vXr3Ew6U/gsBqP/QXZz002pk/+ad4vxlGPb6isow/vYaT"
    "PmWkkr7aRZ8+KhyIPvpYVr5NPuu+9sbAPJ+2WD8eBVk+IqjZvNiHR0CLSO8/eJZePmAeNcDFKJW/"
    "mob1v7D5Pb7VThA+89ONPzlcuT8EOKY/jRenv2wxpbvLyDg/WvC8vWcS5D+6ZYI/CXtAP1FQmr8m"
    "UnI+Ey2lP+EsNb69UIA/Uv9FwKXvl79eqSC/1GsQv7wyYD8591S/OBXFviJexD+Bkgw/FeoNvqYE"
    "Hb/0ktg/NuhHPzHh4b66FtK/2M+DPap3sT4zXgk+fCMwwOD5Qr8SkuU/ugjbv5R2MEAw78G/tpv1"
    "PwdAbT8JUwxAtuo/P7oeDD54l86+yCcfvgCxtb+GmC0/+sbgPxhkmb5jBIm/MRe1v9wRSr9xS9K9"
    "OFe/PZpaVz9x+P4+aLMXv4NCDj9MyFA/TXcCP+PAUz9xz4+/vJ+WPvXc4T/1ezm/i/OlPyUrYT/O"
    "Pq6+LU6+vndzqz4iF0o/zjChPxLHAEBEYJS/2eYRvwMvAD9UZzA/DAuIP5UOYD6wWC+8uA9hPsHA"
    "wL7YrNc9cVMXP7A5g7+H1wa+TvStPnCs8byVeRBAdJ1gv1uFr7/2yLG+tc+kv7jjbr/YfF4+r6cC"
    "wNZtBj9AMiy/EHLNvvv75L4K+S6/2KxEPwPSI7++/Tw/pndav24OJr0/HTU/QeOLPmQmgz99N4q/"
    "/rOxvkwPIMC0wQXAFYlnP94Fhz+Kihu+p9fJvgJjX7+5lmQ/S2HQuyRLYb4Edf8/rkOLP23Ycz+H"
    "+IK/66L+v4rpAsCHP8+/hqZHP/UN3j54DW++XEB6P7EG6b6O5Zy+9DWTPyz0+7/SSIC/SvSEv/GG"
    "ib9PAoy+JW6Lvx4Yvj/5oo2+SAhUv6WgNj44rOE/iGnpP1d3Jr7R7am/ca5OP2gxuz2g6Py/EYwU"
    "QMnIYD/KsDS+6Cjsu95KLz9rKTs/00Ijvo2AMj8s2+G+ljgbwJJHjD86eqY+KiL4u83CDL6wbbO7"
    "jkAewHCf2z8Nmg7AW1c8P+M+Ob+dn9q/ko4ZPqx6wD5V+80/NGDRv+yx/T7IlZa+rLCvP/nsZj+Y"
    "GYQ/3YCFPhjGob9pjLq+2b7avRqkAb/lzLu/WrDlPbR7ST8ysQDABunrP1z7Cb+3YYq/fKzMOylv"
    "vT7vfNm+2wnCPhGeGz/02Fw/5rr+PltGA785IXM/XMBHP/sKmz5fAL2//sgnPvMIS78F/ac/VIdW"
    "P5tdZb5cq8u/mH7Svw09Qj/sgqu/tvL5vhS+Ez/qa6y/tq+3vWVoHr+/Q3E/BAGNQEA8/j9Ci5++"
    "FQrePg/zXD1MV/c9hUKuPiaqB8DGXEK/BTeiP47aij7BpoG+8vvWvn2YOT+FbyI/C0C6v+iHED8e"
    "Yki/XAMBv/wcq79flRy/Y8kOP7zW7L4td6I+DyeDPi4Waj65UJm+lhhcvzTZAD+8wD8/aFcavCKR"
    "nL/4tGM++jZbP+19PD9FZBQ/mSuKP0NhJ79t1oU/Vojkvzi6g7/t5VI+pAsrP8lnC77WWA+/OCoV"
    "vu15dj+Xcd6/WBy8v9JdgD6Flfo9X92LP7dfm75MqOg+S108v9EOaD9DfkM/Zi0EvwrtXb8Z3M49"
    "6p3mP8qCbL7N4Rs/Fc7hvhqjpL4e4Io/QIzyPvAiiL/ibTa/z7THP3p6975VPUg/yA/vvwvymz/m"
    "KfI+QLgRPqJjir82JWy9e6aUv4SNEcBeL6C/j3woP3QrEb5u18C+h1kUPjOt2D5UXey97pjEPrfv"
    "ub5Di7m+ECp5P2Zpab90oQe+RWsDPs/zHr9+RoM/W8YRP1lBG76OMpC9QoyUvzo0ob9W4Oi+hijg"
    "P1g+g79rVPY/R1tLv9ExX79vAdy+HG8uvjDbJ73ixAY/AuHQvayWab2WvQlAZc82vzrYELz+1MQ/"
    "M9mKPxzTJr/nmJ2/7B0QPw5DUb+e1eO+9ai5vyZj8z6Ttl2/paaMv+qdaD4CNPW+/OVOv2hujT/y"
    "ebO/yVfWv7Zhwb9bvJS/2DX0PzubTb8xLsc/jHnyPolpQL96Vae+Fi6ZvAt9E7/EaJ28i6Orvjhd"
    "xr8z85A//Ig7QCuJOr4pLBBAODKwv4dBO7yRDW6+fdNUv8F32T4sSOS+t/PWvpHRZ74KpL09TGQ0"
    "vk9QrL9kdMQ/Tck4P2qgUT4iwzy/yX8fv+iKaL8bQGa9po8qPSg9nD8/c6O/qhi5PyaTM76ulNm/"
    "Z12Wv21/yj/GXAU+d1UPwBmdMr95H5c/NkbkPhweo790A5K/7wxXPj8s6L6UlEA/Aj+WPrYEL76h"
    "7WK/GH8xv8jMZ7+ygTe/5Lp3P1m5nD+CQJu+yXm9v01X/D3e+Xu/EfI1wJbCoD3RUra/OkJAPyZI"
    "zr8D0+U9OLCAvzRAfb+4MBq/AxxUPukIZD9blFw+RMSDP75QOzuKGXa+Lz9Qv86yzj+vVgc/VxyI"
    "vIMbOMBmV94/VtkMPzFwkj/rVDo/ZP+yvkEyu78Kd7g9r7U/vtWNer+FsC2+NgKxP+C5lT7EMJo/"
    "UvxSPlJtLj/pyJI9gh4ovUAzN8A7gHk90JbvvgOHjT/vx4w+UUzZPi3Vgb+8VlM/pBqbv1tn1r4I"
    "l4u/F89zP3XsMjzcuPc/pYFxv6CXnD+Z1re+8lXDPt6Tpb8/R2I/NPUcPgsaGr8yGbk/vkjhvUdP"
    "mL3Uve++DWyoPsHq1b8uIbc+bLyFP3MQmz+HpC6/JhwTvudjw7+sx3O+rOgCv1wjoz6CKJE9Hzgf"
    "v3pbCT9+A2E9b2+cvlnCmr2RKI+/bmmhv1BugT42s/U+nBGuPgrWkr8FX5m+1a0UQKD+Ar+jak4/"
    "LmauPlQQRT9TIgtAHkJ0P8w3AT+oTb2/r0rDPzuUkj6JSQvAQm+JP21F/T85KFc/kteuPpsHEr4w"
    "Ltu/cN0Hv3SfY71Ioy2/Og/Bvyg5/j8jBui/x3JpP9Y6MT/0BwHAb9IKP97urb+PwKA/1sWvvv17"
    "Rr7XAyE/V98uvU0cPb9tkwXAKgwkPyIKFDxgooO/v9KDv/JgLb/Yfg8/9q2vvkPxfb9/d5C/b6an"
    "v93kTj7lc/u9axgQvyXxCT+2XI2+6pxBPr47/T4Ahu66gFWzvRYm/z/9c1I+6QiDPsqOYT0XkBA/"
    "YAVuvQAwKcCB5VI/N+OwPg+8/j53K5W/GPJtP590Hj+GAhs+iyfBP/cmyr91ao8+CcjAP5CJ6T1z"
    "dwG/GMGWPo2iuj/ZNk6/I5ZZP1+Ehb+zOP2/qZseQIg7oL705Ke/3x8mPNI8uT9e75e+fL7IPjBd"
    "Ub3phm4/T1MSv4jUJT6TL8k/Y9mbPu8lYT5OKY89T/zrvyDnuz7JqCG/sZgePlMKn70G+RA/hu7Q"
    "PjFL+768RrK/m0g7v0JLhr9PaQG/i/R5v1ynqb9CEX2/EhLgvg6SOT5Nm1+/v+eoP49izj+sGi69"
    "oBaav/yZoj/oepw+WicCQJyFKD89DfA/XxmvPuiegD59MYs/QzUBQDOywL5CYqU/kP5Zv0duDr4E"
    "R6w+59jLvu5HjD9oqRnAVQOAvdcXA8A4a0c+CHQlvoJ9F7/N7aM+f1o1PfF5ZT/qas89/aKGvT2G"
    "vL//YbO+AJhjvx1rjj9obq0+P1+8v6tjkz4uoyE/dYEMvtP4y79jeHO/Ju/hvlR4+L4UKQY+coHP"
    "PwePB784yCO/uVxovwaJML9lA6C/K2MJv9f9+T9NgJG/oHZEvdklbz/w8Ma/v2lmvkqb/j7/UQu/"
    "xC9VP9C+sz2rw5K/XuPIvzn2Rb60W7+/DFjWPwbNrD4tTvU+uF7SPg2+JD6hft8+Y4CEP/oeIj6c"
    "ITg/HCqNPma20r6dUuK/MVvYP5dfKT8XUIo/2vFOP6EXg780ykU+INHgPsAQdb8RC4c/1ie5vy5P"
    "Yz2KFZm/Q2xMv4iTpD8k7a6/8SZqvhURQr/+j3s+tkbaP9ZXqD+pzjrAAEWAuX4+Yj+Qfa4+qP4h"
    "P7UQND92nCM/Krc4v5sipD+pib4/oo+YPuxemr5d1yq/jgMYP7Xdgj6PK4S+ORLTPaogIj/S8WO+"
    "S7iTPwPcKkDDtke/DpXAve8VGcCXJVw/on7Avkj8cz+fTKW/2K+SPz/mA7432Zo/dmykPkxSUT8x"
    "iPY+BBomvtLvHb1SPk2/4v5Pv12cjL5kh6G+zQ48QCk1dz7rfNq/TF5fv/63YL+lc1u7uQbdv2Z5"
    "tj/H97Y/gkMKvwzt875n3GG/1TyqPthiSD4AwyNAD3rKvi7LsT9hhy6/I7ljvpFdAb8EG++8OLQS"
    "v8nd/L7mNg8/lokLwOp2aj6XdMO/RKfCviayob0Slm69QpKLv0G6Kb8tOuc+ExkFwDqjjD8Qxto/"
    "jscpvyl/LT+Oapo/fB6jPcddAz8Z8wo/dXILvR5kLj+Ick0/ky/Xv8cNhT+Yp0e/jLjkvg/Y0D+0"
    "Ys890JIYP/bvoD8l5pA/R/2QPygsCb9fWVe/sUYcv/rpKDyJsO++BentPwHXgr99IOy/nkKUP65G"
    "wb8Evma/OS+PPhuFAT+Cb5W+ITVsPzG+Cz8Ltti7IXbwPln23b+MdiU/AaafP5rwpD114s6/cBzE"
    "v8ah0rx2OOG/OAoMv6EcC0Cv+WK/MEyIv7PfND5cqqA/3oYov6dvoj8ix+w/bqliv+SwwL9dd2e+"
    "KvhNv7+VsD/1et6/JSX5PwuClD+9HxO/9h7TvEwn0zsMfzW+h3CePaFwhj9UZgI/EDJIP3VzLUDf"
    "oEW/qzw8wMR05D4ScHk/yaWuvXPgm78w6ns/h1ZKwIpsxb6JKY4+QpeIPVWEDL9Ec4K/ESx+vwy5"
    "MD/lEVO/DoEFQBIAvT2qepO/8sSPv5lPer/aCkO/b6BGv9Wg2D/cBhc/GWB3vaNujD9Lnrw91H7B"
    "vq8GxT5ODQJAZ0EYvl+dG0Bd4i2/qXeQPt6Ikz8b75W/fPmnvivqSj8+VqQ+kjkgv09ymT1nEGo+"
    "uG3UP6Y60r6DabC/HKfPv7KUTr91ZW6/y880v4sVhT9ISEg/m6pUvyUAnr/cjtg/eCKrPGP+fr8E"
    "/pM+xz8IP0e+pL6nQcY/JmnlvvEIpz1JlHA/PMSAv/c+2T5VxEQ+GnpAvq/fVj78TZQ/6HgNQHp1"
    "/7+JJUo/b+qLPYdALUC2AtY+eKMJQFJApD/1MVy/EOvKvh8cAj5qKWy/XaLZv4NvMb8/sQu/AFlm"
    "vwaJTj2MwSZAN2CovYwsij+Q5fI+zWLyv3ikJr+ISQE/JuIWv2Yq4b99vRG/mhgKQD3isL90nao/"
    "py4iPy8mgL5nPDU/WI7Nv+l4nT6HNiu+btZaP1fvyb7NYAe/vCW1P6qVkr4mKGa/yCf6um/9Szwd"
    "DEs+GIr3vsnjqb8QULQ/MexqP021Wjwagy+7QIWxvT5Qoz4MoR69mKpWvkRxhT9d1fW97F45vkkz"
    "Or4MT34+00FSv86cEb+Wuuo/yCGfP5SVt75Jal+9kOpgP89DEr+0P6y/TPWOP4CiLTwVC7O85LSC"
    "PlEK1b/qxvG/s6YJvzZD3L5jYhs/EJkQvycno7/rzE++RycSP8oUaz9c2E+/+3m2P+S0+b8kUSq/"
    "SC6YPx/jfj+/fES/yG6QP/rBAT/4hi0+mtiJPpgIXTzwPIy+mZx7v064Jr+YHoc/mqSZPitM3777"
    "QT2/nSl/PremKz5STSU/GLn6vqT3/z+QDVm9lAEyP04vaz9mUPK+8n2aPRrwL7+WMFg/bahxP9S2"
    "Fz/Hgt8+ZCwov6JMX75m4Da9FNTiveBtd73ovSpAhK8yPxbw3z9oyAU/VAiAP9Vd2b/6J9o+xg2m"
    "vmRyxD/s8Oi+t9iYP84hEb8hi82/tgffvwRjzz2esbg/POEEP8YbKL58mCE+FCxsvxS7Bz5j/Wk/"
    "Ob33vBvP1b8VNqk/C2STvzXWsz+molE/GQMEvpULkT6pMU8/xqTivyUqRsC1bEY/iyTYv8Xmfb1M"
    "GfU+9l6gP/nr0L9cyY6/6PTIPoB2ZD9mp4S/RC49v9pZN76+7O0/teGEv/JiYT7EDKE+x/bCPqN9"
    "bj7m0wDAEuiPvxZSu747lB89Fe2+v8lPYD2qMO6+T6u8vYetrj9NQx0/oRvuP0NpBD8LD6294KDH"
    "vtG+Jb+0EgHANwMSP1qWVT6J2PA/XrsyQFWbM7/xtRO+xH+nOxgJEb8+Pkk/XGbIP7TGib+bS1G/"
    "DxfNPmu6tz+kuP6/1Jrdv8TXIj9idG29l1MOQJWxkj4jSYI/q3HOPvjDbL4agsQ/me8dvy4jAr9Y"
    "55E/6+0rvu9qw78cd46+Rx86v8m5j78J2TO/oFTXOWSEWr/0vuU/fSX3v7ewJj9Abag+mDq8vnZh"
    "aD887AQ/zY0+v9Pj9z/R+x2/454DP/Bx3j5S50U+riPZvx5/sD9Mray/0yIVPz3of78L9vG/oPit"
    "v2GDXD/a0o++Xyluvz02ob9/bhQ/VuG6vh3xVz/at929t7UWP2oykz69QVE/XuidPgtl8L7aaLO+"
    "ft12PzU+TD+rCNI/Wj+YPseKcD/Fqb0+0xeDv9krpr6G4Ow/RE2YPzrOKz+5s0Y/YvZMPzRUi75D"
    "6PE/nhT1Pr6+hT2GN7a/AkyfvipP4j4I5zm/6nMuvy6/BT3c/uI/WsVDPiug/D+a/8I+TxpFP16v"
    "5L4wXdY/JhYVvqos2b9eqTk/aZzcvivJ3z/NYJe+SIwGPpygiTwERO89jnY3PvmwCD+IttM+Ka2N"
    "v5jcAT8N47U+FRqvP2KW+z4YHxM/IsiJPnP1Sr/BV/U/GrlPvmAn9r/7Ggq/CKHMv6DPsz+epQA/"
    "+0Bjv/OSuz9stuC/xhGOP9OTjb5Kmri/M8uqvjACCz8aRUy+LBEyP+fy276mnbO/y46SvsTW0b9z"
    "D+y/4XrrvCy1wb86G5c+6JZlv6RXQr/cxJ++yK3nv4hWcr9hLC+/8iTLPkUmeL+qZyi/IYCCv+dK"
    "iz+mdNS/ovDsPjSM6z6/hkW+eIv/vhCHiT+/KKA+sGASwGbCMb/cdRS/7STAvxAxYz8JBBw+9aEL"
    "QDnt0D6vcs4+sh8Hvzx3w77uRw0/f/1sP136bL7kwY4/B8EjvznlmT5B0Pg/34M5v2N3OD+xSKs/"
    "kgETv+/AjL+g57k7y3aqv0gkFz/CbZI/gbi8Pxunrj+gA+29mxaOv2qFJ0AcxlS/2twbPukEh7/n"
    "Bes/L9cpP9EqZD4hRO4/uM0MP28ztr4EhyQ/SNO7P2iyDMDYQBa94cmoPwhuA0DGzRg/GT+1Pqev"
    "ZL/ngL6/+m8Tv84wCr9PaTg/HlCtv9ftor/JaK6+8aWLP5ghkL94w2I+bxk7PxCnkL6oZ1y/otrK"
    "PtLwRz9X75Y/oQCvP6n//T4npgNAk4PEPimmzT4qsMW/Z6ygv8q+a72UINm+tfrAP7HhMr9FUg6/"
    "iroHwFB/JT+QwKg/c5lpv7KNqj5Fp4W/Caumvypo7b43u8m/L0w6v7uoBECiKAu/Hd/TP8DepD7f"
    "PGM/GCUFP+gtIj+L6MI+J4Unvc5cEL42SA4/zGX3PtCOgT/fEWA/h93pP6yFED9lRHw+ynmUPpf6"
    "Hb8LwRE/7Y2GvtCgV78PNXC/wvbSvQVt9z7nr5I/JTkBP991rzzdLIW/bdqMvz/IRL8VTfE/wG8R"
    "P0a+i75TbEy+99tlvxJt579nnAO+9X0OvxKSZT5Y7Xi/E3wjvxIl5jwEh4a/KUrQvv0GMj8VXdm9"
    "zRrMPkRZkT4wxyu+Dv5XP0Zxgr9E+US/qyQoP05oPj2MYhC/7Zf+vj5dBsC9LhtAPV+rPgo+iL22"
    "Lqi/7kPBPnuNkr5XgsU/2U2YP2/s+T4s84m+e0wJwKixuj6b+x4+jXyAPo4Igb7WRkS/MBHYPyoI"
    "p76zTow+O3BGP7DzKr4o+G28rZcTPizDyz7ypT6+JiikvnA5hD8gqtI+HVwmv9yLN7+/6Iq/MVCg"
    "vaV/gz4135E/zG+NvqdLgL+ldWq+t9MBQEQVV79h+y8+D9VIPWRvsT40MkY+wrphwDozNz8Me4M+"
    "dulTv9f3Ar0o9vw/5zLmPx6qKb+XGBo7rvmjP/z7xr6IOdA9a4uMPxjRSL8n636/L2aYPjScTD8R"
    "mta+veZuP4MvIz8BO8U/Pu3rPoF1lz4rSG2/xWWZPg9Phz8FcDk+NEc3P27rID8A3we/p2vQPzyf"
    "uD+XJWa+Jh0tQGP15L/1x3I+tlZDvyLEBb/IITs/rQ38PtNRKL4+Q0y95VUBvr+YVr4Z7gE/fk3q"
    "P0k7Tr8/ZwI//3HFv6uQ8T594NC/uSPJPdNkgD+Q36w+SSMqvlsZAUDiI+q+2vd2vpuLvb2E7he+"
    "Sqp7PzBJRj7Eo8o+30H+Pw3BlD55rRE/F/CzPl+bkj/ykAfA6GPFu6SMdD2LXN++oz2OvgehlD9L"
    "FKc/DaGBv5u2pT/qF+8+F0YmP1AHHcCC0eo+KKhxv9x3nj9tu00/gL0wP8Mclr9YF0I+SM1rvy5E"
    "Xz9TVZW/wSUpv9kc875I5XC95KkyP/vuz7/vsCG/xcylPmXPIL7FVWE/yOFEP/rklr9416e/tDGp"
    "vaPGCb/6G6w/gK2Gv9hXf7++tYI90oCsP9rOyL4pAhk/4OpnP9Pbgj+fad2+G3u0vw0ytL/l55M/"
    "U/aCPxHnor/Cwc6/24kRQFNvbb+Z9LG9QYVDv5PuWD+56Gw/QeAkv/T8RT8pMgs/WU6lPm+sk77A"
    "75I/1EeOvhCXkz1G2lu+oD52v4VDiL2q4qO/NemwP/Q9Kr8Aops+DzCbv+bvU7842aa+4VSlv9FR"
    "S7/70yy+RGsgv0BVkb4yKE+/rZKHv1Yzwzy7U4U/06+LP/inNb9D1ns/FBXZP1dAvb5elqo9RZOG"
    "P5tOkL8xjNo/zg2ovr7pnL6afvs+hAXtvnRbIb/QfuA/4U86v9FNx7++8Si/6wr4Po6hgb8yDaO/"
    "BwckvxYPNL4GRvg9oKacP2vhE8DNxx2+vR1nv6n+FECSJCi/E0savYLTmb9uGfi/o9Ffvo0Atz4d"
    "cc8/J3QNQHEXQT/lH8w/orZgPyQg5b+0T1u/bHyUPTlGFL/ZOwVAGvuHvzerpL6UTFa+vRYRPOjY"
    "Pb9O54s8onVZvG3Rjb+jPiI/cMqrvkw1BUBiYjE/tsfOPixEjj+HL4K/mF4Lv6Rvqr/O+Yy9qoLR"
    "vcX0jj+5UvS/KgbovyVUCz9h7qo/b3gwP1TQZb5KPVe/mCIjPyOR2z9sFAO9gIlcvrObLr/3WeE/"
    "WWvNPhExCT8DQdq/A97CPthY3b6RwnW/OJKpv3ROWz9tjKG/mLWfvw8XRb+q59g/SOaDvytvtD99"
    "n6G/n6jtPJqZhb/fvo0+l9tjPtKYXr+28ks/H7qfPdUm9D/K0wRAC0Guv9KWiT8W7Zq+DSYTvx5j"
    "AL/oybA/qNNsP2oa9r8J/eA+prDfP7n4BcCgQze/sikAPg/PTL+ioJu/9OOAPqw1JD+DWQo/LjtM"
    "P+m6c75vyha+9i1xvs5cnT6sFPu+Pwp4Pxul0L/FoL4/PT27vxyMqD//jR2/F12Uv5HNLj/1ZuE/"
    "n8C2PpIo679RMgdA/52SP3NmYz9XWdg+S4JUv72bfT/ePARAqL6CP3ImwD/Jrgk/GQWGvvibRT/w"
    "A0O857Viv797nD8mmyy9BqiRv8Lcsj5ZoL4/pzgDP7xucr96YRg9gZNCv0rBPb7HVdo+TLsDPfRv"
    "zD4p3z4/V9GXPwJiKL/EKzG9GGw2PkZrgz8PlY4/1A6DvlBvEz/X9n09EkdDP5d8TsBbYNS+z9ok"
    "v06bbT8ON62+vkn9v3NjtD8J3My+O998v0HI77/MS3W/fhPqPrU/pz9K8N+/pOnHPpVyBD4uAoA9"
    "5QqCP3i0AT5vkAXAD9WIv45JTb8xDA9ANltfv32EJz7vL9u+l4YGvZ8/Yb827EO+Uso5Ph4N4z5l"
    "eOo/yt2Ov1ZatT9Kb4u/FsUuP4EGqT76kDU+LAKJPlK4+T5HpNW/HPMcP0fbZD8mU60+wNNmPsUg"
    "6r+RW5U/buSnvtHqOr/SNak/rayRPvK5n7/hIAs/zPU/Pqh4Z76UG7U/TSrsvubxWr+55nK/g7v+"
    "vrnlgr/oyxM/u97AP1YukL8cfS8/5xu/PUJQt79WjFe/6FnHvkploL4hFEs+usJJP6hIzLtrYEW/"
    "ygxhO8K1vD9MGLu+WmEyv0ITED8owmi9e0GgPqasXj9Do3I+L0PKv6sVAr+P4SK+5sO9P+CzVj/Y"
    "4EG/1VAFvy/UIMCX5ju/tkQ0PrtPuz9M3sq+EpMvv05LmT76nw4//SuVPYegLb+AQL6+qm/UPUqV"
    "hb6U098/lot2vi/Zrz/cSYy/lNyyvyhqlr8qQmk+v/wsv3ronb+kRUc+TCSUP+aVEL8jcT4/2HgV"
    "PyQOLz+dnf0/QHHtvtJcq75ulYQ/g1W+v4wSIb+QDMa+ghyQPzBl0r7Ywwc+Ha9FP0+8vj/fqQjA"
    "1ZZ/vweWMb2yo52+6Bh2vkBFDb9aq4W9J98BQM9cYj+BEQS/1pz+v8Dutz77Sn6/NeqfvxAPWb8g"
    "Sw+/X5IDP9qROT/QFVC9ByNNPuL2NT9auP0+AnyzvtAEor9X1Om+Es29PtwS9b8Pns+//mvlvxX5"
    "bz9zggLA1gSrPiMm2r/61MC/zW9SP5L7uT7NWXk/ul8pv+MJEkDb03A/1ODuvkxz+L//H5e8QT9C"
    "P3lmqL7Xsac9J5MSQHIMLD9bgEI/NkC3vrea8T5Bdoe/Z3RsvzXNcb+4UrC+le4Hv8KeXL58bYy/"
    "MD2yP8EOPz9Hz0w+DmToPlgfJL+7JJk/mJPHPeEq3L51ml++RxuJvpnN279RXLa+bsuKP+GCyz6M"
    "/ga/QjGmO2FJ/T2CI/i/PPjtPIHo3712xZg/UpjUvnwB/T48M5k/S9WUP9Rg1T9oIGxAgF8MQO6U"
    "VD4Tgx2/z8VzP2PKPb8XYaS+Ex6Tvw04t7+M2oo/CukDP+764j9OHWe/YT3Pvnm317/b0Vu9fUhJ"
    "P4WpwD03/Xm/ewbzPtn1C767ZI49fSQePwdEjb8dx0Q+iCAjviSs/b8ks6Q+oceKvkbv/T5rcFu/"
    "/o+JP/0FEr7HB18/1CDuPvVOtL/LVbM86IPevzgKz7+kJfk+qNYJPwXK9L7iw32/LW/Mv4Y1Mr4A"
    "hzu/mqsjvuu8KL/oWSE/gV+CP/mvgL/WjDK/IZ2hP9ndp78Havc8qCQovrmBqb7z3r08sTMQP+0g"
    "TT8ZQvU/k3mMvoiUML/P1MA/mzVWPjxrpz+sYa2+H1SWPwpY879BdkA/rc4NP7B0oj+jxuA/3Xtf"
    "P7xNgT9VaLc+h9KXv/pMij/mXpm/FK7ov/3lhz14SOC+3LidP2Q+DD+LgTg/yuc0wJvxVz4PhRVA"
    "d7hnPjImRz/Hb8K/hwycPu4myj50XC2+uPbyv5oRUz/qdou/56PsP5N5Gj/KY8k63b9xP+p7xb3o"
    "ZQFAKQUGv06atT9m5V29/Oq3PmQ9Db/i7Zi/3ek0v0ESor9aCRw/I6qGvyXQB7/b/Ha/N54ov1Mr"
    "oD56tfu/8zZSv1l+DD/5kwJAtQWPPJ3uLr9Kxd2+ECUivSzpPD3QmhvAHF9UQD4IT7+1JBA/NhuW"
    "P7Kyb758cwlAkIOBPxLRi77KJc8/sZm+P6Vgdj8KgqI9",
        [1, 3, 32, 32],
    ),
}

# ── Inlined ONNX op dispatcher (no project imports needed) ────────────────────
"""
Shared ONNX op dispatcher for JAX, TensorFlow, and other array-API backends.

dispatch_op(node, values, np_like) executes one ONNX node using the provided
numpy-compatible module (jax.numpy, tensorflow, numpy, etc.).

Rules:
  - Initializers are stored as plain numpy arrays in `values`.
    Shape-extracting ops (Reshape, Slice, etc.) call np.array() on them safely.
  - Intermediate computed tensors are framework arrays (JAX/TF traced).
    They are NEVER passed to np.array() — only used in framework ops.
  - The dispatcher is framework-agnostic: pass jnp for JAX, tf for TF, etc.
"""
import numpy as np
import onnx
from onnx import TensorProto

_ONNX_DTYPE = {
    TensorProto.FLOAT:  np.float32,
    TensorProto.DOUBLE: np.float64,
    TensorProto.INT32:  np.int32,
    TensorProto.INT64:  np.int64,
    TensorProto.BOOL:   np.bool_,
    TensorProto.UINT8:  np.uint8,
    TensorProto.INT8:   np.int8,
}


def _attr(node, name, default=None):
    for a in node.attribute:
        if a.name == name:
            if a.type == onnx.AttributeProto.FLOAT:  return a.f
            if a.type == onnx.AttributeProto.INT:    return a.i
            if a.type == onnx.AttributeProto.STRING: return a.s
            if a.type == onnx.AttributeProto.FLOATS: return list(a.floats)
            if a.type == onnx.AttributeProto.INTS:   return list(a.ints)
            if a.type == onnx.AttributeProto.TENSOR:
                from onnx import numpy_helper
                return numpy_helper.to_array(a.t)
    return default


def _np(v):
    """Convert a value (numpy or framework tensor) to numpy. Only for initializers."""
    if isinstance(v, np.ndarray):
        return v
    return np.array(v)


def dispatch_op(node, values: dict, F) -> list:
    """
    Execute one ONNX node.
    F  = framework module (jax.numpy, tf, numpy, …)
    values = name → tensor (numpy for initializers, framework array for computed)
    Returns list of output tensors.
    """
    op = node.op_type

    def get(i):
        if i >= len(node.input) or not node.input[i]:
            return None
        return values.get(node.input[i])

    # ── Element-wise arithmetic ──────────────────────────────────────────────
    if op == "Add":       return [F.add(get(0), get(1)) if hasattr(F,'add') else get(0)+get(1)]
    if op == "Sub":       return [get(0) - get(1)]
    if op == "Mul":       return [get(0) * get(1)]
    if op == "Div":       return [get(0) / get(1)]
    if op == "Neg":       return [-get(0)]
    if op == "Abs":       return [F.abs(get(0))]
    if op == "Sqrt":      return [F.sqrt(get(0))]
    if op == "Exp":       return [F.exp(get(0))]
    if op == "Log":       return [F.log(get(0))]
    if op == "Tanh":      return [F.tanh(get(0))]
    if op == "Reciprocal": return [1.0 / get(0)]

    if op == "Pow":
        return [get(0) ** _np(get(1)).flat[0] if isinstance(get(1), np.ndarray)
                else get(0) ** get(1)]

    if op == "Erf":
        if _is_jax_module(F):
            import jax.scipy.special as jss
            return [jss.erf(get(0))]
        else:
            import tensorflow as tf
            return [tf.math.erf(get(0))]

    if op == "Sin":   return [F.sin(get(0))]
    if op == "Cos":   return [F.cos(get(0))]
    if op == "Floor": return [F.floor(get(0))]
    if op == "Ceil":  return [F.ceil(get(0))]
    if op == "Round": return [F.round(get(0))]
    if op == "Sign":  return [F.sign(get(0))]

    # Element-wise Max/Min (binary)
    if op == "Max":
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        result = tensors[0]
        for t in tensors[1:]:
            result = F.maximum(result, t)
        return [result]
    if op == "Min":
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        result = tensors[0]
        for t in tensors[1:]:
            result = F.minimum(result, t)
        return [result]

    # ── Activations ──────────────────────────────────────────────────────────
    if op == "Relu":
        return [F.maximum(get(0), F.zeros_like(get(0))) if hasattr(F, 'zeros_like')
                else F.maximum(get(0), 0.0)]

    if op == "LeakyRelu":
        alpha = _attr(node, "alpha", 0.01)
        x = get(0)
        zero = np.float32(0.0)
        return [F.where(x >= zero, x, np.float32(alpha) * x)]

    if op == "Elu":
        alpha = float(_attr(node, "alpha", 1.0))
        x = get(0)
        return [F.where(x >= np.float32(0.0), x, np.float32(alpha) * (F.exp(x) - np.float32(1.0)))]

    if op == "Selu":
        alpha = float(_attr(node, "alpha", 1.6732632423543772))
        gamma = float(_attr(node, "gamma", 1.0507009873554805))
        x = get(0)
        return [np.float32(gamma) * F.where(x >= np.float32(0.0), x,
                np.float32(alpha) * (F.exp(x) - np.float32(1.0)))]

    if op == "HardSigmoid":
        alpha = float(_attr(node, "alpha", 0.2))
        beta  = float(_attr(node, "beta",  0.5))
        x = get(0)
        return [F.clip(np.float32(alpha) * x + np.float32(beta), np.float32(0.0), np.float32(1.0))]

    if op == "HardSwish":
        x = get(0)
        return [x * F.clip(x / np.float32(6.0) + np.float32(0.5), np.float32(0.0), np.float32(1.0))]

    if op == "Mish":
        x = get(0)
        return [x * F.tanh(F.log(np.float32(1.0) + F.exp(x)))]

    if op == "Sigmoid":
        x = get(0)
        return [np.float32(1.0) / (np.float32(1.0) + F.exp(-x))]

    if op == "Softmax":
        axis = int(_attr(node, "axis", -1))
        x = get(0)
        x_max = F.max(x, axis=axis, keepdims=True)
        e = F.exp(x - x_max)
        return [e / F.sum(e, axis=axis, keepdims=True)]

    if op == "Softplus":
        return [F.log(np.float32(1.0) + F.exp(get(0)))]

    if op == "Clip":
        x = get(0)
        mn = get(1); mx = get(2)
        if mn is not None:
            x = F.maximum(x, F.asarray(mn, dtype=x.dtype) if hasattr(F,'asarray') else mn)
        if mx is not None:
            x = F.minimum(x, F.asarray(mx, dtype=x.dtype) if hasattr(F,'asarray') else mx)
        return [x]

    if op in ("Identity", "Dropout"):
        return [get(0)]

    if op == "Cast":
        to   = _attr(node, "to", TensorProto.FLOAT)
        dtype = _ONNX_DTYPE.get(int(to), np.float32)
        return [get(0).astype(dtype)]

    # ── Shape ops ────────────────────────────────────────────────────────────
    if op == "Transpose":
        perm = _attr(node, "perm", None)
        x = get(0)
        if perm is None:
            perm = list(range(len(x.shape)))[::-1]
        return [F.transpose(x, perm)]

    if op == "Reshape":
        x = get(0)
        shape_raw = _np(get(1)).tolist()          # always an initializer → numpy safe
        orig = x.shape
        shape = [int(orig[i]) if shape_raw[i] == 0 else int(shape_raw[i])
                 for i in range(len(shape_raw))]
        return [F.reshape(x, shape)]

    if op == "Flatten":
        axis = int(_attr(node, "axis", 1))
        x = get(0)
        left  = int(np.prod(x.shape[:axis]))
        right = int(np.prod(x.shape[axis:]))
        return [F.reshape(x, [left, right])]

    if op == "Unsqueeze":
        x = get(0)
        axes = _attr(node, "axes", None)
        if axes is None:
            axes = _np(get(1)).tolist()
        for ax in sorted([int(a) for a in axes]):
            x = F.expand_dims(x, axis=ax)
        return [x]

    if op == "Squeeze":
        x = get(0)
        axes_t = get(1)
        axes = _attr(node, "axes", None)
        if axes is None and axes_t is not None:
            axes = _np(axes_t).tolist()
        if axes:
            for ax in sorted([int(a) for a in axes], reverse=True):
                x = F.squeeze(x, axis=ax)
        else:
            x = F.squeeze(x)
        return [x]

    if op == "Expand":
        x = get(0)
        shape = _np(get(1)).tolist()
        return [F.broadcast_to(x, shape)]

    if op == "Gather":
        x   = get(0)
        idx = _np(get(1))          # indices always come from initializers
        axis = int(_attr(node, "axis", 0))
        if _is_jax_module(F):
            return [F.take(x, idx.astype(np.int32), axis=axis)]
        else:
            import tensorflow as tf
            return [tf.gather(x, idx.astype(np.int32), axis=axis)]

    if op == "Concat":
        axis = int(_attr(node, "axis", 0))
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        return [F.concatenate(tensors, axis=axis)]

    if op == "Split":
        x = get(0)
        axis = int(_attr(node, "axis", 0))
        split_t = get(1)
        sizes = _attr(node, "split", None)
        if sizes is None and split_t is not None:
            sizes = _np(split_t).tolist()
        if sizes is None:
            n = len([o for o in node.output if o])
            sizes = [x.shape[axis] // n] * n
        sizes_int = [int(s) for s in sizes]
        indices = np.cumsum(sizes_int[:-1]).tolist()
        # jax.numpy.split uses indices; tf.split uses sizes
        if _is_jax_module(F):
            parts = F.split(x, [int(i) for i in indices], axis=axis)
        else:
            import tensorflow as tf
            parts = tf.split(x, sizes_int, axis=axis)
        return list(parts)

    if op == "Slice":
        x = get(0)
        starts  = _np(get(1)).tolist()
        ends    = _np(get(2)).tolist()
        axes_t  = get(3); steps_t = get(4)
        axes  = _np(axes_t).tolist() if axes_t is not None else list(range(len(starts)))
        steps = _np(steps_t).tolist() if steps_t is not None else [1]*len(starts)
        slices = [slice(None)] * len(x.shape)
        for ax, s, e, st in zip(axes, starts, ends, steps):
            ax = int(ax) % len(x.shape)
            slices[ax] = slice(int(s), int(e) if abs(int(e)) < 2**30 else None, int(st))
        return [x[tuple(slices)]]

    if op == "Pad":
        x = get(0)
        pads_t = get(1)
        pads = _attr(node, "pads", None)
        if pads is None:
            pads = _np(pads_t).tolist()
        mode = _attr(node, "mode", b"constant")
        if isinstance(mode, bytes): mode = mode.decode()
        n = len(x.shape)
        pad_width = [(int(pads[i]), int(pads[i+n])) for i in range(n)]
        if _is_jax_module(F):
            import jax.numpy as jnp
            return [jnp.pad(x, pad_width, mode=mode if mode != "constant" else "constant")]
        else:
            import tensorflow as tf
            paddings = tf.constant(pad_width, dtype=tf.int32)
            return [tf.pad(x, paddings)]

    if op == "Tile":
        x = get(0)
        reps = _np(get(1)).tolist()
        return [F.tile(x, [int(r) for r in reps])]

    # ── Linear algebra ───────────────────────────────────────────────────────
    if op == "MatMul":
        return [F.matmul(get(0), get(1))]

    if op == "Gemm":
        A = get(0); B = get(1); C = get(2)
        alpha = float(_attr(node, "alpha", 1.0))
        beta  = float(_attr(node, "beta",  1.0))
        if _attr(node, "transA", 0): A = F.swapaxes(A, -1, -2) if hasattr(F,'swapaxes') else F.transpose(A, list(range(len(A.shape)-2))+[-1,-2])
        if _attr(node, "transB", 0): B = F.swapaxes(B, -1, -2) if hasattr(F,'swapaxes') else F.transpose(B, list(range(len(B.shape)-2))+[-1,-2])
        result = np.float32(alpha) * F.matmul(A, B)
        if C is not None:
            result = result + np.float32(beta) * C
        return [result]

    # ── Convolution ──────────────────────────────────────────────────────────
    if op == "Conv":
        return _conv(node, get, F)

    if op == "ConvTranspose":
        return _conv_transpose(node, get, F)

    # ── Normalization ────────────────────────────────────────────────────────
    if op == "BatchNormalization":
        x = get(0); scale = get(1); B_ = get(2); mean = get(3); var = get(4)
        eps = float(_attr(node, "epsilon", 1e-5))
        nd = len(x.shape) - 2
        bc = [1, -1] + [1]*nd
        x_n = (x - F.reshape(mean, bc)) / F.sqrt(F.reshape(var, bc) + np.float32(eps))
        return [F.reshape(scale, bc) * x_n + F.reshape(B_, bc)]

    if op == "InstanceNormalization":
        x = get(0); scale = get(1); B_ = get(2)
        eps = float(_attr(node, "epsilon", 1e-5))
        axes = tuple(range(2, len(x.shape)))
        nd = len(x.shape) - 2
        bc = [1, -1] + [1]*nd
        mean = F.mean(x, axis=axes, keepdims=True)
        var  = F.mean((x-mean)**2, axis=axes, keepdims=True)
        x_n  = (x - mean) / F.sqrt(var + np.float32(eps))
        return [F.reshape(scale, bc) * x_n + F.reshape(B_, bc)]

    if op == "LayerNormalization":
        x = get(0); scale = get(1); B_ = get(2)
        axis = int(_attr(node, "axis", -1))
        eps  = float(_attr(node, "epsilon", 1e-5))
        ndim = len(x.shape)
        norm_axis = axis % ndim
        axes = tuple(range(norm_axis, ndim))
        mean = F.mean(x, axis=axes, keepdims=True)
        var  = F.mean((x - mean)**2, axis=axes, keepdims=True)
        x_n  = (x - mean) / F.sqrt(var + np.float32(eps))
        if scale is not None: x_n = x_n * scale
        if B_ is not None:    x_n = x_n + B_
        return [x_n]

    # ── Pooling ──────────────────────────────────────────────────────────────
    if op in ("MaxPool", "AveragePool"):
        return _pool(node, get, F)

    if op == "GlobalAveragePool":
        x = get(0)
        axes = tuple(range(2, len(x.shape)))
        return [F.mean(x, axis=axes, keepdims=True)]

    if op == "GlobalMaxPool":
        x = get(0)
        axes = tuple(range(2, len(x.shape)))
        return [F.max(x, axis=axes, keepdims=True)]

    # ── Reductions ───────────────────────────────────────────────────────────
    if op == "ReduceMean":
        x = get(0)
        axes = _attr(node, "axes", None)
        if axes is None:
            at = get(1)
            if at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.mean(x, axis=ax, keepdims=kd)]

    if op == "ReduceSum":
        x = get(0)
        at = get(1); axes = _attr(node, "axes", None)
        if axes is None and at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.sum(x, axis=ax, keepdims=kd)]

    if op == "ReduceMax":
        x = get(0)
        axes = _attr(node, "axes", None)
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.max(x, axis=ax, keepdims=kd)]

    if op == "ReduceL2":
        x = get(0)
        at = get(1); axes = _attr(node, "axes", None)
        if axes is None and at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.sqrt(F.sum(x*x, axis=ax, keepdims=kd))]

    # ── Misc ─────────────────────────────────────────────────────────────────
    if op == "Where":
        return [F.where(get(0), get(1), get(2))]

    if op == "DepthToSpace":
        x = get(0)
        bs   = int(_attr(node, "blocksize", 2))
        mode = _attr(node, "mode", b"DCR")
        if isinstance(mode, bytes): mode = mode.decode()
        N, C, H, W = x.shape
        if mode == "DCR":
            x = F.reshape(x, [N, bs, bs, C//(bs*bs), H, W])
            x = F.transpose(x, [0, 3, 4, 1, 5, 2])
        else:  # CRD
            x = F.reshape(x, [N, C//(bs*bs), bs, bs, H, W])
            x = F.transpose(x, [0, 1, 4, 2, 5, 3])
        return [F.reshape(x, [N, C//(bs*bs), H*bs, W*bs])]

    if op == "Resize":
        return _resize(node, get, F)

    if op == "ConstantOfShape":
        shape = _np(get(0)).tolist()
        val_attr = _attr(node, "value", None)
        val = float(val_attr.flat[0]) if val_attr is not None else 0.0
        return [F.full(shape, np.float32(val)) if hasattr(F,'full')
                else np.full(shape, np.float32(val))]

    if op == "Shape":
        x = get(0)
        return [np.array(x.shape, dtype=np.int64)]

    if op == "Reciprocal":
        return [np.float32(1.0) / get(0)]

    if op in ("Equal", "Less", "Greater", "Not", "LessOrEqual", "GreaterOrEqual"):
        a, b = get(0), get(1)
        if op == "Equal":         return [a == b]
        if op == "Less":          return [a < b]
        if op == "Greater":       return [a > b]
        if op == "LessOrEqual":   return [a <= b]
        if op == "GreaterOrEqual":return [a >= b]
        if op == "Not":           return [~get(0)]

    if op == "CumSum":
        x = get(0)
        axis = int(_np(get(1)).flat[0])
        return [F.cumsum(x, axis=axis) if hasattr(F, 'cumsum') else F.cumulative_sum(x, axis=axis)]

    raise NotImplementedError(f"Unsupported ONNX op: {op}")


# ── Framework detection ───────────────────────────────────────────────────────

def _is_jax_module(F) -> bool:
    """Return True if F is jax.numpy (not tf.experimental.numpy)."""
    try:
        import jax.numpy as _jnp
        return F is _jnp
    except ImportError:
        return False


# ── Conv helper ──────────────────────────────────────────────────────────────

def _conv(node, get, F):
    x = get(0); w = get(1); b = get(2)
    pads      = _attr(node, "pads",      [0,0,0,0])
    strides   = _attr(node, "strides",   [1,1])
    dilations = _attr(node, "dilations", [1,1])
    group     = int(_attr(node, "group", 1))

    if _is_jax_module(F):
        import jax.lax as lax
        dn = lax.conv_dimension_numbers(x.shape, w.shape, ("NCHW","OIHW","NCHW"))
        padding = ((int(pads[0]), int(pads[2])), (int(pads[1]), int(pads[3])))
        y = lax.conv_general_dilated(
            x, w,
            window_strides=[int(s) for s in strides],
            padding=padding,
            lhs_dilation=(1,1),
            rhs_dilation=[int(d) for d in dilations],
            dimension_numbers=dn,
            feature_group_count=group,
        )
    else:
        import tensorflow as tf
        # TF conv: NHWC format
        x_nhwc = tf.transpose(x, [0,2,3,1])
        w_hwio = tf.transpose(w, [2,3,1,0])  # OIHW → HWIO
        if group == 1:
            y_nhwc = tf.nn.conv2d(
                x_nhwc, w_hwio,
                strides=[1, int(strides[0]), int(strides[1]), 1],
                padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
                dilations=[int(dilations[0]), int(dilations[1])],
            )
        else:
            # depthwise conv: w is [C,1,kH,kW] → need [kH,kW,C,1] for tf
            w_dwconv = tf.transpose(w, [2,3,0,1])  # [kH,kW,C,1]
            y_nhwc = tf.nn.depthwise_conv2d(
                x_nhwc, w_dwconv,
                strides=[1, int(strides[0]), int(strides[1]), 1],
                padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
                dilations=[int(dilations[0]), int(dilations[1])],
            )
        y = tf.transpose(y_nhwc, [0,3,1,2])

    if b is not None:
        y = y + F.reshape(b, [1,-1,1,1])
    return [y]


# ── ConvTranspose helper ──────────────────────────────────────────────────────

def _conv_transpose(node, get, F):
    x = get(0); w = get(1); b = get(2)
    pads      = _attr(node, "pads",      [0,0,0,0])
    strides   = _attr(node, "strides",   [1,1])
    dilations = _attr(node, "dilations", [1,1])
    op_pads   = _attr(node, "output_padding", [0,0])
    group     = int(_attr(node, "group", 1))

    if _is_jax_module(F):
        import jax.lax as lax
        # ONNX ConvTranspose: w is [C_in, C_out/group, kH, kW].
        # Implement as dilated conv (lhs_dilation = strides) with spatially-flipped
        # and transposed weight → [C_out, C_in, kH, kW] in OIHW format.
        # Padding: for each spatial dim, pad = kernel - 1 - original_pad.
        kH = int(w.shape[2]); kW = int(w.shape[3])
        sH = int(strides[0]); sW = int(strides[1])
        dH = int(dilations[0]); dW = int(dilations[1])
        # Effective kernel size with dilation
        ekH = dH * (kH - 1) + 1; ekW = dW * (kW - 1) + 1
        # Transpose weight: [C_in, C_out, kH, kW] → [C_out, C_in, kH, kW], flip spatially
        w_t = F.transpose(w, (1, 0, 2, 3))[:, :, ::-1, ::-1]
        pad_h_top = ekH - 1 - int(pads[0]); pad_h_bot = ekH - 1 - int(pads[2]) + int(op_pads[0])
        pad_w_left = ekW - 1 - int(pads[1]); pad_w_right = ekW - 1 - int(pads[3]) + int(op_pads[1])
        y = lax.conv_general_dilated(
            x, w_t,
            window_strides=(1, 1),
            padding=((pad_h_top, pad_h_bot), (pad_w_left, pad_w_right)),
            lhs_dilation=(sH, sW),
            rhs_dilation=(dH, dW),
            feature_group_count=group,
            dimension_numbers=('NCHW', 'OIHW', 'NCHW'),
        )
    else:
        import tensorflow as tf
        # For ConvTranspose: w is [C_in, C_out/group, kH, kW] in ONNX
        # TF conv2d_transpose expects [kH, kW, C_out, C_in]
        x_nhwc = tf.transpose(x, [0,2,3,1])
        N, H_in, W_in, C_in = [int(d) for d in x_nhwc.shape]
        C_out = int(w.shape[1]) * group
        kH, kW = int(w.shape[2]), int(w.shape[3])
        sH, sW = int(strides[0]), int(strides[1])
        H_out = (H_in - 1) * sH - int(pads[0]) - int(pads[2]) + kH + int(op_pads[0])
        W_out = (W_in - 1) * sW - int(pads[1]) - int(pads[3]) + kW + int(op_pads[1])
        w_tf = tf.transpose(w, [2,3,1,0])  # [kH,kW,C_out/g,C_in]
        output_shape = [N, H_out, W_out, C_out]
        y_nhwc = tf.nn.conv2d_transpose(
            x_nhwc, w_tf,
            output_shape=output_shape,
            strides=[1, sH, sW, 1],
            padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
        )
        y = tf.transpose(y_nhwc, [0,3,1,2])

    if b is not None:
        y = y + F.reshape(b, [1,-1,1,1])
    return [y]


# ── Pool helper ──────────────────────────────────────────────────────────────

def _pool(node, get, F):
    op = node.op_type
    x = get(0)
    k         = _attr(node, "kernel_shape", [2,2])
    strides   = _attr(node, "strides",      [1,1])
    pads      = _attr(node, "pads",         [0,0,0,0])
    dilations = _attr(node, "dilations",    [1,1])
    ceil_mode = int(_attr(node, "ceil_mode", 0))

    dH, dW = int(dilations[0]), int(dilations[1])

    if _is_jax_module(F):
        import jax.lax as lax
        import jax.numpy as jnp
        pH0, pH1 = int(pads[0]), int(pads[2])
        pW0, pW1 = int(pads[1]), int(pads[3])
        if ceil_mode == 1:
            # Add extra right/bottom padding so lax.reduce_window matches ceil-mode output size
            in_H = int(x.shape[2]); in_W = int(x.shape[3])
            sH = int(strides[0]);   sW = int(strides[1])
            ekH = dH * (int(k[0]) - 1) + 1; ekW = dW * (int(k[1]) - 1) + 1
            rem_h = (in_H + pH0 + pH1 - ekH) % sH
            rem_w = (in_W + pW0 + pW1 - ekW) % sW
            pH1 += (sH - rem_h) if rem_h != 0 else 0
            pW1 += (sW - rem_w) if rem_w != 0 else 0
        pad_h = (pH0, pH1); pad_w = (pW0, pW1)
        padding = ((0,0),(0,0), pad_h, pad_w)
        window = (1, 1, int(k[0]), int(k[1]))
        str_   = (1, 1, int(strides[0]), int(strides[1]))
        win_dil = (1, 1, dH, dW)
        if op == "MaxPool":
            y = lax.reduce_window(x, -jnp.inf, lax.max, window, str_, padding,
                                  window_dilation=win_dil)
        else:
            ones = F.ones_like(x)
            s = lax.reduce_window(x,    0.0, lax.add, window, str_, padding,
                                  window_dilation=win_dil)
            n = lax.reduce_window(ones, 0.0, lax.add, window, str_, padding,
                                  window_dilation=win_dil)
            y = s / n
    else:
        import tensorflow as tf
        x_nhwc = tf.transpose(x, [0,2,3,1])
        ksize   = [1, int(k[0]),       int(k[1]),       1]
        str_tf  = [1, int(strides[0]), int(strides[1]), 1]
        paddings_tf = [[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]]
        if op == "MaxPool" and (dH > 1 or dW > 1):
            # TF max_pool2d has no dilation support; use extract_patches + reduce_max
            kH, kW = int(k[0]), int(k[1])
            pH0, pH1 = int(pads[0]), int(pads[2])
            pW0, pW1 = int(pads[1]), int(pads[3])
            x_pad = tf.pad(x_nhwc, [[0,0],[pH0,pH1],[pW0,pW1],[0,0]],
                           constant_values=-1e9)
            patches = tf.image.extract_patches(
                x_pad,
                sizes=[1, kH, kW, 1],
                strides=str_tf,
                rates=[1, dH, dW, 1],
                padding="VALID",
            )
            N_, H_out, W_out, C_ = [int(d) for d in x_nhwc.shape]
            H_out2 = patches.shape[1]; W_out2 = patches.shape[2]
            C_in = int(x_nhwc.shape[-1])
            patches_r = tf.reshape(patches, [-1, H_out2, W_out2, kH * kW, C_in])
            y_nhwc = tf.reduce_max(patches_r, axis=3)
        elif op == "MaxPool":
            y_nhwc = tf.nn.max_pool2d(x_nhwc, ksize, str_tf, padding=paddings_tf)
        else:
            # avg_pool doesn't support dilations in TF, treat as no dilation
            y_nhwc = tf.nn.avg_pool2d(x_nhwc, ksize, str_tf, padding=paddings_tf)
        y = tf.transpose(y_nhwc, [0,3,1,2])
    return [y]


# ── Resize helper ─────────────────────────────────────────────────────────────

def _resize(node, get, F):
    x = get(0)
    scales_t = get(2); sizes_t = get(3)
    mode = _attr(node, "mode", b"nearest")
    if isinstance(mode, bytes): mode = mode.decode()
    N, C = int(x.shape[0]), int(x.shape[1])
    if scales_t is not None:
        scales = _np(scales_t).tolist()
        H_new = int(int(x.shape[2]) * scales[2])
        W_new = int(int(x.shape[3]) * scales[3])
    else:
        ts = _np(sizes_t).tolist()
        H_new, W_new = int(ts[2]), int(ts[3])

    if _is_jax_module(F):
        import jax.image as ji
        import jax.numpy as jnp
        x_nhwc = jnp.transpose(x, (0,2,3,1))
        method = "nearest" if "nearest" in mode else "linear"
        y_nhwc = ji.resize(x_nhwc, (N, H_new, W_new, C), method=method)
        return [jnp.transpose(y_nhwc, (0,3,1,2))]
    else:
        import tensorflow as tf
        x_nhwc = tf.transpose(x, [0,2,3,1])
        method = tf.image.ResizeMethod.NEAREST_NEIGHBOR if "nearest" in mode \
                 else tf.image.ResizeMethod.BILINEAR
        y_nhwc = tf.image.resize(x_nhwc, [H_new, W_new], method=method)
        return [tf.transpose(y_nhwc, [0,3,1,2])]
# ─────────────────────────────────────────────────────────────────────────────


def _decode():
    model_bytes = base64.b64decode(_ONNX_B64)
    inputs = {n: np.frombuffer(base64.b64decode(b64), dtype=np.float32
                               ).copy().reshape(sh)
              for n, (b64, sh) in _INPUTS.items()}
    return model_bytes, inputs

def _rel_l2(a, b):
    a = np.asarray(a, np.float64).ravel()
    b = np.asarray(b, np.float64).ravel()
    if a.shape != b.shape: return float("inf")
    return float(np.linalg.norm(a - b) / (np.linalg.norm(b) + 1e-8))

def _pytorch_eager(model_bytes, inputs):
    """Reference: onnx2torch eager (no compiler) — same as oracle pytorch_eager."""
    import torch, onnx2torch
    model = onnx.load_from_string(model_bytes)
    m = onnx2torch.convert(model).eval()
    inp = next(iter(inputs.values()))
    x = torch.from_numpy(inp)
    with torch.no_grad():
        out = m(x)
    if isinstance(out, (list, tuple)): out = out[0]
    return out.detach().cpu().float().numpy().ravel()


def _jax_run(model, x_np, use_jit):
    import jax, jax.numpy as jnp
    inp_name = model.graph.input[0].name
    out_name = model.graph.output[0].name
    init_np  = {i.name: _nh.to_array(i).copy() for i in model.graph.initializer}

    def fn(x_jax):
        vals = dict(init_np)
        vals[inp_name] = x_jax
        for node in model.graph.node:
            for nm, v in zip(node.output, dispatch_op(node, vals, jnp)):
                if nm: vals[nm] = v
        return jnp.asarray(vals[out_name], dtype=jnp.float32)

    if use_jit:
        return np.array(jax.jit(fn)(jnp.array(x_np)), dtype=np.float32).ravel()
    with jax.disable_jit():
        return np.array(fn(jnp.array(x_np)), dtype=np.float32).ravel()


def main():
    model_bytes, inputs = _decode()
    model  = onnx.load_from_string(model_bytes)
    x_np   = next(iter(inputs.values()))

    # Reference: pytorch eager
    try:
        ref = _pytorch_eager(model_bytes, inputs)
    except Exception as exc:
        print(f"[warn] pytorch_eager reference failed: {exc}")
        ref = None

    # Target: jax.jit
    try:
        target    = _jax_run(model, x_np, use_jit=True)
        noopt_out = _jax_run(model, x_np, use_jit=False)
    except Exception as exc:
        print(f"[crash] xla: {exc}")
        sys.exit(0)

    diff_vs_ref    = _rel_l2(target, ref) if ref is not None else 0.0
    diff_opt_noopt = _rel_l2(target, noopt_out)

    print(f"rel L2(jit vs pytorch_eager) = {diff_vs_ref:.6e}")
    print(f"rel L2(jit vs no-jit)        = {diff_opt_noopt:.6e}")
    print(f"tolerance = {TOLERANCE}")

    if diff_vs_ref > TOLERANCE or diff_opt_noopt > TOLERANCE:
        print("BUG REPRODUCED")
        sys.exit(0)
    print("not reproduced")
    sys.exit(1)

if __name__ == "__main__":
    main()
