#!/usr/bin/env python3
"""
Bug #0055 — xla: jax.jit diverges from pytorch_eager.

Patterns  : [['constant', 'mul_zero_elim'], ['fusion', 'relu_add_relu'], ['broadcast', 'elu_scale'], ['branch', 'where_mask_fill'], ['normalization', 'variance_whitening'], ['branch', 'glu']]
S_diff    : 1.000000   (jit vs pytorch_eager)
Delta_opt : 0.000000   (jit vs no-jit)
Tolerance : 0.001

    python unique_0055.py
Exit 0 = reproduced, 1 = not reproduced.
"""
import base64, sys
import numpy as np
import onnx
from onnx import numpy_helper as _nh

TOLERANCE = 0.001

_ONNX_B64 = (
    "CAg6icsBCisKC21vZGVsX2lucHV0CgxuMF9temVfemVyb3MSCW4wX216ZV9teiIDTXVsCioKCW4w"
    "X216ZV9tegoMbjBfbXplX3NjYWxlEgpuMF9temVfb3V0IgNBZGQKHwoKbjBfbXplX291dBILbjEw"
    "MF9yYXJfcjEiBFJlbHUKKwoLbjEwMF9yYXJfcjEKCm4wX216ZV9vdXQSC24xMDBfcmFyX2FkIgNB"
    "ZGQKIQoLbjEwMF9yYXJfYWQSDG4xMDBfcmFyX291dCIEUmVsdQozCgxuMTAwX3Jhcl9vdXQSDW4y"
    "MDBfZWx1c19lbHUiA0VsdSoPCgVhbHBoYRUAAIA/oAEBCjIKDW4yMDBfZWx1c19lbHUKDW4yMDBf"
    "ZWx1c19vbmUSDW4yMDBfZWx1c19vdXQiA0FkZAoxCg1uMjAwX2VsdXNfb3V0CgpuMzAwX3dtZl96"
    "EgtuMzAwX3dtZl9ndCIHR3JlYXRlcgo/CgtuMzAwX3dtZl9ndAoNbjIwMF9lbHVzX291dAoNbjMw"
    "MF93bWZfZmlsbBILbjMwMF93bWZfd2giBVdoZXJlCi8KC24zMDBfd21mX3doCg1uMjAwX2VsdXNf"
    "b3V0EgxuMzAwX3dtZl9vdXQiA011bApPCgxuMzAwX3dtZl9vdXQSDG40MDBfdndfbWVhbiIKUmVk"
    "dWNlTWVhbioUCgRheGVzQP///////////wGgAQcqDwoIa2VlcGRpbXMYAaABAgovCgxuMzAwX3dt"
    "Zl9vdXQKDG40MDBfdndfbWVhbhIMbjQwMF92d19kaWZmIgNTdWIKLQoMbjQwMF92d19kaWZmCgxu"
    "NDAwX3Z3X2RpZmYSCm40MDBfdndfc3EiA011bApMCgpuNDAwX3Z3X3NxEgtuNDAwX3Z3X3ZhciIK"
    "UmVkdWNlTWVhbioUCgRheGVzQP///////////wGgAQcqDwoIa2VlcGRpbXMYAaABAgosCgtuNDAw"
    "X3Z3X3ZhcgoLbjQwMF92d19lcHMSC240MDBfdndfYWRkIgNBZGQKLQoLbjQwMF92d19hZGQKDG40"
    "MDBfdndfaGFsZhILbjQwMF92d19zdGQiA1BvdwotCgxuNDAwX3Z3X2RpZmYKC240MDBfdndfc3Rk"
    "EgtuNDAwX3Z3X2RpdiIDRGl2CisKC240MDBfdndfZGl2CgpuNDAwX3Z3X3NjEgtuNDAwX3Z3X291"
    "dCIDTXVsCk8KC240MDBfdndfb3V0CgtuNTAwX2dsdV9zcBIKbjUwMF9nbHVfYRIKbjUwMF9nbHVf"
    "YiIFU3BsaXQqFAoEYXhpcxj///////////8BoAECCiMKCm41MDBfZ2x1X2ISDG41MDBfZ2x1X3Np"
    "ZyIHU2lnbW9pZAotCgpuNTAwX2dsdV9hCgxuNTAwX2dsdV9zaWcSDG41MDBfZ2x1X291dCIDTXVs"
    "Egt0cmlvbl9ncmFwaCqaQAgBCBAIgAEQAUIMbjBfbXplX3plcm9zSoBAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqmkAIAQgQCIABEAFCDG4wX216ZV9zY2FsZUqAQGZm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
    "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
    "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
    "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/KptACAEIEAiAARABQg1uMjAw"
    "X2VsdXNfb25lSoBAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8qFggB"
    "EAFCCm4zMDBfd21mX3pKBAAAAAAqGQgBEAFCDW4zMDBfd21mX2ZpbGxKBAAAgL8qFwgBEAFCC240"
    "MDBfdndfZXBzSgSsxSc3KhgIARABQgxuNDAwX3Z3X2hhbGZKBAAAAD8qGggBCAEIARABQgpuNDAw"
    "X3Z3X3NjSgQAAIA/KiMIAhAHQgtuNTAwX2dsdV9zcEoQQAAAAAAAAABAAAAAAAAAAFoiCgttb2Rl"
    "bF9pbnB1dBITChEIARINCgIIAQoCCBAKAwiAAWIiCgxuNTAwX2dsdV9vdXQSEgoQCAESDAoCCAEK"
    "AggQCgIIQEIECgAQEQ=="
)
_INPUTS = {
    'model_input': (
    "Fa4dQHrR5j9e0Z8/8hgNP2rHMj9VFIC/IKoavu6ck74a9He/JkgMP85k+z4olJ6/lQt8v38KVL7e"
    "2Ls/3YLmP93T5D1MlY8+FFPnPqI2M7+941C/hCkBQFKJsj9K1QTAXZ4Rv6r4vr5KtJK/GC48Phqu"
    "D78xxCy/OZIRwDteSb2DAaK/kcJ8vzxo3L5qjpG+Oq/4P5E/Sj+46h9AZnNUPoDwSD4yrV++Ckau"
    "P3cN9b8/pSG/lhSTvjYkCUCE6jS/qOC9P8X7Hb+Ja0g/Ir7XvuhJpb7SMl0+tDRAvxJu5T7l8na/"
    "vfCkvyAXMb4xnkY+lgMKv5Fhi7/QFD4/BYwJvs51Xr9Xvtk//KhhPpTzV7+y5tU/DRQDP9tSgb9S"
    "ayk/hZvbvhjknr8ci6w/pXG6vsUMsL8lXFk+HIq2v7umAr/+8Uu/DATaPtGgkz/e3To+UbxNvubD"
    "Sz5d7mQ9h5Spv+ARIr7PsuM//giZvmy7xD+hepi/ahWDv+0UCT6yhFW/tIJLvx1khT83rRY826xD"
    "vmwAhT2Sq8O/my4bPly3pT9tP3685Xr2v5JR4j4Lh34/qSWNP3/5ND/lpkI/Pe7Gvr1cyr7onug+"
    "y4wQv4Yvdb989YI/lqSyPaPMmL/5jHs/NbOsv9kqsD5ZCIM/AQt7P7dgLz/TzQw/HdEFO/c8o7+X"
    "2oa+5kzUvyDA6j7+PEw/5klBP4bt678bZbq/dkKBPvKdwD8ldZ0/l+8Yv3NT3j9KW4Q/zDHxPRHm"
    "tb+AZai/QzFrv/gMEL/pm1S//K1aPxe9Xz+6mC+/q2k2vp9isT/HqANAVwqePUQUij80kYI/K/q1"
    "vokzkD5K1Ys+ItSwPzLsKUDQgwY/bARXvlys3L90mPq9+ZzsPbmjzr9FexK/B9qNvuj5OD51te++"
    "CWiBPwIGjr8Ps1g/LEM/Pwe3dD3d+ti+p8zhvxu3AEDqTXs+POcMv+VeBcC6Jxe+GR43vvFrCUAA"
    "iw1Atab1P+cOIL88HaC/kEa+vWqKbL2114S/gfC6Plig5r/ZsrU/gEoUP8ZeXbxo5Ya/0PMAP2R5"
    "iz99LwZAW2VuPn6TUj/y0j0/OCoUv52BMz8tvHs/MHqCPzVS6j6zlZG/mVHwPedTAT/u95M/Z67Q"
    "vlOFdj3fWz2+l4gVvxNVTj9ghF89ZW1DPqc9Vz5pgyu/hnh0vUzSjz8ffqI/IWOtP1/i078/e6e+"
    "juWZPxzGXD8yTPw+6aPIv9fIZD/gitu/ine7v7Mj/b4Lyi++6XvvPp3XEz8GY+U/lPr1vmo7eb/L"
    "owZA/743vSXuor+oJLw/q/c8P7SMED6CG7K+/ptYP/X9hz9cuvI/55XoP0n/Hj+sh08/33eIP5wR"
    "2b+m2nY9q5zTvvoTSL8wCda//5vHvm3yt78pRwK/0BseP+mODL8kFzA+Q4yIP/QOSL95+M2+qj40"
    "P4QgnT0Yhl6+2m6nPjsGiD828ny/zPELvhU9CD9VdeA+kBU5Pzwlq7+EP64/9CbfvgwPfD8Yz52/"
    "/iicP5Whxj4NdNe/+b0qv7kDzL/tn/g+Uls8PxYbKj+8FyY/mNuJvvtb97+pVVM/tdoOQM4/Gr7W"
    "hXO/X43fP3DDuz73d8s+6qOtPXkbQb8+wzy/EXNnP9E3g78ZhXK+VzxLPzX61T6RclC8AQdivswb"
    "FT5jLt6/JYzEv9vjjz9syq+/T74NQOlEZb2yvkI/5QC3PyvTlL8kAwI/HqrIP8/Vab/mxpG+7b/9"
    "v013XT++0V6+vcmVPpjMr7+uLTW/3qa/v/3kQr/zZhy/JW4bP95Vxb7BSps/m65JP5gS5r53WFw/"
    "N/QYv/RZsT/Op7M+pIL9P+8pf75uPBy+q7Cpv1tBh754LPS/PFulPwNa5Dw3+6I+2xxAPnkX1r8s"
    "G4k+uCCtP+Wfwb4hGju9kSlhP2c9lbzWGVu+F51jv7Qws70coNO9+rTRvwceYz9xVjO/ANMQPaca"
    "sz8EeNU+0UbVv/MAZj/1ETy/yxNTv9kvhT8wYl+/nbelPnYy5L6+W28/JJ32PrFBdz+vnwE/IHMt"
    "wCP3ID/sxx49cXkkv+AG1j9vRqk/Hau7P+X8r7+c5NA/BTRov2UVrD2mSgA9yqQkv1mOtb+u73K/"
    "h3sVvv+tlj/pBGc/fqmsvzt1tL4R8re8RYUAv0jxC7vFYY+/35yuv5ioNb+2C0W/BB5rv6p5l70I"
    "WiO/sI9Yv2pNqT4tNsO/rzvTP08iKkDgGm5AaAUcPzxHkj2MHRm+pekJvxQtgT5U0Zi+ETGOP1cP"
    "LD+rqqS+9na4v8BonD9hUfE/kuNvPiOL7L47pRs/IvI4vjcgwL5hnY4+0+ORPhIC9r72lpW/cMYU"
    "v3W4vT9MLSi/SM9Fvzw5vD/zijPACy1wv660JkBa7a++wVebP/HdKD9apao/E3LlPjaAj7zPbQG/"
    "l57YPqd/Yj8zqjM/YA3Rviewej9K+eW/haf5Ped+eT8NTiy+BxgXvqh0IsD0GMi/SdqoPxvqUL/4"
    "+bK/fw16P7uXbD+pUQo/egwpv0bXcz8LE+m/A0Pnv8ZEgr/Npv6/YjJZP2dKyL7fktU/3FmOPyzE"
    "pD7lgLy99pfiPmYRRzx5C5o/SOyCvy/4PD+rQrU/amjqPiQx5z+vEVc/5Dl5v1aYJz9xdaM+VsHd"
    "P12jur+FRm6/quXrPRq1Ur8oApO/EVDJPdbsc76iv6i+jvYjP0U5tb+RLwo++COgPvzg1j9Jvsm9"
    "x/CevhGO378wqFY+gtBPP1GO+7zRvcq/VpsRPesB1j6p33E/nD8BwMbapD8gNos+8KGdPxuLbr8t"
    "O8C89GR2v3NNyL5Ter2/dp5iPyLnjb6UEdK+a/50P2HEuj47tki/yzGMvlJT+T6nIW4+9OC/PyID"
    "JD8pOPW/OHPHP+cfQr+WlzDAU6+xvld+AsDlEny/B0kKP9o7I0CK/VA/Xx/kP9GB5T8usWM/v9SZ"
    "vhaFyT/oLWM/AXDEvu4RrL7AeLk/h/+mP35atr/IWrW9UFqIv6kAIkDXGidA0d7+u2HMoD8IFjC/"
    "E8ajv6708r4BAGy/v6SZP1Rdpj1/QvK9O07pvSj6lb4Pcpu/ULYAP2cEFL8rAbS+HC7VvmPYjD9l"
    "qTW/UOLRvZ0lT78qxZY9HWKsvwazQj+gkC+/l/MlP1VlPj+JtPK+L2MRP048Rz8xkSnAeOeVPtXK"
    "Cb+k7TW/Z4A0Pz1H0b4V5VS+wMAJP6y+ij8r796/iQODvyD+bD9Acdc92asYv7Flyz3Imrk/ddWY"
    "P1sQqL8/C7w/Q2PDvwWTtD7ySeC+so7GPo213z8CVUG+MJdAP/wSr78tnZ+9Y9UFv5QVeb4Buse/"
    "xSgdP6UECz9wkPS/a6wdwPWqNMAGYnG+Y/U/Pzsidb66zbU/DDgHv78G4j6kx/q/SAzwP+5DIr4N"
    "gQK6QuiXP72Ypj4tAOo/e0AVv7EISD+NLfc8vla9v2NxZ70FyZQ+q9+uv7Ackj/seOK/2koUP0UO"
    "Mb/GcAg/oG3cOy3iIj7p2Qs/wRiiP9974z+ePKY/KJixvr1Icb8F/48+jlZjPtdaDD1c0l+/luEB"
    "Phxtm7+pStA+8pSVvje7yjoGRNS/lK4fPRX2vL4s8dw+b4kRvszaFcDnNUw/Ch2mv1F5l78vep4+"
    "d+6wP71fpD97aAC/YxstP1ZdAL8K4/a/WGZSvlvAlL+ZfgK/eW3QPt5LBD/kqEs+t/2PP+4Nc7/W"
    "IbQ+4sy4PxTTjb87rGw/847xP2uutL/bJaK84quLv4gmvL+we0W+TA3mP1rxuLzS/rc/kiD4Pigw"
    "Pr7arZi9eQgGwB8Dnb8XYo8/mBwvv+jtnL4hgKo++SsawI0AWb8X+6+/3dVfvdPjhL9kjS+/Z9U7"
    "PeTPSL+mgHQ/3pAOP6pcyT+ftpq/jm+Rv9iySr4XBjM/nuaJP8aAB0DFbCDA0T+pPzP2jb4i9Mm/"
    "P3AZv+/6gj6SqK0/gKmnP1kF8r78/to+3gHFPrkNx7+Frru8uAShv+mHrj9FHrM/YERyP/GB1j0c"
    "Ut2+xgEKv55d675pb42/O2DIP5tJ2L+nw7A9vTuMPzLTCr/swHU/GNGyP4K5xb6GmJK+sa0Bvk5Z"
    "1T4syvi/RwaiPo5InL/1vvm/wbo5v0lbSb7Rn4o/ccQhwEFLgD974k6/ZGh0PHqwZD/e92q/JmYG"
    "QIW7BT8/LFO/UmeBPvMA+D08LG6/QghQvxx1pr65vgq/8VQUvSbjiD6lUXY/YTcKv/vDAj+Yf6w/"
    "q96IPju9qz/eLDc/NOzjv5HLjz6SvBe/IKtHvxB8nz8ANZM/pz9svoCBjT5qtYi+WVZdv5Xruj+D"
    "WEg/8FQJPu0YoD+in3G/E9wdPvvdG0BwIhK/odtgP6/TtL4yRbU/+xp0PzJ+Ej6KaWa/s3ThPuoq"
    "I75BF4U+Ty9fvz3qDj+QjZ0/EdEHP96l872Luv6/ACUuP9lf7L5+cWA+nrA4vpQJNL4vGdC+04kE"
    "Pl7PFD/wEGQ/PMviPrYP7z80bJg+TsyGPhH6ub/km/E//3JQPhOuyj7uZm+9FvrsvrrgVD9xxDe/"
    "YNOXvvAKQb8/PyK+KcKYPg9zPD/v31e9+aNVv9/Ltb+RvPQ+XGLEvVsmsb9IJU8/i8RevsivF0A8"
    "pNU/UPXVvpBobL+I3dS+HSGeP7JnlD5y+AA/k+8bP5J7ST/sXdU/8H8QQGEXKT/dcS2/YHW1v2Tk"
    "yr5zY0W+mfgDwMA/sT5hBTS/EIOivwC8kL7IbU4+OhivPmuNpLp1Nn09gawmv5FrLL9IcAo+IRv0"
    "vy8COj6Flwm+02KWP7haIT/QJWQ/CiPdvxWaID+0310+Dri3PaS3tb/g2hK/Gya3P7M9I74HGqk/"
    "N1+OPyI1v76/uP0+9SEPv8Jjbb+438i+GcX5vpLzpr5Uiuq+kP04P1wi2T+LSBVAWTukv65MBb8q"
    "9WU/EaITP0W/Tj5S2PI/xGOgvkA1KL0NRk8/CSq7P/lkc78joE8/0jFaPjoI4L6P36E9n9fNPe2w"
    "kz69MV++dyhjv/sBnr91ch2/NSP/P04uoz5RqNS/Av8Vv8dMjr4bGWI+kcjOvMSNUD9FTZs+V7bk"
    "PsvUqT83C/4+M+rUP39tWz/stdc/xzP6vrJrgT9VKCnABnLYvgMKSz+rMqY/AUSYPht6hT8+kqG/"
    "oEV7PkeQGkDH7fy/re03vtGArT8x5Xq+v7AgPjMvVD9n8Ia8+TtuPxdYAUBGy8s/LPoMv3gcrb7Z"
    "Siu/1fWSPw2wrL+r7lU/NhqavjVV1ryfCg8/VfyQvr2Tor8e4La+ZwLEvwm5Y7/gCsm+GjiYP4Kk"
    "B79YDBE/r62Yv2yZoz+X83I/sf8rvmF+ID8B/48+1R4UwHGmnb/gOmq+VLlNP9V/5L9T1MC/kYNd"
    "vV1Jgr6vwmQ+Dachvwvzsj/22/i8nM6VPjC4eD4CRZm/Xfn9P6HVKj/FB6s/GoTEv/mhK7/e+VO/"
    "A2+YvzpzXr4+UAw/+8nmv5Oao70RFIM/NM2kvqZfYD+RFZW+RYHBvj+0KsClNnY+iRClP+HPgz9I"
    "r949k7uKvzmf27119Ou/aOGhvSMEhb+bf6+/48h4P9Yt5r8s8t6/DGzJP1HUnz6iyMC/xg92vwfy"
    "zL/RvCG/o5tSv3UvKL++590+ILsdPrFHML9lz5i/IGUBP96cNkB7XmO/ZcAqP2p+hL9R1dU+N4cM"
    "v7+Gzz6zhYW/qCW8v/1ZWL/F5s0/Y/H7P1267T+021c+osQMvtl9S7+i7o+/c1JcP/eB4T+iix1A"
    "F6tcv9D+l78P/Xg9kAssQLajRT4fttQ9MvnKvXI0J0DRcq8/Abc+wHlnsr/krCm/WX4GP1t5BL+i"
    "VNc/FRxYPyVF17/Xd52/rV/cv0QDtT+dAoq+nh+ZPlJ+jj46EN06YSmGP96RxD7K+2o/XOHgPmpI"
    "BD87Co4/cKEbQOpufj7IsU0+bsHsvrFI+D5CaLC/z2Qkv2+a4T90ffK+JBMZP21tlL1eHXO/kh4h"
    "wNSKpT/fyCy+lDnTv5tAWD8u4ay/gIlSvjMm1L/oYgs/r907P/2/iz9jKbS+bpOhv0K9fD9zjM4+"
    "AOxJv3Xjij+WPghA11wYPtTnwr7mQwO+gTu/vn6Hxz65iVQ8MCUdP4vCmL7mIQJAuA46PkCzm762"
    "tz4/VF2ov665Er/+qiI/NRYyPoO7OT6lI/K+O392v++0q733F1s/llqzvuMgJL/t4BA/95w7P48c"
    "wb3aSUW/2siZv+fl1j5IArG/xry3OJBQEEDuXFc9o6DTPwiVPb98NY2/HqcnvxPsNb8xtWs+Q+xQ"
    "v3tGIL68J4M+ImodQFSX179he44/ZSlmPjXfDr93z+s+dPENP65E4D6vG0A+7vo/v+WFtj5w4ou/"
    "etCNP5LQtz4hGc+9kBm9v2yVC7782yQ//xw1v4aUUL2DfSO/rwL3v2N2u762sLo9a1/Wvys6ZT8E"
    "Giu+KCKtP05oKr9//Y6/tuR2PoBNFr8od44/1pOJv4JTDr57B5y/+9kxv2Uel751Y5w/m4+3Pw4d"
    "Zb6l46s/DAqFP9iCBT6G6Cq/dW3/vtvmIT6ZnHi+JZbIvtyk5D4ZU3S/9YSxvyjEzL9lO9w/cw4f"
    "QIf1U78n+hM/HksDPpjhSr5THCbABodLv3RVkL8wZds/lTz8PfFnZL/PYLY/Mjg9P6SpID81W029"
    "ZpcJP4ICLD8JKZg8rmyhv/jGnL7z2Jq/yEdiP2Xz/L5+SES/O9LOPbyS47/i64++qK0Lv3+QaD+U"
    "gPo+m8Dcv6JBk78A5Ey8lxlJQEUDXz91/8Y/vNCDP8+7hT74vBRAlSX0vx9/fL+7LXk//IpnvwSY"
    "Cj5RbrC+L/s1vtlpDL2/i1q/3TLyvsXYNL/W1B1Ay+JYvxfXBD6yCca7gSCXv6/Ro704wje+GNl/"
    "v2/xmz+3I2S/I4e8P4ETwL/DTr6/tIW8vpvaTL4l4AlABiSZv3VaPT6qTK8/iOSXP1i7wL9rLqa/"
    "UsOPvmzeK7q5UFY9R/8KQPtn/T4UP3y9kJ7Av+i9IkB0yNI901pvvwsnvL5O/KW/e3WAPi7tVL7X"
    "sLK/8tpMP1+jVr8l8pW+MdK2PihVEMBmTdu+gl06v93GEb9Np2e+rmhPPzjbtb6vQI8+OfpMvqsP"
    "w7+epqm+uisLv0wvgz+pVbK+GmHJPyuS+D6XA1M/mETkvo+Q574zKWK+dHmMPoAehT7/oOi9gq5r"
    "Pw2tYz2jbIU/NQkVP1TS2z+gXqO/j/y3vxCtjz7ddeI/aOFDv9kCWT2vQSU/dq0pv/nG8b6Fb8E+"
    "VCCbv4BQrj8K7We/PXq4Pswx2b/Adoi/VJU/vI7RLT9eXSW/PCKvvyuvbz/p0Hs/8aJPP2JYTT/i"
    "MKO9Y9yqP8y9Sz73wy6/uNqBPr9DZT7m6Pg+rFDnP+9ryr+jd+M+ELeFv+PHHz8/C6K/WYKZPhF/"
    "u74lmP4+e3v0v9PfYD/dpkw+4LWfv91KJz/eNsm989auPwMu8b5Ngjg+9K+MP0MbWb8UWHW/liEf"
    "vtm7R77FLEy/wo8bPwDA4j6X/oG/WBFxPpI6jT/2uTc+oApNPrc1kT60++Y+FodCP521cL8g8QS+"
    "Gq3Nv3yEgL+K0es+p0Eiv5Doaz7/b6G+SQMUv7erqT9HF7C/Or1bP2niIL8KWkO/w2i+vjOIlz++"
    "SDo/dOuVv8PUTz9ADSM/GaaZP8gh1z7syeU+QtlGv+1lGL9rKta/1HbaPRIUBD9odKk+9/APv10V"
    "+z3Mzg/AC9Y9PY8UAL+iMu+/ircevz3FgD2THkm/F/+vvwK0uT7F0Ri9XD0lPQodiT9pLnE/fhcZ"
    "QHVDEcC+YyI/P3HxP21c+7+jA7s+dL8Bv/iKpT/S9NY+GcY8QKkEQz+H7ik/lcfzPiKZEL+/pjc/"
    "2crWvs16k70nnJC+wFqZvhpL7j4tqrG/aeMYv1wAJ79O3+E/uKUvv50FZj+bLJ6+yXcAwAHDWr+e"
    "yU4+DpePvyWSxz8AtDo+sn+HPxv8Tr1RotE/sD+bP2+soT6MgtQ+D4KGv1mHMb9RG++9YNxJvkze"
    "vD/0W3C/wUmxvyikEL9uiCA+OvW4P5A3PL9oJ3Y/ptEuvw6R7T+BekC+ON00PCiXxj5Wqpk/AYLX"
    "v3bAMD0ukBS/i2V8PyF24j+DgEw+AUr0v3WHir+FdxE+VEL6v+qrLT5EqWM/NPLyvxu/aT9tMeG/"
    "rpzAP3L9vT8mM4Y/2H+gvqTkLr8u2Gm97pcWv433ML5iAQDATB6XPmDPiT5zIN6/+ao7v6PgKj8F"
    "1bw+Ke70vgDodD/BZxHAHq2+vttJbz6Z/I47t4LBvXp9lj8GJYq+itYYPyrlsL4pIs4/ZUCcPxcc"
    "2D7OTCI/VxqNvu5LjD8vGW++n44Jvj0Qhb9obmW/kN23v3xpxz4rlS1A9Ggwvyx9GL6YFCI/7PKl"
    "PPuia79WG8G/hLMHv1sDDD8Gp1++auXRvo5oLj8r7bY+qeCrvs2Fzz9jFoi/zmikvsNhYb5sY/I/"
    "bXgLPw2ng7/uV5E+D1Fgv36ZIr5uU4q/w5axP710nz8CeHQ/t29Ov0KRyr5/Zse/duEVPrnb5T6s"
    "goC/3Ciov7a1hT4OyPs+oSmZPrRoi79o3o6+x4KKP2Q7uj6pvk4+Ps1xvsIm8r7EwRm988BSP5ww"
    "ij/ULDw/GOSWP+Chwb/y4sw+yS1BPy99qz54ztk/LFv0PtME579fzYS/N6tdPw4BAD78vn+/zs0Z"
    "v/LWFUBuU3Y/FV6SP8y/DkDQDju+v/Orvn5iGL9YMLI+YLo3v01Jqz9v0oq/cd8MvzmkG78A8Qg/"
    "gf7Ovha0lj+wQ5i+ZJvdvgTEMj/5jBa+03goP/MivL6Jmxq+IwMjv99yUz8NXeU/7m2ov5dJm76P"
    "LCi+VjYNQOudRz/iMxC/V/VjP3tuJj5AXP4+4sJlv6SWzD/qbWO+37l3PyhSTb8cl4w/yJGSPuu+"
    "rb2hGY88qOusP785HT4nI3M/DrVtv/ffDD8ZGPw/ONZdP6ecB76gn+u+FHI/P2H2cz49HGU/SfU9"
    "vYE9Wz+2MMK+5+/yPliQiL+pghXAcg/RPyc+BL9Vapo/lB/RvmHKZz8bvxu/n9wkPgzsnj+gTXu9"
    "tndtPr0Shz8ncYY/4B5HP6ZPAD+FoQpAQ47kP9G1IT9heBg/OlBxv+xda79buq4+aRbXvoQukj8l"
    "tZK/d7oXv0FsjL+1Rha/4ASgPrxtyj3T3Dw+bRUZP1S9tb8R0ZW/yAB1vzPUvr9qYaa9SLAPP6Lo"
    "tD/b98Q+K2ouP/jOSr/jqRE/MJr/Pgdgir8P9oE+uvKHv/5n8r7Ohlw+cX6+v/cLV76NUDO/H7bt"
    "PlPM0T6gYPS88WPZveMFbL9B46Q/JLebP1KQIL/pW569uaK4PnF/+j3TfRs/UuTkvD8mgL6n1Me/"
    "92iCv+JbZD+2604/mY6yPyMOjL9YMEW/mz/dvVhzWL90hgC+oDShvvZQHz+52Yq/hNMGwPnDG74c"
    "DoO/kinsPSN7C75gWKY/1QgHv5/21D4L6U4/hcFMv16cnT+yB+U+vO3HP4bypj+B/Sy9t/5Tvw1J"
    "YD33Lks/t4rMv3RPML9K/du9D5mtPl+Dyj5UEFg/PN3XPzwWmz6q2Qe/l7c9v1nmNr9P8Xu/5KfS"
    "PwXnhz9mWsO+3R3av0hR1D0JZO4/hDSkPzHl5b9rJCq/U9K8P4tPQL4v/jS/ora5v/wjIsDABZi+"
    "5POnPzRmyz/VZSq+va/Lv6IhiD9K80O+wjWxv0eFUr2qzdc/4zCBv6MjTb9GC5k/1VQMv5hkzz5t"
    "XGu/vlQVv18nUj0I9Kg+KLAlP9akqb+YCqa/E+eQvtiu4z6Df0Y/hw/hvyT6FcBoE4E/is+mvr90"
    "d722TXQ+VW2/P3AN+b0I4YC/pqynva91yr7uNNe8JVVhvXFaiz+nbOA+bPI3v1zuYT25gdY/GD1h"
    "Pzainr+PuEA+TtQcPRqtwb8kcY6+Lyy1P40LBL7ZCEm/gr+LPwXmAL/tdrI+sAriPivibj/QogVA"
    "iSMDP/WSjj4j6zU/d2H7PoDRBr6UbXa9Yvi7viu+dT8Pble9x4mRvqR8bz+6N8S9Jz5ovnEC8z+X"
    "OEY/P17mP6/7Er7aVVy/veGIv5qRpj87NNQ9Ulh6vUjMs75/yaI/XYUtPhUMA77kU7O/kyOjv55g"
    "Nr7bP8o9RchUwKPPcT/0URq/SuMUwCPn6bzcb/G/g+aaOqkB+r4fzhE/OxwEwLbJ7b/84C49MM1a"
    "v46i1b5GV6c/1bpIvhgrab9GoUg+ix/rPmqzsr8PfWM+nun1Ps9Kdz99xBZAKiq1P46caj99l/K+"
    "eEuAvtdMyr/rgB+/25mavfeN0L0CQxq/X0LuPzeU7L1UpgA/EapjP2I+tT8FRKy+ROwIvwK5uDu3"
    "0nY+BVdUP3DgVT/nbQfAtM8HP3+DtD4ELfA9InJ2PuGHQD+llLe/QQ7dv04rg7+Zi/c+nLafPuRh"
    "Nb5Rfey+zZXpPgOGPr9B3ZG/Kh08v2/EEMBtPKU/I6TXPq8pbz+o3U+/2pMKP5aWF0AaCsM/+B6W"
    "Pv2earzR+Wi/cfHiP9Ly/T79D6M+nlEBvw0GvL+Wo6+/JS0vPfP8hb5vtwBAd31KP1P5ij8hnWW/"
    "rrAFv4+6Gj7x8Xm+4oCWvijLwb9DBdU/ZcKHP42DhT4JTys+rjaQvSzYAcBJxo+/E1aavv6SnL0S"
    "0oq9n/VdPx0T6j5Ydic+lEZ/vveWsb87X44/1cNuP88Ikb5Jhfo/1d4Sv+PFIr2N/Cg/Hs2GPnfD"
    "Az6ROQW/BgVHP2emCz9wfxy/QraGP9ftP71CcBE/4CMTQCcPqL8hBci+GnJovksXc76UVEe+dfKg"
    "P4o3nr4GgYm/Dp6qP0a73Ltc1/2+0DvBP3leOL/4Mqc//VcNPgOrJr8=",
        [1, 16, 128],
    ),
}

# ── Inlined ONNX op dispatcher (no project imports needed) ────────────────────
"""
Shared ONNX op dispatcher for JAX, TensorFlow, and other array-API backends.

dispatch_op(node, values, np_like) executes one ONNX node using the provided
numpy-compatible module (jax.numpy, tensorflow, numpy, etc.).

Rules:
  - Initializers are stored as plain numpy arrays in `values`.
    Shape-extracting ops (Reshape, Slice, etc.) call np.array() on them safely.
  - Intermediate computed tensors are framework arrays (JAX/TF traced).
    They are NEVER passed to np.array() — only used in framework ops.
  - The dispatcher is framework-agnostic: pass jnp for JAX, tf for TF, etc.
"""
import numpy as np
import onnx
from onnx import TensorProto

_ONNX_DTYPE = {
    TensorProto.FLOAT:  np.float32,
    TensorProto.DOUBLE: np.float64,
    TensorProto.INT32:  np.int32,
    TensorProto.INT64:  np.int64,
    TensorProto.BOOL:   np.bool_,
    TensorProto.UINT8:  np.uint8,
    TensorProto.INT8:   np.int8,
}


def _attr(node, name, default=None):
    for a in node.attribute:
        if a.name == name:
            if a.type == onnx.AttributeProto.FLOAT:  return a.f
            if a.type == onnx.AttributeProto.INT:    return a.i
            if a.type == onnx.AttributeProto.STRING: return a.s
            if a.type == onnx.AttributeProto.FLOATS: return list(a.floats)
            if a.type == onnx.AttributeProto.INTS:   return list(a.ints)
            if a.type == onnx.AttributeProto.TENSOR:
                from onnx import numpy_helper
                return numpy_helper.to_array(a.t)
    return default


def _np(v):
    """Convert a value (numpy or framework tensor) to numpy. Only for initializers."""
    if isinstance(v, np.ndarray):
        return v
    return np.array(v)


def dispatch_op(node, values: dict, F) -> list:
    """
    Execute one ONNX node.
    F  = framework module (jax.numpy, tf, numpy, …)
    values = name → tensor (numpy for initializers, framework array for computed)
    Returns list of output tensors.
    """
    op = node.op_type

    def get(i):
        if i >= len(node.input) or not node.input[i]:
            return None
        return values.get(node.input[i])

    # ── Element-wise arithmetic ──────────────────────────────────────────────
    if op == "Add":       return [F.add(get(0), get(1)) if hasattr(F,'add') else get(0)+get(1)]
    if op == "Sub":       return [get(0) - get(1)]
    if op == "Mul":       return [get(0) * get(1)]
    if op == "Div":       return [get(0) / get(1)]
    if op == "Neg":       return [-get(0)]
    if op == "Abs":       return [F.abs(get(0))]
    if op == "Sqrt":      return [F.sqrt(get(0))]
    if op == "Exp":       return [F.exp(get(0))]
    if op == "Log":       return [F.log(get(0))]
    if op == "Tanh":      return [F.tanh(get(0))]
    if op == "Reciprocal": return [1.0 / get(0)]

    if op == "Pow":
        return [get(0) ** _np(get(1)).flat[0] if isinstance(get(1), np.ndarray)
                else get(0) ** get(1)]

    if op == "Erf":
        if _is_jax_module(F):
            import jax.scipy.special as jss
            return [jss.erf(get(0))]
        else:
            import tensorflow as tf
            return [tf.math.erf(get(0))]

    if op == "Sin":   return [F.sin(get(0))]
    if op == "Cos":   return [F.cos(get(0))]
    if op == "Floor": return [F.floor(get(0))]
    if op == "Ceil":  return [F.ceil(get(0))]
    if op == "Round": return [F.round(get(0))]
    if op == "Sign":  return [F.sign(get(0))]

    # Element-wise Max/Min (binary)
    if op == "Max":
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        result = tensors[0]
        for t in tensors[1:]:
            result = F.maximum(result, t)
        return [result]
    if op == "Min":
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        result = tensors[0]
        for t in tensors[1:]:
            result = F.minimum(result, t)
        return [result]

    # ── Activations ──────────────────────────────────────────────────────────
    if op == "Relu":
        return [F.maximum(get(0), F.zeros_like(get(0))) if hasattr(F, 'zeros_like')
                else F.maximum(get(0), 0.0)]

    if op == "LeakyRelu":
        alpha = _attr(node, "alpha", 0.01)
        x = get(0)
        zero = np.float32(0.0)
        return [F.where(x >= zero, x, np.float32(alpha) * x)]

    if op == "Elu":
        alpha = float(_attr(node, "alpha", 1.0))
        x = get(0)
        return [F.where(x >= np.float32(0.0), x, np.float32(alpha) * (F.exp(x) - np.float32(1.0)))]

    if op == "Selu":
        alpha = float(_attr(node, "alpha", 1.6732632423543772))
        gamma = float(_attr(node, "gamma", 1.0507009873554805))
        x = get(0)
        return [np.float32(gamma) * F.where(x >= np.float32(0.0), x,
                np.float32(alpha) * (F.exp(x) - np.float32(1.0)))]

    if op == "HardSigmoid":
        alpha = float(_attr(node, "alpha", 0.2))
        beta  = float(_attr(node, "beta",  0.5))
        x = get(0)
        return [F.clip(np.float32(alpha) * x + np.float32(beta), np.float32(0.0), np.float32(1.0))]

    if op == "HardSwish":
        x = get(0)
        return [x * F.clip(x / np.float32(6.0) + np.float32(0.5), np.float32(0.0), np.float32(1.0))]

    if op == "Mish":
        x = get(0)
        return [x * F.tanh(F.log(np.float32(1.0) + F.exp(x)))]

    if op == "Sigmoid":
        x = get(0)
        return [np.float32(1.0) / (np.float32(1.0) + F.exp(-x))]

    if op == "Softmax":
        axis = int(_attr(node, "axis", -1))
        x = get(0)
        x_max = F.max(x, axis=axis, keepdims=True)
        e = F.exp(x - x_max)
        return [e / F.sum(e, axis=axis, keepdims=True)]

    if op == "Softplus":
        return [F.log(np.float32(1.0) + F.exp(get(0)))]

    if op == "Clip":
        x = get(0)
        mn = get(1); mx = get(2)
        if mn is not None:
            x = F.maximum(x, F.asarray(mn, dtype=x.dtype) if hasattr(F,'asarray') else mn)
        if mx is not None:
            x = F.minimum(x, F.asarray(mx, dtype=x.dtype) if hasattr(F,'asarray') else mx)
        return [x]

    if op in ("Identity", "Dropout"):
        return [get(0)]

    if op == "Cast":
        to   = _attr(node, "to", TensorProto.FLOAT)
        dtype = _ONNX_DTYPE.get(int(to), np.float32)
        return [get(0).astype(dtype)]

    # ── Shape ops ────────────────────────────────────────────────────────────
    if op == "Transpose":
        perm = _attr(node, "perm", None)
        x = get(0)
        if perm is None:
            perm = list(range(len(x.shape)))[::-1]
        return [F.transpose(x, perm)]

    if op == "Reshape":
        x = get(0)
        shape_raw = _np(get(1)).tolist()          # always an initializer → numpy safe
        orig = x.shape
        shape = [int(orig[i]) if shape_raw[i] == 0 else int(shape_raw[i])
                 for i in range(len(shape_raw))]
        return [F.reshape(x, shape)]

    if op == "Flatten":
        axis = int(_attr(node, "axis", 1))
        x = get(0)
        left  = int(np.prod(x.shape[:axis]))
        right = int(np.prod(x.shape[axis:]))
        return [F.reshape(x, [left, right])]

    if op == "Unsqueeze":
        x = get(0)
        axes = _attr(node, "axes", None)
        if axes is None:
            axes = _np(get(1)).tolist()
        for ax in sorted([int(a) for a in axes]):
            x = F.expand_dims(x, axis=ax)
        return [x]

    if op == "Squeeze":
        x = get(0)
        axes_t = get(1)
        axes = _attr(node, "axes", None)
        if axes is None and axes_t is not None:
            axes = _np(axes_t).tolist()
        if axes:
            for ax in sorted([int(a) for a in axes], reverse=True):
                x = F.squeeze(x, axis=ax)
        else:
            x = F.squeeze(x)
        return [x]

    if op == "Expand":
        x = get(0)
        shape = _np(get(1)).tolist()
        return [F.broadcast_to(x, shape)]

    if op == "Gather":
        x   = get(0)
        idx = _np(get(1))          # indices always come from initializers
        axis = int(_attr(node, "axis", 0))
        if _is_jax_module(F):
            return [F.take(x, idx.astype(np.int32), axis=axis)]
        else:
            import tensorflow as tf
            return [tf.gather(x, idx.astype(np.int32), axis=axis)]

    if op == "Concat":
        axis = int(_attr(node, "axis", 0))
        tensors = [get(i) for i in range(len(node.input)) if node.input[i]]
        return [F.concatenate(tensors, axis=axis)]

    if op == "Split":
        x = get(0)
        axis = int(_attr(node, "axis", 0))
        split_t = get(1)
        sizes = _attr(node, "split", None)
        if sizes is None and split_t is not None:
            sizes = _np(split_t).tolist()
        if sizes is None:
            n = len([o for o in node.output if o])
            sizes = [x.shape[axis] // n] * n
        sizes_int = [int(s) for s in sizes]
        indices = np.cumsum(sizes_int[:-1]).tolist()
        # jax.numpy.split uses indices; tf.split uses sizes
        if _is_jax_module(F):
            parts = F.split(x, [int(i) for i in indices], axis=axis)
        else:
            import tensorflow as tf
            parts = tf.split(x, sizes_int, axis=axis)
        return list(parts)

    if op == "Slice":
        x = get(0)
        starts  = _np(get(1)).tolist()
        ends    = _np(get(2)).tolist()
        axes_t  = get(3); steps_t = get(4)
        axes  = _np(axes_t).tolist() if axes_t is not None else list(range(len(starts)))
        steps = _np(steps_t).tolist() if steps_t is not None else [1]*len(starts)
        slices = [slice(None)] * len(x.shape)
        for ax, s, e, st in zip(axes, starts, ends, steps):
            ax = int(ax) % len(x.shape)
            slices[ax] = slice(int(s), int(e) if abs(int(e)) < 2**30 else None, int(st))
        return [x[tuple(slices)]]

    if op == "Pad":
        x = get(0)
        pads_t = get(1)
        pads = _attr(node, "pads", None)
        if pads is None:
            pads = _np(pads_t).tolist()
        mode = _attr(node, "mode", b"constant")
        if isinstance(mode, bytes): mode = mode.decode()
        n = len(x.shape)
        pad_width = [(int(pads[i]), int(pads[i+n])) for i in range(n)]
        if _is_jax_module(F):
            import jax.numpy as jnp
            return [jnp.pad(x, pad_width, mode=mode if mode != "constant" else "constant")]
        else:
            import tensorflow as tf
            paddings = tf.constant(pad_width, dtype=tf.int32)
            return [tf.pad(x, paddings)]

    if op == "Tile":
        x = get(0)
        reps = _np(get(1)).tolist()
        return [F.tile(x, [int(r) for r in reps])]

    # ── Linear algebra ───────────────────────────────────────────────────────
    if op == "MatMul":
        return [F.matmul(get(0), get(1))]

    if op == "Gemm":
        A = get(0); B = get(1); C = get(2)
        alpha = float(_attr(node, "alpha", 1.0))
        beta  = float(_attr(node, "beta",  1.0))
        if _attr(node, "transA", 0): A = F.swapaxes(A, -1, -2) if hasattr(F,'swapaxes') else F.transpose(A, list(range(len(A.shape)-2))+[-1,-2])
        if _attr(node, "transB", 0): B = F.swapaxes(B, -1, -2) if hasattr(F,'swapaxes') else F.transpose(B, list(range(len(B.shape)-2))+[-1,-2])
        result = np.float32(alpha) * F.matmul(A, B)
        if C is not None:
            result = result + np.float32(beta) * C
        return [result]

    # ── Convolution ──────────────────────────────────────────────────────────
    if op == "Conv":
        return _conv(node, get, F)

    if op == "ConvTranspose":
        return _conv_transpose(node, get, F)

    # ── Normalization ────────────────────────────────────────────────────────
    if op == "BatchNormalization":
        x = get(0); scale = get(1); B_ = get(2); mean = get(3); var = get(4)
        eps = float(_attr(node, "epsilon", 1e-5))
        nd = len(x.shape) - 2
        bc = [1, -1] + [1]*nd
        x_n = (x - F.reshape(mean, bc)) / F.sqrt(F.reshape(var, bc) + np.float32(eps))
        return [F.reshape(scale, bc) * x_n + F.reshape(B_, bc)]

    if op == "InstanceNormalization":
        x = get(0); scale = get(1); B_ = get(2)
        eps = float(_attr(node, "epsilon", 1e-5))
        axes = tuple(range(2, len(x.shape)))
        nd = len(x.shape) - 2
        bc = [1, -1] + [1]*nd
        mean = F.mean(x, axis=axes, keepdims=True)
        var  = F.mean((x-mean)**2, axis=axes, keepdims=True)
        x_n  = (x - mean) / F.sqrt(var + np.float32(eps))
        return [F.reshape(scale, bc) * x_n + F.reshape(B_, bc)]

    if op == "LayerNormalization":
        x = get(0); scale = get(1); B_ = get(2)
        axis = int(_attr(node, "axis", -1))
        eps  = float(_attr(node, "epsilon", 1e-5))
        ndim = len(x.shape)
        norm_axis = axis % ndim
        axes = tuple(range(norm_axis, ndim))
        mean = F.mean(x, axis=axes, keepdims=True)
        var  = F.mean((x - mean)**2, axis=axes, keepdims=True)
        x_n  = (x - mean) / F.sqrt(var + np.float32(eps))
        if scale is not None: x_n = x_n * scale
        if B_ is not None:    x_n = x_n + B_
        return [x_n]

    # ── Pooling ──────────────────────────────────────────────────────────────
    if op in ("MaxPool", "AveragePool"):
        return _pool(node, get, F)

    if op == "GlobalAveragePool":
        x = get(0)
        axes = tuple(range(2, len(x.shape)))
        return [F.mean(x, axis=axes, keepdims=True)]

    if op == "GlobalMaxPool":
        x = get(0)
        axes = tuple(range(2, len(x.shape)))
        return [F.max(x, axis=axes, keepdims=True)]

    # ── Reductions ───────────────────────────────────────────────────────────
    if op == "ReduceMean":
        x = get(0)
        axes = _attr(node, "axes", None)
        if axes is None:
            at = get(1)
            if at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.mean(x, axis=ax, keepdims=kd)]

    if op == "ReduceSum":
        x = get(0)
        at = get(1); axes = _attr(node, "axes", None)
        if axes is None and at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.sum(x, axis=ax, keepdims=kd)]

    if op == "ReduceMax":
        x = get(0)
        axes = _attr(node, "axes", None)
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.max(x, axis=ax, keepdims=kd)]

    if op == "ReduceL2":
        x = get(0)
        at = get(1); axes = _attr(node, "axes", None)
        if axes is None and at is not None: axes = _np(at).tolist()
        kd = bool(_attr(node, "keepdims", 1))
        ax = tuple(int(a) for a in axes) if axes else None
        return [F.sqrt(F.sum(x*x, axis=ax, keepdims=kd))]

    # ── Misc ─────────────────────────────────────────────────────────────────
    if op == "Where":
        return [F.where(get(0), get(1), get(2))]

    if op == "DepthToSpace":
        x = get(0)
        bs   = int(_attr(node, "blocksize", 2))
        mode = _attr(node, "mode", b"DCR")
        if isinstance(mode, bytes): mode = mode.decode()
        N, C, H, W = x.shape
        if mode == "DCR":
            x = F.reshape(x, [N, bs, bs, C//(bs*bs), H, W])
            x = F.transpose(x, [0, 3, 4, 1, 5, 2])
        else:  # CRD
            x = F.reshape(x, [N, C//(bs*bs), bs, bs, H, W])
            x = F.transpose(x, [0, 1, 4, 2, 5, 3])
        return [F.reshape(x, [N, C//(bs*bs), H*bs, W*bs])]

    if op == "Resize":
        return _resize(node, get, F)

    if op == "ConstantOfShape":
        shape = _np(get(0)).tolist()
        val_attr = _attr(node, "value", None)
        val = float(val_attr.flat[0]) if val_attr is not None else 0.0
        return [F.full(shape, np.float32(val)) if hasattr(F,'full')
                else np.full(shape, np.float32(val))]

    if op == "Shape":
        x = get(0)
        return [np.array(x.shape, dtype=np.int64)]

    if op == "Reciprocal":
        return [np.float32(1.0) / get(0)]

    if op in ("Equal", "Less", "Greater", "Not", "LessOrEqual", "GreaterOrEqual"):
        a, b = get(0), get(1)
        if op == "Equal":         return [a == b]
        if op == "Less":          return [a < b]
        if op == "Greater":       return [a > b]
        if op == "LessOrEqual":   return [a <= b]
        if op == "GreaterOrEqual":return [a >= b]
        if op == "Not":           return [~get(0)]

    if op == "CumSum":
        x = get(0)
        axis = int(_np(get(1)).flat[0])
        return [F.cumsum(x, axis=axis) if hasattr(F, 'cumsum') else F.cumulative_sum(x, axis=axis)]

    raise NotImplementedError(f"Unsupported ONNX op: {op}")


# ── Framework detection ───────────────────────────────────────────────────────

def _is_jax_module(F) -> bool:
    """Return True if F is jax.numpy (not tf.experimental.numpy)."""
    try:
        import jax.numpy as _jnp
        return F is _jnp
    except ImportError:
        return False


# ── Conv helper ──────────────────────────────────────────────────────────────

def _conv(node, get, F):
    x = get(0); w = get(1); b = get(2)
    pads      = _attr(node, "pads",      [0,0,0,0])
    strides   = _attr(node, "strides",   [1,1])
    dilations = _attr(node, "dilations", [1,1])
    group     = int(_attr(node, "group", 1))

    if _is_jax_module(F):
        import jax.lax as lax
        dn = lax.conv_dimension_numbers(x.shape, w.shape, ("NCHW","OIHW","NCHW"))
        padding = ((int(pads[0]), int(pads[2])), (int(pads[1]), int(pads[3])))
        y = lax.conv_general_dilated(
            x, w,
            window_strides=[int(s) for s in strides],
            padding=padding,
            lhs_dilation=(1,1),
            rhs_dilation=[int(d) for d in dilations],
            dimension_numbers=dn,
            feature_group_count=group,
        )
    else:
        import tensorflow as tf
        # TF conv: NHWC format
        x_nhwc = tf.transpose(x, [0,2,3,1])
        w_hwio = tf.transpose(w, [2,3,1,0])  # OIHW → HWIO
        if group == 1:
            y_nhwc = tf.nn.conv2d(
                x_nhwc, w_hwio,
                strides=[1, int(strides[0]), int(strides[1]), 1],
                padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
                dilations=[int(dilations[0]), int(dilations[1])],
            )
        else:
            # depthwise conv: w is [C,1,kH,kW] → need [kH,kW,C,1] for tf
            w_dwconv = tf.transpose(w, [2,3,0,1])  # [kH,kW,C,1]
            y_nhwc = tf.nn.depthwise_conv2d(
                x_nhwc, w_dwconv,
                strides=[1, int(strides[0]), int(strides[1]), 1],
                padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
                dilations=[int(dilations[0]), int(dilations[1])],
            )
        y = tf.transpose(y_nhwc, [0,3,1,2])

    if b is not None:
        y = y + F.reshape(b, [1,-1,1,1])
    return [y]


# ── ConvTranspose helper ──────────────────────────────────────────────────────

def _conv_transpose(node, get, F):
    x = get(0); w = get(1); b = get(2)
    pads      = _attr(node, "pads",      [0,0,0,0])
    strides   = _attr(node, "strides",   [1,1])
    dilations = _attr(node, "dilations", [1,1])
    op_pads   = _attr(node, "output_padding", [0,0])
    group     = int(_attr(node, "group", 1))

    if _is_jax_module(F):
        import jax.lax as lax
        # ONNX ConvTranspose: w is [C_in, C_out/group, kH, kW].
        # Implement as dilated conv (lhs_dilation = strides) with spatially-flipped
        # and transposed weight → [C_out, C_in, kH, kW] in OIHW format.
        # Padding: for each spatial dim, pad = kernel - 1 - original_pad.
        kH = int(w.shape[2]); kW = int(w.shape[3])
        sH = int(strides[0]); sW = int(strides[1])
        dH = int(dilations[0]); dW = int(dilations[1])
        # Effective kernel size with dilation
        ekH = dH * (kH - 1) + 1; ekW = dW * (kW - 1) + 1
        # Transpose weight: [C_in, C_out, kH, kW] → [C_out, C_in, kH, kW], flip spatially
        w_t = F.transpose(w, (1, 0, 2, 3))[:, :, ::-1, ::-1]
        pad_h_top = ekH - 1 - int(pads[0]); pad_h_bot = ekH - 1 - int(pads[2]) + int(op_pads[0])
        pad_w_left = ekW - 1 - int(pads[1]); pad_w_right = ekW - 1 - int(pads[3]) + int(op_pads[1])
        y = lax.conv_general_dilated(
            x, w_t,
            window_strides=(1, 1),
            padding=((pad_h_top, pad_h_bot), (pad_w_left, pad_w_right)),
            lhs_dilation=(sH, sW),
            rhs_dilation=(dH, dW),
            feature_group_count=group,
            dimension_numbers=('NCHW', 'OIHW', 'NCHW'),
        )
    else:
        import tensorflow as tf
        # For ConvTranspose: w is [C_in, C_out/group, kH, kW] in ONNX
        # TF conv2d_transpose expects [kH, kW, C_out, C_in]
        x_nhwc = tf.transpose(x, [0,2,3,1])
        N, H_in, W_in, C_in = [int(d) for d in x_nhwc.shape]
        C_out = int(w.shape[1]) * group
        kH, kW = int(w.shape[2]), int(w.shape[3])
        sH, sW = int(strides[0]), int(strides[1])
        H_out = (H_in - 1) * sH - int(pads[0]) - int(pads[2]) + kH + int(op_pads[0])
        W_out = (W_in - 1) * sW - int(pads[1]) - int(pads[3]) + kW + int(op_pads[1])
        w_tf = tf.transpose(w, [2,3,1,0])  # [kH,kW,C_out/g,C_in]
        output_shape = [N, H_out, W_out, C_out]
        y_nhwc = tf.nn.conv2d_transpose(
            x_nhwc, w_tf,
            output_shape=output_shape,
            strides=[1, sH, sW, 1],
            padding=[[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]],
        )
        y = tf.transpose(y_nhwc, [0,3,1,2])

    if b is not None:
        y = y + F.reshape(b, [1,-1,1,1])
    return [y]


# ── Pool helper ──────────────────────────────────────────────────────────────

def _pool(node, get, F):
    op = node.op_type
    x = get(0)
    k         = _attr(node, "kernel_shape", [2,2])
    strides   = _attr(node, "strides",      [1,1])
    pads      = _attr(node, "pads",         [0,0,0,0])
    dilations = _attr(node, "dilations",    [1,1])
    ceil_mode = int(_attr(node, "ceil_mode", 0))

    dH, dW = int(dilations[0]), int(dilations[1])

    if _is_jax_module(F):
        import jax.lax as lax
        import jax.numpy as jnp
        pH0, pH1 = int(pads[0]), int(pads[2])
        pW0, pW1 = int(pads[1]), int(pads[3])
        if ceil_mode == 1:
            # Add extra right/bottom padding so lax.reduce_window matches ceil-mode output size
            in_H = int(x.shape[2]); in_W = int(x.shape[3])
            sH = int(strides[0]);   sW = int(strides[1])
            ekH = dH * (int(k[0]) - 1) + 1; ekW = dW * (int(k[1]) - 1) + 1
            rem_h = (in_H + pH0 + pH1 - ekH) % sH
            rem_w = (in_W + pW0 + pW1 - ekW) % sW
            pH1 += (sH - rem_h) if rem_h != 0 else 0
            pW1 += (sW - rem_w) if rem_w != 0 else 0
        pad_h = (pH0, pH1); pad_w = (pW0, pW1)
        padding = ((0,0),(0,0), pad_h, pad_w)
        window = (1, 1, int(k[0]), int(k[1]))
        str_   = (1, 1, int(strides[0]), int(strides[1]))
        win_dil = (1, 1, dH, dW)
        if op == "MaxPool":
            y = lax.reduce_window(x, -jnp.inf, lax.max, window, str_, padding,
                                  window_dilation=win_dil)
        else:
            ones = F.ones_like(x)
            s = lax.reduce_window(x,    0.0, lax.add, window, str_, padding,
                                  window_dilation=win_dil)
            n = lax.reduce_window(ones, 0.0, lax.add, window, str_, padding,
                                  window_dilation=win_dil)
            y = s / n
    else:
        import tensorflow as tf
        x_nhwc = tf.transpose(x, [0,2,3,1])
        ksize   = [1, int(k[0]),       int(k[1]),       1]
        str_tf  = [1, int(strides[0]), int(strides[1]), 1]
        paddings_tf = [[0,0],[int(pads[0]),int(pads[2])],[int(pads[1]),int(pads[3])],[0,0]]
        if op == "MaxPool" and (dH > 1 or dW > 1):
            # TF max_pool2d has no dilation support; use extract_patches + reduce_max
            kH, kW = int(k[0]), int(k[1])
            pH0, pH1 = int(pads[0]), int(pads[2])
            pW0, pW1 = int(pads[1]), int(pads[3])
            x_pad = tf.pad(x_nhwc, [[0,0],[pH0,pH1],[pW0,pW1],[0,0]],
                           constant_values=-1e9)
            patches = tf.image.extract_patches(
                x_pad,
                sizes=[1, kH, kW, 1],
                strides=str_tf,
                rates=[1, dH, dW, 1],
                padding="VALID",
            )
            N_, H_out, W_out, C_ = [int(d) for d in x_nhwc.shape]
            H_out2 = patches.shape[1]; W_out2 = patches.shape[2]
            C_in = int(x_nhwc.shape[-1])
            patches_r = tf.reshape(patches, [-1, H_out2, W_out2, kH * kW, C_in])
            y_nhwc = tf.reduce_max(patches_r, axis=3)
        elif op == "MaxPool":
            y_nhwc = tf.nn.max_pool2d(x_nhwc, ksize, str_tf, padding=paddings_tf)
        else:
            # avg_pool doesn't support dilations in TF, treat as no dilation
            y_nhwc = tf.nn.avg_pool2d(x_nhwc, ksize, str_tf, padding=paddings_tf)
        y = tf.transpose(y_nhwc, [0,3,1,2])
    return [y]


# ── Resize helper ─────────────────────────────────────────────────────────────

def _resize(node, get, F):
    x = get(0)
    scales_t = get(2); sizes_t = get(3)
    mode = _attr(node, "mode", b"nearest")
    if isinstance(mode, bytes): mode = mode.decode()
    N, C = int(x.shape[0]), int(x.shape[1])
    if scales_t is not None:
        scales = _np(scales_t).tolist()
        H_new = int(int(x.shape[2]) * scales[2])
        W_new = int(int(x.shape[3]) * scales[3])
    else:
        ts = _np(sizes_t).tolist()
        H_new, W_new = int(ts[2]), int(ts[3])

    if _is_jax_module(F):
        import jax.image as ji
        import jax.numpy as jnp
        x_nhwc = jnp.transpose(x, (0,2,3,1))
        method = "nearest" if "nearest" in mode else "linear"
        y_nhwc = ji.resize(x_nhwc, (N, H_new, W_new, C), method=method)
        return [jnp.transpose(y_nhwc, (0,3,1,2))]
    else:
        import tensorflow as tf
        x_nhwc = tf.transpose(x, [0,2,3,1])
        method = tf.image.ResizeMethod.NEAREST_NEIGHBOR if "nearest" in mode \
                 else tf.image.ResizeMethod.BILINEAR
        y_nhwc = tf.image.resize(x_nhwc, [H_new, W_new], method=method)
        return [tf.transpose(y_nhwc, [0,3,1,2])]
# ─────────────────────────────────────────────────────────────────────────────


def _decode():
    model_bytes = base64.b64decode(_ONNX_B64)
    inputs = {n: np.frombuffer(base64.b64decode(b64), dtype=np.float32
                               ).copy().reshape(sh)
              for n, (b64, sh) in _INPUTS.items()}
    return model_bytes, inputs

def _rel_l2(a, b):
    a = np.asarray(a, np.float64).ravel()
    b = np.asarray(b, np.float64).ravel()
    if a.shape != b.shape: return float("inf")
    return float(np.linalg.norm(a - b) / (np.linalg.norm(b) + 1e-8))

def _pytorch_eager(model_bytes, inputs):
    """Reference: onnx2torch eager (no compiler) — same as oracle pytorch_eager."""
    import torch, onnx2torch
    model = onnx.load_from_string(model_bytes)
    m = onnx2torch.convert(model).eval()
    inp = next(iter(inputs.values()))
    x = torch.from_numpy(inp)
    with torch.no_grad():
        out = m(x)
    if isinstance(out, (list, tuple)): out = out[0]
    return out.detach().cpu().float().numpy().ravel()


def _jax_run(model, x_np, use_jit):
    import jax, jax.numpy as jnp
    inp_name = model.graph.input[0].name
    out_name = model.graph.output[0].name
    init_np  = {i.name: _nh.to_array(i).copy() for i in model.graph.initializer}

    def fn(x_jax):
        vals = dict(init_np)
        vals[inp_name] = x_jax
        for node in model.graph.node:
            for nm, v in zip(node.output, dispatch_op(node, vals, jnp)):
                if nm: vals[nm] = v
        return jnp.asarray(vals[out_name], dtype=jnp.float32)

    if use_jit:
        return np.array(jax.jit(fn)(jnp.array(x_np)), dtype=np.float32).ravel()
    with jax.disable_jit():
        return np.array(fn(jnp.array(x_np)), dtype=np.float32).ravel()


def main():
    model_bytes, inputs = _decode()
    model  = onnx.load_from_string(model_bytes)
    x_np   = next(iter(inputs.values()))

    # Reference: pytorch eager
    try:
        ref = _pytorch_eager(model_bytes, inputs)
    except Exception as exc:
        print(f"[warn] pytorch_eager reference failed: {exc}")
        ref = None

    # Target: jax.jit
    try:
        target    = _jax_run(model, x_np, use_jit=True)
        noopt_out = _jax_run(model, x_np, use_jit=False)
    except Exception as exc:
        print(f"[crash] xla: {exc}")
        sys.exit(0)

    diff_vs_ref    = _rel_l2(target, ref) if ref is not None else 0.0
    diff_opt_noopt = _rel_l2(target, noopt_out)

    print(f"rel L2(jit vs pytorch_eager) = {diff_vs_ref:.6e}")
    print(f"rel L2(jit vs no-jit)        = {diff_opt_noopt:.6e}")
    print(f"tolerance = {TOLERANCE}")

    if diff_vs_ref > TOLERANCE or diff_opt_noopt > TOLERANCE:
        print("BUG REPRODUCED")
        sys.exit(0)
    print("not reproduced")
    sys.exit(1)

if __name__ == "__main__":
    main()
