#!/usr/bin/env python3
"""
Bug v2-0006 — OnnxRuntime wrong output vs ONNX spec reference.
Compiler  : OnnxRuntime (ORT_ENABLE_ALL)
Root cause: ORT TopK(k=1) tie-breaking on all-equal values changes after gather+layernorm fusion — gather index reordering causes incorrect TopK selection.
Report to : https://github.com/microsoft/onnxruntime/issues
           (label: bug, regression, Resize / TopK / CumSum etc.)

Oracle: ORT_ENABLE_ALL output vs pytorch_eager (onnx2torch) reference.
        ORT_DISABLE_ALL gives the same wrong answer — this is a fundamental
        implementation divergence, not an optimization regression.

The ONNX model is embedded in unique_2625.py (the reference repro).
Run: python v2_0006_onnxruntime.py  →  exit 0 = BUG REPRODUCED
"""
import base64, sys
import numpy as np
import onnx
import onnxruntime as ort

TOLERANCE = 0.01

_ONNX_B64 = (
    "CAg650oKOwoMbjBfZ2xuX2VtYmVkCgpuMF9nbG5faWR4EgpuMF9nbG5fZ3RoIgZHYXRoZXIqCwoE"
    "YXhpcxgAoAECCiwKCm4wX2dsbl9ndGgKC21vZGVsX2lucHV0EgxuMF9nbG5fYWRkZWQiA0FkZApr"
    "CgxuMF9nbG5fYWRkZWQKCG4wX2dsbl9nCghuMF9nbG5fYhIKbjBfZ2xuX291dCISTGF5ZXJOb3Jt"
    "YWxpemF0aW9uKhQKBGF4aXMY////////////AaABAioRCgdlcHNpbG9uFazFJzegAQEKbQoKbjBf"
    "Z2xuX291dAoJbjEwMF90a19rEgxuMTAwX3RrX3ZhbHMSC24xMDBfdGtfaWR4IgRUb3BLKhQKBGF4"
    "aXMY////////////AaABAioOCgdsYXJnZXN0GAGgAQIqDQoGc29ydGVkGAGgAQIKLgoMbjEwMF90"
    "a192YWxzCgtuMTAwX3RrX3JlcBILbjEwMF90a19vdXQiBFRpbGUKbwoLbjEwMF90a19vdXQKCm4y"
    "MDBfbG5nX2cKCm4yMDBfbG5nX2ISC24yMDBfbG5nX2xuIhJMYXllck5vcm1hbGl6YXRpb24qFAoE"
    "YXhpcxj///////////8BoAECKhEKB2Vwc2lsb24VrMUnN6ABAQokCgtuMjAwX2xuZ19sbhIMbjIw"
    "MF9sbmdfc2lnIgdTaWdtb2lkCi4KC24yMDBfbG5nX2xuCgxuMjAwX2xuZ19zaWcSDG4yMDBfbG5n"
    "X291dCIDTXVsCm8KDG4yMDBfbG5nX291dAoJbjMwMF90a19rEgxuMzAwX3RrX3ZhbHMSC24zMDBf"
    "dGtfaWR4IgRUb3BLKhQKBGF4aXMY////////////AaABAioOCgdsYXJnZXN0GAGgAQIqDQoGc29y"
    "dGVkGAGgAQIKLgoMbjMwMF90a192YWxzCgtuMzAwX3RrX3JlcBILbjMwMF90a19vdXQiBFRpbGUK"
    "PAoLbjMwMF90a19vdXQKDG40MDBfZ3NjX2lkeBIKbjQwMF9nc2NfZyIGR2F0aGVyKgsKBGF4aXMY"
    "AKABAgo6CgpuNDAwX2dzY19nCgtuNDAwX2dzY19zdAoLbjQwMF9nc2NfZW4SC240MDBfZ3NjX3Ns"
    "IgVTbGljZQoxCgtuNDAwX2dzY19zbAoMbjQwMF9nc2NfZXhwEgxuNDAwX2dzY19vdXQiBkV4cGFu"
    "ZBILdHJpb25fZ3JhcGgqmCAIBAiAAhABQgxuMF9nbG5fZW1iZWRKgCAPzCQ7CSctu4vaUTyjfgk7"
    "NIcvvJX57Du5pdU8dCubPJeZZrygU8+8DTxMvMqqWDpudz69JmOPu0shzLwK82+8wVcyvFxKz7sS"
    "4gY8Ls6qPBN5KLuh4d88k/hZvJtd5jtJBpQ8lXL2Oj2hc7z3A5e80/wVvJ1OkDt0aqW81hWJuwyz"
    "ULtqOTE8062MO6Xl6DseP1a8HuMpu1BygDwKr/Q8CUnOvJAK+Dwbgtw8kwKAPEpQrTuCu8270uHu"
    "PJmVID0GlxM9c3fXPHw26juO+MW85NG6uBwdVzzLFdO8PXkBPJTbDDxLFGQ8gQHCvKLTWLzXAg+8"
    "Dam/vDB9Dj0CgCK88pfXO0Z1qbvVtwE99FPYPHiJTzzzgjS9DWSIOsEHYDwzfaQ8zXlKvFlCFT3k"
    "Vti8/sRYvNcymTz/l4A6NwkkPYsYdzsrfE+8pXD3u/zFsrzKVdG8wJJOPLhvPjy7GdQ860R3vCZf"
    "Cj2nV7y7vPkAPbXQDbzPAHG8CLOjO0f+qDzZCVM7uN0/vNS+27wFoOW8GLgkPJInojwdWFe7IQaw"
    "vAsKjzydx9G8fKhpvMF+SzzhVDi9Dzb9O5KXPrwvPA87b3LGuit1hDtdd2M8qoB4vE7Q6Dwp7W08"
    "tjyKPO/ZvjzYCYE8OUuKPAQqxjo8w+m8nQExu5AnfLwdGum8L2GpO2JNOrwhuai8ouKqvOrorzsr"
    "D+s74qvYPOfnkbntsao8QL/lPHJxvDwFxEG9u07JPMeS3juE3Ao8oEnzO/7X+jvQVNE7qTfruy7I"
    "G723wQ679a6DvFb5sDz7Pr27XdPaOg8zi7wdUie8p91xuSZd87yXDsU78QcLu7JEwryXdkS97h0o"
    "PFAGw7tUrC28LMSau0POFD3djIK6NBHjOluk87w08wY9PFKWPH3OrjxB8Xk6SS+WPIwa8zsH7kg8"
    "fHtHu1d78bxHkag8C4MevbE+nbsuCYa7udyqvH7oSDy/SYO7LCcPvHxXKjxZKhy8C5LjPGBU5jvv"
    "bRu8MUYfvSVD1rz8ELI80KeEuoGMubt8nQY9NSbSvInoP7yH2xq8iSFAPF1tWbw4AUm8bH4DvUL+"
    "bjzvE4Q8YBkcvMoXVjuCydO8jpoavHPD4Tyt5zE71UM9PUL5gLzJJT48byCAuz1oOTyxOxe5teQ3"
    "vHwmjrxzK3s9ZMHKunA0Jb2PiFS8GC5ePL7XI7xA5d48oTukPF2sR7tYvBq8aaCkvHNdZbwZXPG8"
    "ClTFPGlPAj1Azs28YJvBvGLgEL366p28m3h+vaYmu7yTfNQ8OYriu9wDjDyyOSC83zsQPTuPgjtZ"
    "Wfq7NRhRPVil1LvSFci84FKEO4GbS7rltK48IACXvEbYgzzdtos8q8lavJn3VTtDHIi8KStAPYK7"
    "ZrykdhS8fKCuvITV4rtbdfa40pZ7PFQLSLxlf3O73hPovMSPh7x5wWE955iqPE0HgLyBHtu86daf"
    "vPVx47nZEjY6fulzvNjK0rzhCuk8HwIUPBV69bvPnJC7PIQtvFWFcL2rmRc74mWvvKFHpLwbzVG8"
    "6/VvPJ7Hv7wg/uq8rqpRPAwxdzyYHJ28VUk4PM4fv7twdMU7gZjOvCB2iDxXJMU8k8FQPPP0Njws"
    "g5q9as6qOyBoBbpJvEC7t6BOvM4ikTrpCgc8T+Csu3LSF7yde8k8dBq1vNfHqDxrwGc7BseDvOQK"
    "vrtUu5a8hDRdPDsA5Dtzcza8Ypa0vI+7xTup25w8JDUVu/QVCTzibva77SCxOirlvrsVtMA7c1z3"
    "vJ4WUzxFsJa7cwTrO5AG37uw89E7i7qvvMDUwjzrjQu91kSqvDRymjsMrO882UW2OyN4orudfOm8"
    "zLV6u/Js0LnLfQo9pdtLPM6G+rykCCY91G8BvDcXkLyLovE8hm6Cuu7H8LsyYo87NG2KPIq/ojwr"
    "UOG8MrcjPUAimzxhg/i7FSGGvFTDnrzvtiE7i1dUvEeierx56oQ8QOzuOwlLAbwnmXA8BAjgPIFS"
    "s7zKr0W8bXCaPBuVazzCkZQ7e3O+POlKsryJV/K89PeNvPmeIDtNboK80qYfvHi+n7xeTUu81J+k"
    "vJnS8DsmPII8um4dvG7Vh7uLZD68lBQuPH506TrklwI9bXuzvNOR7TuyfBE80zfsu2Q2PzwDsOu8"
    "hZItPWzh27yDs5Y8S6+3vImPvDxeKvy756VPO2PWizoiWLQ8tbrSu1sSc71ZDnm8oMtwOyZVELxB"
    "QXw85lmmPP2vQbtBEPS8GMjiPI5ysTzyE8S7BLYsPZej5LtCTrq8ck5Mu6CXsDyml5m8J9gfPQnj"
    "krxfX5w80GgyPPjsSbvXCLE8Hrr1vLBs3jyh8aa6xL4xvEZ9dTxip608Hj98PKLMIz3vELE8K0rS"
    "PBLnMLxynws7Zno4PHQKurn+rcU7QqALPChSijxJLgW7kj7luxS2h7z3GZK8KxjAPGmR3brX7oA8"
    "Yo/UvFTGHr0T4qu8Bd27PGr+rjzVmtk7dG2DvBZyK7vrI8O77BTiuxhMTb0KkIy89C15u5dz+Dxr"
    "sFI7hIXlPIcCAbwcmqW7ZrifvffSFzy1RTM8tXwQPX2AH7zJ0fY6+S9nvMu3wLzUq2m8JhniuzAT"
    "3jzOhTk42oWBvE32OTtrlo47dJZdvLJOuzyMsRq91/KLu8ntWTzuSdu8UsDsO93T0zy0qBQ8OXUK"
    "vWydbryN5sk8WYTDO8bBTrmWkhA8+EVsPF4maLwNUb673VE7O3s+Mrzp6i67r6TUPE6RnrwL1R09"
    "tfQZPW5dDL1b1zi7G5bgO35SebxX1nK8vpebu8A2cjzKjSe8i6QVPZAJvjuOcga7W3LtPEY4TTwK"
    "BPI7IgTZuwmaFD1EAoU8wk6Fu0M0Ab3iavQ772O7vP+RDL3Z8ba7BHe4Oykf0jyOG7k76Q6EPD7Z"
    "yLxbROy5Z84iOzlFjTyAHxg7hL2DPE03Jbzeluo7hPEHPGXDzLz9FGY76vPRu577G719Bp08zyXt"
    "u9Sni7w+R/e7UyQ1O08O9zzyfVm7acwaPBgM4Tx31S481BKvPIskHLxOqHw8CfuXuhMIsDxXbKS8"
    "C3J/vHXezzxvgYC7mz/ru/hZyzo972G8qznaPK6pzLxOZEW7BWHjO5/mCLtgcoO84kaOvKtkCzx8"
    "1ai8xMJTPGq3+bxb2zW8Hlk+Og8nzbyiplU8wGTCuRTAqbzK2vi8ykAAvU3IhTr4iL28M5/fvEaJ"
    "l7umkjo9i+O1O0X+eTw3aIs7p0iAPDgN3Lz2EQ28ZUerOxXfu7k8pnu7vDFavH1VqbtrsH28hWVG"
    "vVC1w7yp3Bs8lRz/PIiRFD3+oP06OV+SPFvDlDzp1mK8YRgLvULwIToIXBC9R6vRu49ERzwHqui8"
    "IVIpOiEqyzy76+w7hScrPHOPlDzf9g09J3lGOwFxyTw7N6i69fcyvDJSzjtEg0a8kM07vPskR7yJ"
    "Cjy9wEcKOxgRz7yLmQy7GZDtPK24KrwGmzG8gXbfPHMDMzyE/p88+9fou8UhdTz+12C8IoNdvJhg"
    "QzwuE0S8kF57PELtQz0vIQq9eXt2vFWGtzwnKD67pDu+PCp9pbxUJtk7UFZFu5n8NzsMANk7xuLH"
    "vJf8r7yLQOU8GSnAO+hjCzsXFGe656npO4Bjvbw+rqO8CrvVPIpHRjs0UIs8x3ZGvAyQ4TwbSOI7"
    "07EdPMHOMzz9lIK8ANcYvX0YsLyLkgU9pBrVPL5b47vktMW7ZtapPPm8XLvp3tS8uVjPPKRcHDx4"
    "I069lEDNu7hPPDvpsR08d21HO+JRULxKuhe7STPBO6Cjr7uVuvO7NCTNPJsXm7w9BuW7zWYmvdlD"
    "MTzus4c8abozPPlZljwpaRA8i3jgO5BNGzzqLq+7FbLCPLBw5Lt8l++8gjqLPA2cFz2oT528vzUF"
    "uwubYLxGa/m78KhxOjh1y7yO9rW7IS/wvGQyOrxdU8K8OYStvCTlDL1wx8c8+M4mPCIUHb2GkUO8"
    "d7BbvJhoYryyDu28dTJ3PHa3AbwtZxk8eZssPFxa4TyhrBS9IW0OPfjhzzxCyDs8jUNDPbRVhjtS"
    "l4Y8p/ZxvGbauTwM+Vs7adkTvG9rLT3mwMe75NU5ORZKgbtFnne8XBYuPEn2cTzYPeg76mBBvXYm"
    "pTw+iOW7TUjHvOCuRTw7bzg8ruWqvLyKSj1qL8a8s/cNvXUZvbyqyOg8uX9mu8HU87tX8aK6mX9D"
    "vH0vYrwOHVK8nftnPAUxpzzK3ay8y8ecO88jgTz3O7G8V64kvJATqryphdO8goMFO0I3cbzyzk48"
    "b0EaurE1BzzvjL+7cBNQvLWx7bqKjdG4c0tnvGvJCzzqpHQ8wTNPO4JeDD1wNE+8y5YqPCnvBbxM"
    "xJk7mfqHvKqztjzQtmY7XFbDPOVvz7wOtyG87DySvIVOLrxP9GK80/4du3PZtLn04Fa6uAg2vHSp"
    "dTv5dY88LtSTvCcWlTchLMK6b3gZPMVmp7riQaS5kmGivMyU4zmjCpe8afwoPIdKB7sQ+VA6OwOS"
    "vAmwgzyA22I87yaNPKt3Nj0prYm6YCrFPLdNIrtwIgE8c23vOyFnrTuHslc8EDDHu2GaVjoHaS88"
    "Jy8PPQADirxZ9RO9CaAevPO96zqSWGU7T77xOtDJwTx+6p88IieBunfcGbynwuK76oHpu0/Zk7vf"
    "1AC95hIXvIU5C7y9kXe7dqimuws0XDylTi68kLYPvB6VMTxHN5q7FNuNO/NTWzxeRQo8S/KjO229"
    "gLtscV88yRhmOx5uJbwqq0W7DZTHvJSKnbxxPxq9x8xevNXQ2jyqWTa82weBPIeykLhLjmW8gkPb"
    "PPfGPjzrgQ+9k5+qPAYYsLwDMmm7au1aPAKDxLvqU7c8b3N5PHotAb2mzhq8Hty4O2JqPLwtvY27"
    "aQmDPBWbzzuP1Za8LNxkO+agSLzcGMe8+yW5vCYPvDuUZRO6mdPjOH3Lu7yDFHG79u2pvMbHl7xY"
    "b1i7mafivDROWzy3uUs94lgWPIfeqrxhubG7y9f+vIN597uTPCY8LiFBPG4KqbxPDMQ7RXe9PPDG"
    "Dz3vomW8LZeNvN+ljjqA3m+9XAIuvA6WsbtmhBa8O8ABvaTsoLunen68STZ4PKB7lrymCbm7LaqY"
    "u1f7OTx9j1C9YTvfuyLpeDw3Ce27YSz6vBQK1juwptw7l0Sxu1wFvrxVtHK8m5/Nu4Jyj7wOTR29"
    "dBR8vKfbobpHJya8ExzGuutN2zoa5ZI8iok0PQ/KbzzPFea8LKhZvX2g97r4I7s6gFy+vGtHsjuO"
    "T3u8YvIDPOJU1buUPQI8dM0OvUStD7yLxEK7lHPpvH4zGj1cMzG8pLvjPA6xWbzCtpa7cvjBPK8d"
    "xzu+uns750muO9DU37w7TP+7PbScvIRggTveQTK8Jv9muimeyrqBrz66zSw2unDFVbwUsKy8PrJZ"
    "vJOPrzzvNfU7YlVAPAwY4jzrPMG86RknPOAjsLyzG9u7KhoIARAHQgpuMF9nbG5faWR4SggAAAAA"
    "AAAAACqSCAiAAhABQghuMF9nbG5fZ0qACAAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8qkggIgAIQAUIIbjBfZ2xuX2JKgAgAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKhkIARAHQgluMTAwX3Rr"
    "X2tKCAEAAAAAAAAAKiMIAhAHQgtuMTAwX3RrX3JlcEoQAQAAAAAAAAAAAQAAAAAAACqUCAiAAhAB"
    "QgpuMjAwX2xuZ19nSoAIAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/"
    "AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A"
    "AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA"
    "gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA"
    "PwAAgD8AAIA/AACAPyqUCAiAAhABQgpuMjAwX2xuZ19iSoAIAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoZCAEQB0IJbjMwMF90a19rSggBAAAA"
    "AAAAACojCAIQB0ILbjMwMF90a19yZXBKEAEAAAAAAAAAAAEAAAAAAAAqHAgBEAdCDG40MDBfZ3Nj"
    "X2lkeEoIAAAAAAAAAAAqGwgBEAdCC240MDBfZ3NjX3N0SggAAAAAAAAAACobCAEQB0ILbjQwMF9n"
    "c2NfZW5KCAABAAAAAAAAKiQIAhAHQgxuNDAwX2dzY19leHBKEAEAAAAAAAAAAAEAAAAAAABaHgoL"
    "bW9kZWxfaW5wdXQSDwoNCAESCQoCCAEKAwiAAmIfCgxuNDAwX2dzY19vdXQSDwoNCAESCQoCCAEK"
    "AwiAAkIECgAQEQ=="
)
_INPUTS = {
    'model_input': (
    "gQpYPk30K8C52Zs97Vuevr9Op78ebuW/ktjuP9JudT8R/dK9IAy9v0mkmT9OrAa/8j1vP7u41j4h"
    "CIW/G4Dzv9LD0z5jXlw/oGu/v7obQD/6cyi/ugONP0ZmAj+SK5E/aRpiPuAnUT+iMvS+J7awPtXN"
    "Iz6M51g/BLGxP0QlgD6kYTk/0IyKvsLXhr/pgme/7w4VPzXfAT+RG0G/Z4cVv2CsTz9yyZS/gS+w"
    "vssKE7/XwuY+wcZPv/0mKb6hBBG9R4K0v2hkrj5N2wm/GdQOwLJtvb4ZwhlA6lpLv6nqbj6QTga+"
    "Sl/mvyKcmz7eBnU/6EBVu4O9HD5BAeO+Luq5PtwhHr8zXEg8VrAxvrz4bT9HCuo/cIzfvjRZpb//"
    "Eva+RdQ1P9f9jT+M9rC+SZeOPx4ihj76Vbi/auhEPjImiLwkOOs/7gLKvs7rOT6lwwG/c6/jPsV9"
    "j78wXqs+p9hgv6sDoj59INS+GnBYv+3UmD/74Rc/1NmlPd2sqb4IfJE/K7gDvqdnOj5DRpy/R2i3"
    "PXAOpz54r4+/xT7bP4+yvr/BI4S/1bYmQKRUAEBv4wA/ilaDvz4umbtr/AFACrg6vn4wVj7NlRk+"
    "cBGEP0oz8z843909oTGbv17SSD9Hh94/A5qKvpRpJD910Ms/Uf9UOwoPjD8IiAXAZqqlPnTVxL/7"
    "FzU/HC8NP0tFqL+DpYo/OizCP7ePjD+kucQ/PI9WvnerCr6p1fs+AmYxvhA7Mb4a9Ae/cNv3v2Jg"
    "DL5JsNQ/lLocv/Z7iT+7kYG9SFROPbj+Tb+ziNs+fKOrPy8LoL6hhc0/7/m4P6HCCD/2+849sRio"
    "v11C8z6FQpe/tDxnP4D5vz6I2S9ANNFIv5D4Bj9DGVC+6A6bv/28Qj8usYm/GbTNv/XZmj+LdJ+/"
    "2HKFvpfK2z9Mt7M+dYq6vwwWoT64ZAvAr6pYv7cgRr9Bzt2/d9TZvwJOnz/JgSu/dPhQv1qSEz8f"
    "9vK/GesgP/39Wb/PVLm/NS7WPSFnoj+SXxVA227rP15qKz8yVoe9CLlbP53Ztb2r2Qa+UNqmP+YP"
    "Vj9fC2Y/GP0Zv49Ndj8OPv2+dAKVvRL5BL/nv9Q/lbeWP+Kp2b1Q3bO/VBuuP1g0tj4AKO09bp/i"
    "P/nuV79NrKy/R+xdPwXqqL+r7fe/2HuIP+i6Hb/v72u8KRa5PpSHaD/a1pO/1dGCv34wxz9mkq29"
    "36HrvlQwqT7D3Li/f+nsPsUJXL7YAjm+9Ke0vkeDFz9SYAM/bq62v30LP8AGsxS+jS43vzVehT4/"
    "x0w/t/A5v5RiA8ALVCA9iOQLwPduA8D6n9g+nbKRPlsVH0AISSo8yIMKwFPjlD8OL7Y+iT6mPw==",
        [1, 256],
    ),
}


def _decode():
    model_bytes = base64.b64decode(_ONNX_B64)
    inputs = {n: np.frombuffer(base64.b64decode(b64), dtype=np.float32
                               ).copy().reshape(sh)
              for n, (b64, sh) in _INPUTS.items()}
    return model_bytes, inputs

def _rel_l2(a, b):
    a = np.asarray(a, np.float64).ravel()
    b = np.asarray(b, np.float64).ravel()
    if a.shape != b.shape: return float("inf")
    return float(np.linalg.norm(a - b) / (np.linalg.norm(b) + 1e-8))

def _pytorch_eager(model_bytes, inputs):
    """Reference: onnx2torch eager (no compiler) — same as oracle pytorch_eager."""
    import torch, onnx2torch
    model = onnx.load_from_string(model_bytes)
    m = onnx2torch.convert(model).eval()
    inp = next(iter(inputs.values()))
    x = torch.from_numpy(inp)
    with torch.no_grad():
        out = m(x)
    if isinstance(out, (list, tuple)): out = out[0]
    return out.detach().cpu().float().numpy().ravel()


def main():
    model_bytes, inputs = _decode()

    # Reference: pytorch eager
    try:
        ref = _pytorch_eager(model_bytes, inputs)
    except Exception as exc:
        print(f"[error] reference failed: {exc}")
        sys.exit(2)

    # Target: ORT with full graph optimisation
    try:
        opts = ort.SessionOptions()
        opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        sess = ort.InferenceSession(model_bytes, opts,
                                    providers=["CPUExecutionProvider"])
        target = np.asarray(sess.run(None, inputs)[0]).ravel()
    except Exception as exc:
        print(f"[crash] onnxruntime: {exc}")
        sys.exit(0)

    diff_vs_ref = _rel_l2(target, ref)

    # Also check opt-vs-noopt (delta_opt)
    try:
        opts_off = ort.SessionOptions()
        opts_off.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
        sess_off = ort.InferenceSession(model_bytes, opts_off,
                                         providers=["CPUExecutionProvider"])
        noopt = np.asarray(sess_off.run(None, inputs)[0]).ravel()
        diff_opt_noopt = _rel_l2(target, noopt)
    except Exception:
        diff_opt_noopt = 0.0

    print(f"rel L2(ORT_opt  vs pytorch_eager) = {diff_vs_ref:.6e}")
    print(f"rel L2(ORT_opt  vs ORT_noopt)     = {diff_opt_noopt:.6e}")
    print(f"tolerance = {TOLERANCE}")

    if diff_vs_ref > TOLERANCE or diff_opt_noopt > TOLERANCE:
        print("BUG REPRODUCED")
        sys.exit(0)
    print("not reproduced")
    sys.exit(1)

if __name__ == "__main__":
    main()
