#!/usr/bin/env python3
"""
Bug ID     : bug_000342
Source     : Trion campaign v3 (minimized via delta-debug)
Compiler   : tensorflow
Patterns   : Greater, Cast, Mul, MatMul, LogSoftmax, Mul, Pad
Root cause : tensorflow rel_L2=0.326
Minimal ops: Greater -> Cast -> Mul -> MatMul -> LogSoftmax -> Mul -> Pad (7 ops, down from 8)
Tolerance  : 0.1

Exit 0 = BUG REPRODUCED  |  Exit 1 = not reproduced  |  Exit 2 = missing deps
"""
from __future__ import annotations
import base64, io, os, sys
import numpy as np

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")

try:
    import onnx
    from onnx import helper, numpy_helper, TensorProto
except ImportError as e:
    print(f"missing deps: {e}"); sys.exit(2)

TOLERANCE = 0.1
BACKENDS = ['tensorflow']
INPUT_NAME = 'model_input'
INPUT_SHAPE = [1, 3, 32, 32]
OUTPUT_NAME = 'n300_prma_out'
OPSET = 17
IR_VERSION = 8


def _inits():
    i_0 = numpy_helper.from_array(np.frombuffer(base64.b64decode(
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
        "AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8A"
        "AAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAA"
        "AD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAA"
        "PwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/"
    ), dtype=np.float32).copy().reshape([1, 3, 32, 32]), 'n0_grea_c')
    i_1 = numpy_helper.from_array(np.frombuffer(base64.b64decode(
        "uEFyvmXtsTzV89o+tC4OPSdpCT+aSdA+JLPTPcAxKL41r9s+Dl7gPTiEqr75KpW8desXPfFR4L0R"
        "wkG+56LTvVHygD2XdHU+CrMWvkaKE7+7pns+W77lPUBFQ74YvWC+bTu3PjgvAr9gLY49lIKFPsdU"
        "1T3l5um8wlUGPr69Ib74vIq+5lmrvnjSEj1kKsi+gcpkPsElr77kFKc9zHWavq+cdLzsHMO9oiSO"
        "PmF39j5/ns28RswjPuK0fr0ecy8+qKDfPQUHt73EujE+4/5GPgSxMT5Y/b89khiIPtKEkT3yxHG+"
        "MZw5vrLzdL2ltds8PxcVv9rNPL7reoo9KtowPUOrUr7oKJa93zlcPtMmFT5TMTw+jxljPjuZpj4c"
        "cle+fPT9vfQrVb6gLyS/c9ToPUO5Hj7DKpm8jfU3vnvB+j3zVcK+AjWUvv8Ghr6tyBq+HD4hPwqw"
        "nT7dqBs+O2Q2vsJGLD46qIq9h2fivcKDkL3Zrl6+3He2Pji7Lb7DmJU+UUHGPvyksD0TgFI+E9Ee"
        "vm0sI75d1ww/9RYhv7TvhT2DTjA+l+mUvcWvlT4CbCY9OAm5PitXT7zpt8c7WQOcvdOpBr6bbcc+"
        "OvcavrX9yD5itzI+gWRxvIRABj5r4IC9/T7dPUcIgb6MXKY+mlq2PncnhDxXZwI9OfYSPGoiqr5i"
        "IKY+ueFqvrefnzw7YYO8vOhIvtSQOz6pyKm+iSeUPcnigD0VtRS+dYY8PrUjfr55+MQ8XyePPply"
        "vL1cAeS9baQavsBV1L2Qs8g+eRaOPjozIj9oWtm+d/QqPfZ0tr0WmGu9jvtQvnLifL2vs2q8Vkkv"
        "Pqz+Iz7XIBI/qOUcPu2ggD7Lowm9XhGQvU0YGj2QGBE9RpyyvgtiID6dI7K9Ou0MPvdhHz6lEnS9"
        "MESCvoK4Y77vZpG94gu7PpW4HT6RYP0+RRlzu9h8Xr0NKAU+CNLRvewYK75gzRI+0v27vcGyXz04"
        "S42+/E5cPVXwAL6WgMM9xNDrPHUJTr8P3369lxCTPXmkiTw1DyE+7BhivRvfWr4J8pY+kAIEOkfH"
        "Br2ZYUE+4idzPTsHHD0ltVQ9ZdSkPKTFR77fFj8+kuQePLW0nb0YM3c+BtzcvX292r4+lSs9Vkvt"
        "voITrD6/JSe+2zQ4PmA2I75GR2Y+NtqjPoMJ/L7L0uI83/lTPhwy+z2+sIG9jfTaPlG3NTxkVJK9"
        "4r+XPZlJ2D73rWa+JSVdPf/IP77LPUg+8udsPtAs7r4fzUo+sS/NvUp4RT5ClLe+gyxsPEaVDz5h"
        "HAK/G4VpvsL7ZT4prjm+9tXmvRU8Hb4BUx6+TTp9PeekrT4xqw2+4AP8PZJdOz5tG/w8qJqKPcOB"
        "/L65vZQ9YTEFP2qVoD7DNCI+QDHJPiOClT2c3ZE9EIQLvzequT7Hwi6/dZLJvfTsIj7l7ic+A7nE"
        "PjxXH739D1u+LSoavRl6rj0GIrS9CmiIPkE3mz6qqtQ+lmx7vq40nr10aCO+3eHTvc3ABD98Eqw9"
        "y5aDPtL/Ez6FdqA+rN2APfA0pb5P6YA+Vq+1vTqCc719rTe+FSKKPsFKID5Qepu+XQw6vbRPnj70"
        "6Ko+0Gq+vnPAlT6xmYa9Y1SCPfyw9b3JoJs94p/dO+Lolz01ORG+bGjJvpBLj75xYzw9OqCZPcx5"
        "xD3TjSO+xLHYvoFJiL4RTbE+jJQwPnfmrr1YmsI9VO9Rug3U+7wD8Mw9WxiJvess7D1DArK+XWOl"
        "PVaqqD6+MaS+loq7vQOZrbx8XZY+kKSUPKbcKb4/5jQ+9Y2SvjfijL74TS88srYzPtQznL7Y30q9"
        "xrJMPu5n1r5UH0W7aX2QvcUx777quKy85MGTPREF3j7iFkc9nLdrPnmM2j7Soac+mVRkvt63or1u"
        "u6G+s7NlvnH4b759bdq+4JeNPnbdN72aKyS+/6wpvch0Dr501lw+HVTuO9PvYz4pNYG+d1rKvLze"
        "Nb4rW8Y+K5+BPpQgrbyfWms93LaLPV/jgr3n6Q8/T76FvJGEDb27k5e9QIqkvd3djbzUjzw8He9b"
        "PkzLqz1lGZy9/40xvl111b52Nhq7zxcKvud1hz52oMG+hQnMPVRCHL9uZ8o+ZxtevnJfir2XyxU+"
        "q90MP7mepb0j1SO/PVOGPi+ndb1K1pq+K+leO/faBr3lADI9R4d8vqQhvr4iAGY+H6VcvpCDdz7+"
        "zH4852+kvSDTBr5kE+K+g34qvGrGrr2xaFK+/6MhPgtDDT4DSYU+k9d3PZXKqL11oS6+eDgSvlgx"
        "qr4JGgI+xyJIvnRnEL7UPqI+CdZ0PoRwPr0MZpc+Klv4PYu55j1kjCE/IxEHP+1hmz2m5ZS+eLfD"
        "vj98gD7ryCm943zYPntHJz5Rirq9IZTQPbjQ6zz0usI+gyqEvmuYbr7Mtxw+T4ervcPniz5iF9u+"
        "4J3rvJddIL54gB6+Mjk0vvoo8z64MC0/FZCgPgCGDT6wXZG+a26ovgFeeT56cXq9hWETvuWPnr7s"
        "w/O+nFeUPRYRcL2y5Z89zkksPiRleL2PPK69ECxtPPu5gr2lx8M9bH/uOyHqHz5TsLM9BKgUvvuO"
        "Oj585VU+svdsvluhzj6rSuw9Vn+FukGTBz+y+CI+ftyWvlJTqj3eWRG+YZe3vhHAdT5BEB4+J7EG"
        "vT/ZHb9P2lG9MMTmvdwgkL6rApe9PJ0NPyrSoz6GOcW+Ruqsvf+0pr02gSe9ljTyvpwvhD6ExJ2+"
        "JyyHPtH9gz2j18W94gpuvW0e7j4jdtw+pOQFPnIpnbyydU4/oIZDvi+11b3IN48+79q8Pu5zOT3H"
        "2oc+pG6uPdPSfb1Yu549uzs9vxiUmj4GnhG97kmcPh+4oD0Nigw+6VEYPkwDkr6Ap6w9ThDaPcGG"
        "zD42r6E9l02ePCy5qD4xfBE89PitPcWxcT7O8ui+wSdLPTqaWzslIAC+3KyyvghAiL296ok9zdTL"
        "vUBh+T1axIy+I2hUPgDSkz2AQ90+JKKbviTz8D7HxUM+eSVHPvEYrz5SvT6+spcRPvONIL65NN09"
        "bRyKvqZ8pb6zcNq+96GDvp6SGb49hHe+bbECPfJ5pr2XOS89EJ9GvCRFhz2g0Q6+AG1BPbJqQj6q"
        "mVM9C6IWPpH7xj0slWI+du2Zvh6VVz6zQSe9r40rvc/quL3+SaS7k0wTPjeRGz1zRX2+HsXgPi4N"
        "1b5GJS++5E4kvcHApz4bFfa8O4AZPgdkhL4wNzS+W6tNvpLYHz6JXXg+baVXPWiwiL5z4Co+d73B"
        "vU6xk76ZRWW+zN6ePuA8Z73hMo++iVK3PiccPrwyJ5O+/OIrP+w7gT5mIzw7bULmvdKIg70SIMQ+"
        "Sh+mPb7+nD5cQJM8H6vxPZ3kp723AF++Wy4BvXGq0D5ty7U9MnEbv5mpRz4Y+p0+QJsUve0kuD5E"
        "xYQ+qN8wvYBPvD1WoC+9hSlovsaUiL7LvZ4+zF0rPtKS/L0Fu3++yUDjPd2w87z2MHo+tiuSPqje"
        "KT6caYM+NWeJPdErlT0KGRI/9f1huwrjXz4egIW9ayi8PZGCHb4Uj7E9/6ZnPvwJmru80Go+K6iP"
        "vjGAZz7GlhI9WdCOPRgYe75ukIg+FLNavI0npD7iOBq+hW+Zvvvqvz4ithS+d7t0PoRfDT4sDPY+"
        "3rmKvu7ADb7G1Ow+Yx9IPj9QrTzM2Xy+MgbkurljA76KUN0+GyGGvk4XG76ANGi+C0QPPuEKtj7p"
        "a3A+ldp0vZLjhTyLiZ4+ZQGePjd8kz4Pp2A+TcOyvYlEoz6Ae7I9185gvTACEr7uuTS+h9qMvj7J"
        "kD574ry8zZwtPLbtqT5QNJW+SaatPUIus739CgQ+mP4Fv6xy6j3fomQ+7c1uPhxZRb5Z7Ba+UOwD"
        "vjhEsr6rga49nYf2vlHsJ74+Rc++KRUxP81Opb7tVq29/mYFPufqlb6Dk0G+gtUDPgZ48D51Bwu/"
        "ZvMdvlgYi75EQcQ9i0skveXSebx9KkI/qY2ePq4rUj0ILE0+FAy5PQ7qdj4dZHg+E5FMvj6RIj5n"
        "W24+ntIqPkiKmz2m6nU+3ofJPszQfj1fn1g+bcKrPozKnz1sJdg8Qw+5PvS0rj2k1Wk+Sr4svehO"
        "9j4FOWO+x1wVv4EPvj4NMhc+xhxTPROl1j0Y8Js+6rGMPLE/lT3W6IC93a8FP3MGaT1lv7A9r6GA"
        "vlBcxT5ntIm+ygGhvQFB/j0Z+ts+/fFmvXMGdD46ICO+MZaVPeFHGr2miti9z+JLPae6Eb0YC0C+"
        "fZeKPSs23D5GPvU9gGwSvjgdkj5Lyba9kVa/Pt5nh76QVYi994G2PRcDEb5VhaS9SpBTvYLmgr4W"
        "YvC9Eo9JPveWADus6dE92PD2vl/jwb1hVvQ9KchOPq9Jer5/0gk+0SoRv1CvA74OV8E9nJCoPQq+"
        "X7xFkAS+J1ZgPnrRVr7dlQ6+nosxPij9B77ztIs+nEtqvkDlDL7ydU073TAQPs6FIj6IZns+QXum"
        "Pd+Rgr4fGWs+FVuEPvSuGz5KPs08REGKPlR+gz5tJ64+KbgZPrczZz7KUvu8SFyaPYJXbD2Hss69"
        "KVA+Pu+gzL7JDMO9basFPox2AD88qL+9tysHvhhDO76ptrC99gCBPgppvr6MQeA83QGWPttqW70F"
        "kLO9mt4Nvp36Sj51n8q9416XvUnC4728BwU+NShpvpm8Sb7ERWi+vEfGPEHqFr64Czk+S6RhPhT/"
        "rL4TL/K+U2fmPmh/sb4CtQq+CpKdPZbP+j5LfJ++iBJWPn+zMzzKmRG+nwk+Pd4oLj5Ks66++m7a"
        "vLK9Bj4rM+W+GKGLPkx5Ir6e0O68FSCfvlK7ej07sk64HVNrvtKeiz5UYr8+NZiRviXfZzoCf4u+"
        "ZXgKPvTtrT6OfLM+sP6ovvpfPD5H9p87a25yPVLyszx9Tmq+P5mkvgkOhL25lqu+q38HPrcNNr/g"
        "Ndi+PZkZvrtUMz7yZ0m9mQ6UPre3T728+JE9SfKTPvWhJb4wkh++mJonvq3LT76RcCu+CQYgPf5C"
        "uT5NIc0+fAkoPRNAc759pgC/77ktPh1Fiz431bO9PIZlPuP9Sb5zYmY+XUhFPqOEuz65C6U9SPMf"
        "Por9Wr6mFSi+db7gPqx+CzzbpZE+3uS2vhyrcb3momG+1B8JPnOVHD78IHo+3y81PfZqGz7BoGi+"
        "SO/QPZJ47L0tjLu+VXKGPjxDGT3PIAg+3KOMveWIMLwHWmG+0s8hPiY6hD5KhDA+GWVgO9Oorj4R"
        "5Y8+dDzePdjy1L7LkB0+asd1vjK6JT4aP5q+6YGLvXVKvj6WjGo+1xu5PixwubtvQO4+1UYwPocS"
        "mb5Tchi/gRgeOx+yhr5NSDq/44loPiF5pr5Hmpi+HInFPn4lwT58Hp6+SUXdPIN5xrs8hmY+B5lA"
        "vvIvnL3b5OI96boqvnYPmz6fa/w+Dobiuy+x4D4/sOE+X6abvN1ivT7ikH0+jGbAPg=="
    ), dtype=np.float32).copy().reshape([1, 1, 32, 32]), 'n100_mm4d_w')
    i_2 = numpy_helper.from_array(np.array([0, 0, 2, 0, 0, 0, 0, 2], dtype=np.int64).reshape([8]), 'n300_prma_pads')
    return [i_0, i_1, i_2]


def _nodes():
    return [
        helper.make_node('Greater', inputs=['model_input', 'n0_grea_c'], outputs=['n0_grea_res']),
        helper.make_node('Cast', inputs=['n0_grea_res'], outputs=['n0_grea_cast'], to=1),
        helper.make_node('Mul', inputs=['n0_grea_cast', 'model_input'], outputs=['n0_grea_out']),
        helper.make_node('MatMul', inputs=['n0_grea_out', 'n100_mm4d_w'], outputs=['n100_mm4d_out']),
        helper.make_node('LogSoftmax', inputs=['n100_mm4d_out'], outputs=['n200_lsm_ls'], axis=-1),
        helper.make_node('Mul', inputs=['n200_lsm_ls', 'n100_mm4d_out'], outputs=['n200_lsm_out']),
        helper.make_node('Pad', inputs=['n200_lsm_out', 'n300_prma_pads'], outputs=['n300_prma_out'], mode='reflect'),
    ]


def build_model() -> bytes:
    inputs_info  = [helper.make_tensor_value_info(INPUT_NAME, TensorProto.FLOAT, INPUT_SHAPE)]
    outputs_info = [helper.make_tensor_value_info(OUTPUT_NAME, TensorProto.FLOAT, None)]
    g = helper.make_graph(_nodes(), "bug_000342_min", inputs_info, outputs_info, initializer=_inits())
    m = helper.make_model(g, opset_imports=[helper.make_opsetid("", OPSET)])
    m.ir_version = IR_VERSION
    return m.SerializeToString()


def _input() -> np.ndarray:
    return np.frombuffer(base64.b64decode(
        "t1DNP5CNDT91mKnAp3uEPAb/7b/mhfi/wm0wwGKceL+RCovASNGJP2Icx79/AbC/9IHmvgjQW0BS"
        "ujq/PwCoPPTRhsAC1JI/xEGjwNTznj9QM8LAe3tfP4YjBkBZI6W/toP+v/mOmkARbCc/Ooc9wOth"
        "ar9MD2S+Zj9LwHsUDkCnHg1A3jEEQNM8kb/Ep7i+w8fWvxS/F7+Hwi6/mKKzv0mIPUCAF1HAj6y4"
        "P+SsgD/dBDDAFcMVwJWXPMBjAnNA50zQP9Jmjr/WJ6u/DP/8vfXp4sCAms4/BuBTwIu0yb263rm/"
        "CiRKP3UVpD/j5ew/HrUFQC4JQL4KXD5AozWxPgd/VMBmDIy/dzjXvgcggT8gzsE/OWGWvxx7mL/t"
        "tj+/nMzVvdEwyj/+hmlACSqLwHIiI0B5jjO/9RzxP8j1MEDv46g/m0IEwP1nKcB6+BZAj6NDvwJc"
        "qz8VSu+/E5Wmv3asLr+WrWw/sMeoP8VN1z37N7W/+8gPPuJUfsBueqC/1ofUvqWEZUBMRGZAjCBA"
        "vrEWzT9kaKm/Ah0RwHtO0z772yy/qzwiwLwdqcAo4QVAxWszwGX0MUDZWjS/TwLTPlZBP7+6+tQ+"
        "Qz0PvxIY7L/rkpc/CsDfvkAkkz4qp9u/d2SWvzsyiMBdxTdAunsYPgp1Pr9axKo/UXG5vzbfbr77"
        "KTVAig/Wvb3qV7+2dss/z/LAv6MjC75q0ITAk96ZvzdESkCm8Pu+SDyBwGM63b6i7kA/wlg9QKId"
        "Zj4+ccm/yTe2vWkYbD8L+zTAQn71v0xCPz+oX5W/k7pBQMSRHD+oTkBAiD9fv2YweD6mvrE/EIkc"
        "QExLQr/TB7I+oNA2QI2iDEA2QYm/AqUsQCrgVUCex9g/2CffP/G6pz+DAJM/NNIEQMd3Q8AU3qO/"
        "6iGNv0gELj4Ow8u/elCYPdlIBj52I1dAs9xrvxQzXcBIOc4/1SdvP+XFAUDZ3KQ//wxkP9pDyz8M"
        "Zh1AqfxvvxG7xj28fg8/5uD8vydjkT9NGTc/vvq3v0OwrD2otJK/5rGdwINAC8B4n67AiU+CPHQ1"
        "pL8oWMzA9DQ9PN46AkAI41s/YXGMv8Fp8z61O/2917QWvIV1sT+gnx7A87Pjv1p5CkANfXI/udMJ"
        "v9FjI8Bnt2I/+E31P4cj4D/Lg6Q/X55uv029BMBTV5S/n8baP+oMRkCLHL+/prcpvrzCor/SqXM/"
        "+iAkwBjl/b5pXfu/DYFNv2fQmkAF+6c/m10iQIyqhkDW+iY9JJzYv3obNcCELPw/JwgMP1WWNcCO"
        "t/c/+3I/Pyl5A0BfyhQ/qxYAQD3oZL6MpU9APGkaQNUc6j9aNcQ+bwnFPZdWTMCqmDxAHq9EP3Hz"
        "1b/r6DPAhJr2v1fs3b85czK86kmOvucRW0D24hrAgDQ+v+25T8B0e9w/pxV3PgN5MEDsD86/T7WQ"
        "PyJA8z/57mpAXJq1P4ApFkB1w6K+jtFNQLqnBsDy0gfAobffP4rgVcCz30a/PPIcPne1W0DmM+E/"
        "fUBNwLbWjcCL6zhAKviqPjqCs8DvVk4/pCczv5Fx4747S+K/f7Itv7iyzb/wbQHAhj/sPw9Ikr12"
        "vITA4eKfP3Z7pL2QhYq+4EcuwDyUrz4WMYm/9oigP3Pp6782R10/LdYHQAnWoT5MTCy/Mhd2wM35"
        "V7+E8Rk+neJaQOJTBL9IPIs+2d7BPxhvmj13Zaa/G+cFwJytHsDVY2M/BNfNQM/rw78bm7m/B9cI"
        "wO3uBL9Jdi2/z4yWwHYXMD80YCLAw4J2wBfw4jwy4HM+aNBsv/ac4D9waLy/y82XvJtDmz8Phka/"
        "J83cPnF6eEDFb7Q9krRdQKj2C0D9CENAjIOyP9qChUBlenZA+fLIvlMjlL8vnxi/C/4lv0eNBcDy"
        "V9w/eqbqv0fVkj+q1D+/xSt6P+hFLsAKql7A2TsTPycmNz5elNK8OXiMvwHE8z50NIq/3KqvP5Fl"
        "ID+5vCJAq+gqv5tKzz/aT/g+WR5YwAiBdL4A/qo/gF8vvzE7XMA9DX8/A5njPFSh+r+RZAA/u78C"
        "QPBxoz/hfH2/VreTPV6Tpz/Rn4A9v2ijPnNGEMAlsNM/7JZNQPoJFL7TaEXAZxfsP/hKqD9Zd7m/"
        "nurLvxu9HD5rUea+J56Gvum4hr913ELAXtGMwBZGEECmRqe+5wmLvPZJMECBSiLAMSDbPsHCG0Dl"
        "S7e/TIFFwFMtXL9R4Wy/WAj9Pzj8QT//cX9AVl/cP2A2OT7LDvg+kDdowI1YZMDyYN2/rI/gPwQh"
        "Q0CkhQG9eQ3ivpoUIL5dpEA9BRqRvXUPB8Bisaw/8l8IwEHRX8C+5ss/FaGqP6s2WEB1rwnAme4h"
        "wP6XYkBTD7Y+SzBMQN2JSUA0TCzA+nB2QHv6yr6VoIY/C3g/wL0GnT8HkIvAKq65v4wc1r8OS7W/"
        "RZ4pQPw3REAZkoW/lyodv107Xz+8Trm/6/LHv6nWqT+q7N0/fwhFP1PFxEDFS7c/CkJRP3sPMT/z"
        "olE/9EecPzWnP8BNsOm+R0gmwIxWHsCaI/q/DlrGv2bsvD+5b6BApp2OPBi3tb8Rgy5AWzrkPX4Z"
        "hD6Fads/a6QPwPsW+D7v1Oy/3c+xvykZMr7xDSVA3YQDwGSHqD6FMN+/HhD+PxZUA8CNxnhA3GxY"
        "wFZW3r/JQai/jJFuQAQuA8A5tJw/Y6iev4G9RL3Xpvy/fRwzQJRj9D/75GhAku3WPq6jkr9Pzck/"
        "LdADwDo+nb/KgQHAq2iVvcrR5T7a5Tm/+csmwAR1/DxCyQdAdHY5QDyXTL9oWNG/RDVMP04Eq79w"
        "MIG+vnXsvmEHVMC/jhLACYRKPuO1v78cRro/d+GNwCjLQz4vxhBA3VLlv9zpDcDQxss/VSMmP6KY"
        "iz/QNHK/oz8QPepGm7+VWxO/yJ17QJZPuD/hOpm+adeUQApSHsBN2g1AOKwHvrFpbL8PIB09467x"
        "P2H9NkA9kEc/tK6sv03SI0D8HjZASN2avz4k9z3fCqA/FTXRvCK1EUC7OCLAj2kHPwUhhD9jxlE/"
        "qIujv/TaCr4vhmC+ojnSP6Ot8j7ggH5AZhQBwGLTA0CPPVZA2R7FwLcIG0Dp2RQ/viPfPnOpyz1X"
        "tT3AdfK+v168jcB35DY/ywf8PjfgjL+YhI9AfeYuvxhHaz8Av4q/dmJgPUGocsC9Fng/qmb7vpRQ"
        "CMAes92/0MoKQNYV4j+A7am+YZ5KwLmx4b+figNAmjXbPwgCI7qjqYc/xAAYwN1AoD6hPXq/QNu2"
        "PuiAYD9F/gZALwipP/juQz+DWo0/XdrHvvpCLr/Y0TDAUxamP/t1OEAXXN0/0VgfvmqY3D+xRTI/"
        "/gIbvlnUvT9B6Ww/gM0HP6lGFsAEHMC/ZEytPdUjir8S7KK9KKSvP+8U07/IzS7Aw1gWv9LTgr/3"
        "9i+/Zp8NP/0/KUAxhBZAqZVVwLcj9T+C3M+/Y9xSQCil0z5S1AS/WnidQC1rzr8G0nu/qKkBQKHA"
        "hz8uM8U9hUCSP6iMqD7UYtY82JHwvgkQfb98U3dAeIAKP9m85T/t4ge/SMr9P+RbHcB09ELAhwpu"
        "v3zMQ0D2EeM+syhtv/dED8CLEpBAVYsGQIFgs79Zphc/v8ojvpvjJ8Cs2RtAvu5vP7yDtr8XKlDA"
        "OWhrP7plLL8MwDpAL6wawNkIbUA/gYq+bIsJQL/MF8DUslC/hs9nwNWfScCHXre9iBsqv5gsZL+9"
        "SBZAhjgaP/HyIz9TGGTAilUmwCo34r+rMUu/3qMnwCfd+j+rd0e+4ovJPzZlcT9zvn6/BK1MPlN9"
        "CT8fQw7AdbYUP3pm70AeuCtAosVgvywJ6r8fnDo/xuqYwLDD278K0QZAePLdv43zB0BpqQbANlZe"
        "QKPNvj9eOwzAzxQLv9HNPMDfa/4/HlSovngCdECGN/K9g+Pgv8PYn70HLZS/H0euP6l7MsCDbo0/"
        "VCS5P1cYkr8kikJAgijBPi6mnL8ir9E/tqDcv3umKkDneR1AIFNkP/K+QL78bKG/soerQIDYB8D2"
        "WKJABjxNQD94kb8wNe4+nbRJP3lh5L8vmJ+/o9jbv0poAMAP8rTArHF5vORdpL/+ZXq/Zvh9P2Ap"
        "4T/O4K6/LhicvorEn8DVxdc/fiojv2mo3z5ic9E+eiS9Pyxqnj/AmXU/d4JYP0Pwsb+UBnI/7xf6"
        "voEE6b8BBlZAydyAQIaeLkCM7ZvAzzijvvqi5r4FBN3AiqymP/5Hsj+Vg3w/KlS7PzriRUApXw3A"
        "4qQewL3vlMAo3eM/2w0CQAkekj5m7FO/UeSNPxVMhsBmoEG/pS8tP3qGUcAHgCq/uBmEP8MaUL+E"
        "jTo/kdxOwEfpH78zGQ5AB9HJP5mlD0D/ucK/IPkHQG2TSECae8M/SrT3Pf4r6b5Jtb6/98QxwDzx"
        "IEBeHS1ADYEJQEFQ7T+IFCa/P3F7OxBPDUDWPRzAu9c4wM8Yk79/kw2/DTaYvx6PXT45Sqo//+DV"
        "v+rF87+EuNk/XWLBP9pVoUDAQlZAZSgIQAQeub/+P8c/CLJmv4xWhL+ZN6C/DZ/eP8l54b85nM8/"
        "qu0NQFg5BkBftrBAzsRkwI8HRMA97b8/TLZBP4/vK0ChAdW/6+hDPTicPj/qLw3ABT6TPsCbhr/a"
        "rGu/zbmAvzmvaL+kx4o9yreXvwozGD5Abqi+yPgZQMHjFsD8E40+De5Svl7XJcD9V45Ay/VdQFFN"
        "V8D4HoXAL10EwGT+qz9BfGQ9PxpNwIV/qr5VuSE+DvnKvtKjwT4aeo5ARfKAvxrz3T8i0V++vIq3"
        "vppHaj/ozMG/bYWfP/63L78cltA+faBKwIKXnr+Pk8c+VFGJv703gD6hmpJAID/uPhVhr7+z4czA"
        "bKabvqQ/AD8NlIW/Z9cCQJYVZL+8Ymq/HhpXv1d4N78wRnU/XQPJP1HAZEAsDd0/Mp4dQFCBRkAs"
        "9ZI+RXEHP38GOUCnuJG/pi2VvwLzj0Bz0KDAAs/ZP/MhGMACoJk+W3JjvZZ2QUDgrTm+jSXYPUm1"
        "7r8G3j5AoRGHvzXPCr/Rj9G/uIVgQP7qor4OmSjAsTPSvwQ5zD+uKR6/Jd6HO1MDmb+cL4I/X7qK"
        "QMfisD8/iZU/HjV7P4lwmT93zQpAhC4qQBKLrT45IyRAOVyYPnXrB78E8CY8JuPGPXmCJT72pM49"
        "ECWQPzpT+D+j3vC/ThWKv/QUiz8UpNc/RNrHv7TfBr8CQvq+0qI6P9rIPz2sqnHAW9nHP0n1XUDD"
        "NqS/L/guQK21WcBUqynAWR+SwCSdgkCrLQnAc5hpPyvGUUDmbEM/XrovwNHooz7NHM+/xUUYwIrQ"
        "LL9FiRy9vFWBPwUpJsD8TKM+918pwN5jRj/IgRHAWDJPP2/OiD4K+Nm/iVoVv1wh3D5X8oRAAfz/"
        "P5BOur85uiW/8/SrP5gQjz+GVCC/MiJgPhDpQz8qVD9ABiDmP9A0a7+adArAl3k5QC+kBL/R9Ku/"
        "EAadP67pWsDkSVbAshykQCzX3b+HoRLAyZ6mv47m1b6NpAbA8I+Jv1oQNMAqkw2/w3PEwHifFD+Q"
        "VRPAm8FkvtuwqsDSL4C9FmgLwHsR6r7XTbu/3V+TP8e2I8BiYhnAFdUuP+mBRD/qbsA/w/JKv0cY"
        "vz7ZX5y/otjQvuWfbkAliQlAUpYFwKULbb/HEii/o6aIwFFk/b2QT6Q/Vz8GQBp7Zz9EFIw+t5Wo"
        "P5RmrkC9eWTAT7S5P7r6cr9KtRW+/0hoQPrvakD8y9O+7ZcbwH/rcT9ouss/6XcFwGBihj+5BkRA"
        "yw9WQC+2ksC6JdM/I+X8P37qnT9Kdt6/rfqkvqLy/r6h/GHA8IQUQEpcwj8Q7o0/3rUOvz/mOz4l"
        "rBTAC5/vPlkunL4GibM/UwkmwG9w1r7Hgrc9tqTmvctNJEChViA+EKmmP+3xIz/gbZg9SYUGQNJR"
        "8r6XZA7A23hBQJyxf78+Su0+uEudv4NMCcAkPas/0sg1P28sK0C3pglA5Hm6vw4gQT9Fuli88YFG"
        "wPC9J8AtXUy96V4rQCAsJL7kJEy/NvWTP9UY3D/EXPU/Y9q2P6m0lD9aqGU+RrsyQPzwDUDvPU7A"
        "UYErvy9r/L8Vi13AHPUDP/IdjL8l2C3AhqCNwNgMW8BD0d2+d19fP2Rv5b+s+6y/UhtevpTASEBa"
        "Lsq/0tYGwHAhDz/stZK+q0YRQMN9qT8xlBq/zKezwAuTFD7VIVDAX8xEv+Ajj70xyc49BiLLP9E2"
        "BD9hT5C//kScvUAdLsDGdp5ASgGAPm4Rz76J2DU/ZUC0vrnKGkA8xErA/26sv61sMj+bPpfAZcHm"
        "vy1c8L5JECi9Cu6svltxyz/IebO+rDDBwFBvYz/QVQi/7uNJwIHSiT+1Oy2+spcBPwNtvj8OPS6/"
        "1L4MwA0ZvT81m0A/+w47QAo3K0CNE1a/P7lLP3iXYsCKilS+RD/UPeFYm7/sr76+XXwEwK6llT94"
        "Ity/X57uv3K0uzzPiZM/6TAJwDOYxD5q23a+tHoFQBNV1D35PBpAGRQcQNbihUBwJHS/tRxWPxhl"
        "Qz9hzQ1AOQzZv/q7NMAAXXM+BhAyQNs8Yz8lT4++9HdtvUaZMD/EjS3AzfYxQP6OjT4E3wrAc8uO"
        "v0hxrD9Tjr4/XH4pPwZB6L/WGArAPvegPwfVNj8yax4/L6WZvzBcMEDTnh6+qZ0HQJ+NHL2s8FJA"
        "rF6Avw7lXj791CE+Cj2tPo4QCMBAsOu/ARPMvyPIGj+J5d29aTYFv7chJb77RytA/CgCvwUud7/h"
        "TiJAfLs8P7qgHz+I9DM/3pJ8wH6p4j/qw1a/8NqXv0MUfD/XiIk+fYcsQPDGy72OC3y/BvKVP6F5"
        "ND/buMW+DpBdP+qOHUC58SbA0PXJvD/RVcBS5AZA1BMiQOfaPUB+yLe+ZTuiP9Pn7b59GwzAabIK"
        "QKJcoD+04BBAhixWwFz9Pj/CEAPAI6qZP8WmbL5Ei5w+w9AbwAHVx75y/g4/KmPAP3IFNb/9qLa/"
        "jhfkP6iOA79+tGTAyLfsvos8XsD9J9M/wZ30vydP2D+e1tE+z5KZv3VhU7+iUkS+6OIWwIUMGL1u"
        "z9A/CNvnP9k5GD4rXBrA5tX8P8AkZMAlF4I+nrUCwH+HAcBilzlAvBACwJ/yxr/kEvA/mydGQLTB"
        "HT9sXvO/XinXPo2rjz9aAc6/VSj+PD7ruz5HaNS/UI1QvndnKr8uL1I+RfQCQA9qCMA1lR+//roY"
        "wPjFUz+lBO4+2TbiP1kgvT+DZ3/AZjIjwLFmdr85Ro3A1NL6v1KYSkActEe/k443v0WMAMCGBZO9"
        "BQq9vSCkxr5Nsiw/0O/zvsoPKb+I5A2/7PpmvgRm/T9NISzAfOkkQMITtD59lB2/sAwdvwRJ9T70"
        "zVVAJ6rZPtBqHsBiEEhAfuikPrBFUcCzyClAZqsDwGwvVcCMW1o/Oq9GvrAJxb9vzDA/dvcIv3bz"
        "DL9OMRLA6rd2wL5xJUAe31Q/RJVbP73m078OzuK/RZ2EvxBej78PzsA/NOdeP3g3Mj/Q4uY+5VCe"
        "P5/QYz6ckdW/Ip7dP26IRb9QBRc/8Ol6v6LdMkCUZoA/zTrkvO3x3T/Rr4VARvbUPmQ1WkCmbwZA"
        "g6K7P0OZ/79596u/0oLAQGICCMCAFxC/6+jJv0ESI0DhZC+/fMA6v/88+j+acAFAti2KvxgzJsDk"
        "gUc/LBAuv7G+AkCkRLu/YDwhP6AG+79MVls/qb+uQL7jisBYFElAqI7Av0KeG0Bkibk/yqzVPvB6"
        "rUDUhm9AdEZYQNYXrz+1yGRAImXoPl55jb78+fi/yhYsPxalN78voCq+eXl4QC+HTcDV5DVAawWn"
        "v+IBVMD0yhrA4TiYvoHjZr+aCb4/j20vwI64Vb87zFw/e2CCQEEQjj93nDM/SLTrP0dkwT/EPds/"
        "plSQQKOGrz8xJOo/NZfAP0gjN8D1a1+/5GyTv2JT8z9zD8Y/ltFHQLEEir7pzJO/QNH4vpve2L7Q"
        "WCFAT77qPvFuA8AkPpO/fcQPwFeyIj9fexdAfhFcv/RhkL8aBRvAol4EQEB+Xz9i2EA/QGcXPoTC"
        "BUBVe9W/0TjSP+WACUAuWQnA5ANmQHzAzT5Vl68/gIKVwB9oEL5Gb0U/1cpVQAgU5T9Z95q+1T+r"
        "viccU79jxTa/95Cpvz/9hj9cN+Y/VqvxP/+jWEAIs3+/s/mawMgJEMDo0A4/xrqSP84Owj+WlIa/"
        "SDcDvzDgwj/1Qxo/qz2Jv+fs+7/a8ec/oorRvypVAkCJoCHA1B76vzMnU0AbF5c/dbDfvn2Bwb8g"
        "+oU/hsaGQHpcI7/VuhdAjakaP+9Zf0BW5/M/GPEpwCRT+j/2KxO/e3smQD0Ej70y3FBAkLsswD/B"
        "qL+bj1a/JckrwC1j/j9iETq/EuFAwJWwLkB99E4/fx8fPQ3y5z60BxNAEhP8wNWqkz+GFjDAnkOk"
        "P1nJV8AfCzFAxBGJQKlj8D+rfIa/uSDCPoJyJ7+c0US/SqWKQHCP3D/JfRLA24H6PQcegT8eD4O/"
        "F1KGP5G6MsCLPK0/MGAPwF0lpD9rHfg/5fjRv/pu8T9Kwfi/EhcuQBLttMBGijA/ArsjwM6doz/T"
        "DB5AFneAv+omQT9+LCDAk2Otv/4OB8C4ko4+S/HzP/7QHUBdMiE9LyGvPT5IN8AvIjxA/92DP6pY"
        "NUBIf1RAtk9OP4KKB0CPnj2/c9OEPqMoZb5F1RnAdv88vF/vP781zLC/9Rx2wPM9br+Q4iBAJsWf"
        "P5J4xb7Cxiq/blLePmcwgL9d1U5Asw55QNChpr85IijAboyKvydErj8GFJk/k8ZsPlykGD0ak8M/"
        "gLiwP20i2z/veek+FSv3PzuzA0D8AtW/85REQNYeOL91CJW/mIXvvfLe6T9sZbu/rLF2QJkWRL9V"
        "RyXAzaVpvRXUaz9xV9Q+lrJMv5o0A8AjH44/eM/APzCkcMBdD4w/5EkLvzrvLD0r8HnAeMwUwPPU"
        "JD+CtqE9ClojQGLmVMCpepa9uef7vheB8L5ElKm/2L69Pkk6Ar1ejom/cQkvQGm9K7+qaqU/a0FW"
        "P0Pm1Tz8+k8/SlHavks9Rr/LHqE/l5IRwA1DcMBdotW/ALbVv9oeA77rirI/5MeQvxBa9r11hLI/"
        "/2rnP4gtJsAuxbXASV8QQKr9sD8weCk/6vqrPKzD8L4wUlhA2IaIP7Is5L556YQ9J5NJvwkrzT1Z"
        "j3Q+aXw3wGnYmEAzCO8/DLlXwNWI3L4DdCFA3ctEQLTw5L+T6Tq+JgweQAwtcb4WBiVASC4hP3uP"
        "tT4yiYi+cEAwQHcyScBix8m/dNAIwCsG1D5KQdI8XdLJP/Iqoj+w5Vg9+1acv1i4lj6IqinAz01a"
        "Px8XCT9CyZA/0nEbQO5udr+K0gu/6dfbv9kDtj9lP+m+rv5fPcBRjT/3U9w+hdnvvw57S7+PYcw/"
        "/5ApwBx9KsCLo/U/daxXP7963r8P7PA/qCiWv2ZsNcCzNb0/FSoMP0n4B8Br8MI/btTFv/H4or+R"
        "zeS+4xVzQBErFEDpMvU/d3nDvxUw4L8+PR5A25KJv45ZtT5wmxA/VHW3PyCmsEDuSyvA3fS8Pz17"
        "mr9yycq/NPtzQBHKG8AEJqe/pF+xP5IJ77+FCfI/HARPQJPOGL5+Q8++b50mQHTLGr+lhIm/DS7e"
        "P1k35j+ui6G+gi88QItSvT/4dPE+znCov1rf5T15zKo/t7BfwCtWDkD83i8/uC5hv2/DVj+60KG+"
        "l5R/P1x+Kz+jwOG/ShJav6FNJL70TmHApiJmwIprYj9gGCW/P60GQE7U/D8pjLQ+bshavhrFMr/+"
        "OoC/s0YMQJrSA0BKbbe/DLvnP0dX5D7tLeE/Lp4QP16apj9SIks/b3s3QJCME0D6NkdA5UdwvW8B"
        "lj6t9/6/Kah5P0BmK0CoRuM+jqWrQMsFejwG3Vu/N20kPgUMJz4yklvAgjykv5zEFcCU1AxAIFRK"
        "vz5daz8cpb0/bHtYP8gVbT76frg/PLeLPsP7a8An8YM+LL7oPZbBE0AOe08/TQMpPxjoyD8KRc0/"
        "A89GPvb2nr/tJ7u/XlAowKAU1L18ORDACJXEvgeShkA/fm0/oXJ+v81G3z6vb3zATyOQQCCIh78S"
        "ili/AKdaPwQ6jr4gft4/a/REPo1mIsBcnwtA5/o9vmt1GkBV8k5ARhkNQPGwor8UOPE/AvaAQF6t"
        "wL98Eta+ctFEvl0xrD+3wU3ADwFXvyggjL/jhMK/8PATPyxUjsBOSmpA4Z+WP4Q+mz/pBY9ABfqZ"
        "v7ogtz9sEq0/mTEIwGAJ6D++ZIBAdzDzvrNLxr4a4SrAhKr6P2DY7L5MAEXA9JKvv47Stb/Fc/o/"
        "6RoEQCVUmr+1lmC/4kguQHnt7T/g2aw+K1cBQG6YFj0QaGq+rpEPP3cYPT8dN0Q/5sU2wJ7ber6C"
        "4ADATiSeP65Ayr9EUKI/GKP4PwZ2wz9ZlB+/3b7Fvnar2D+I3cA/9UkbwAIuxT7YGSrA6uIqvsJK"
        "cMAUbURAeStHQNeSJ0CK18g/lgMBQIPoiL7pxHa+S08cwFWs7T+cZRQ/YbelvwILRD6uU3VAk4NP"
        "PhJHCkAAyCM/qV6LP3At8D9apdq/W4BwQN0bnz8ce64+e1iOwF/vYD9nI5s/bx0mwKKZoj7Bn94/"
        "WAICwPCHVD/AOSVAWXCrvs0STr9okeq/Vt/cPxjJTb6u9lNAgDNEvmUyr0Cn9by/tWULQMh4JT9d"
        "VD1ABMdRQCbTwb4NWI3A2xqzvxhBlr4J8zjAdDZ5Ps7to7/IQkbAiNEmwJWp1L+HiRPA8IErQEdJ"
        "iT+Xpou/jC3zv5GPsT419Da/hWQTPxOVbb/enh9AubgVwPxBPT9uVb2+lVWfPhaVVj/oJZm9BJ6N"
        "v3EwAb99q1q/MTxPv3nWKEBNI+2+w69lwDiGQr+Hf16/vse/PzkQrb5y4Ho+LazpP9yQND8rxoA/"
        "dxbXP5jCPD1YMDpAwiBeQCsbX77B14k/jQJCv/WBN7+Kjsa+BN/qvyVFu798Dtu/WMpfvxGnVMBl"
        "47NA2C77Pg3kKEBvQIE+wGcPP6mntT9fWTC/zk8svghY8z5K4Go/7Pk1QOk0/b+06oS/sO0vwFW7"
        "iz9ED1HAakwWwO1jg8D4K6W/C2qjP/KSBEA9h8C/kvYiQFtgjz6of1o/0q47QJZ8fEBH3pvA4jJH"
        "wDZexT8sMARA8bVqv6FcJEAfSKu+G1JPwPrRCsBwibU+9xQsv3YZBsACiq0/9V1DwFA9f79Viju+"
        "WmggwK7wJD90jdC/ZilmP9etAUBHk8O/gzFmwEZCoD9sYw6/0VoowMd+5L8JPDxASkn4vjLoJz/n"
        "AJI8M1pHQCeFBb1xMYy/oEzLP/yHyr866ui+Oe1+QPReicBa8z2+OG1lwBvWlr9tgEw/Ss53v9f7"
        "Uj/BKkO/FwShvr4b0z8TSSlAzokvwJeMCz+jWUa/XvLuv7Ic4D+BelFAAbw+wBlOJsDcH7G/hjBI"
        "v37TDj5DjhzAiCb/vgQdLz9VODw/uSLdPz/sXLw9+EM/oHtowMQri8CNXXHA8fQMv5CVQcD4m0RA"
        "8PaNPqUKCz4DngFAXicTQHE1fEC6fn5ACD+rP2EZQUD8CLq88dMvP32+m79kriLAIz3qPot+FEAj"
        "a1DAuE9TPy2K+D8DbFo/QHmaPx5AJT/NaVvAldAzwCC5A0A3kX/A+KFRPzbwEr+FxvK/a8jRvqk4"
        "sz+DErk9FxKRvkQgGr87bjK/y6zOv82Vu7+JQoRAsQ8Bv88gXT/59uk/1bzxv/yJlUBkmuc/+L4t"
        "wE9c4T66VTG/rjT6vQjDRD+mMoG/yDipPwcijj83d+K/sglWvkH+tr/5Cr4/Hmu5P+nVQr/+X6O+"
        "9bQ6v0qUqz+r0cc/nE5Tvr71OD/MXEHAcbievxzGG794evU/ypC2P6TxDMBtMxvAVz1ywDk9qL9s"
        "QWs+sNlXQDjbFL8CdN4+HS8sv0JVEkAE2D3AwldmwLoNKMAhHaq/Q3xSQItTIkCfqDPAwjggwIdj"
        "qD/Kfbg9Dtiwv/s2J74rjWw/85SQPoh3iT8DhrLASWf1P7beFcDQN06/PHWFwBeXlcAgeQVAfQQB"
        "wFySUMCMINY/6eHtPpfzncBFbpe92thvwIZqgb98YFe/UWu6PwGX9L52suu/OH55PzZJKD8NHr0/"
        "WRvXP0vHdj+5VopAy5EGQIEQQT9aZA/AG4gBQNsdIsDMxhhAw+5LQEVcMcAw69+/atjNP9iDHsCM"
        "dxS/kPzmv9Sr177RD6E/tCreP3HNnT5+/gnAfcwavwvF77/axdjA9goSPtmSOsBKF9C/47qyv/WL"
        "EUDRZt4/8K8lPxvGQrwLxZ6/qWorwFFTvj/V3Iu9h0cPQFIIAEBHBT2/HQvgv55JN8CWe8e/V5d5"
        "wLDAsL4Hymg/RT+gPz24CUAQCK1AGabXP9MDNsD4qsW/3IYsvuueGL+rMaQ/IZC0v5C0M8D4U/U/"
        "EnWhP85qNMCUCzI+hrnpv0jdzT+NFQ69voYFv2kjJsC49y9Aq1K5P7L0ID5wxnVAiulSP5DqlL9v"
        "kdS/Zjp5v2LGK7wq3bG+FfJsP75qab9PZ+u/SDrLv5+nfr9Dm1O/IGxXvXDUzz5AOkA/WiuJvjVe"
        "bEDy9xtAJKCeP5mmFz7R21i/kIWQvJ7bGr/aMTFAj25hvwVmr7/TcPC+J5CfPtEzBkABFZ+8FlUT"
        "QKFi277dbyG/r4CVP4/8Ub90A8Y+NB0+wOBEqDy8oQtAJq4JQNF5Qr+QLxZAX/Ztv7iUqD8RLUI+"
        "zRJPv3cryb8Pt6Q+n0JZwJBBjj+K3Rc/naMLwAlk6z+VtPe/YK+hPyj/xD4sSKg+PA4tv+FUpEDc"
        "89K/JnuAvgRehT9jNRxAqoUAQBSrNL8tXnDAXPYsv1wmGcDAOiBAnVARQIXLgz8RFEhAiNOUP2SH"
        "lz/epXRAtsvFP44xkL1v9oo/ak4fPxnBpL4dHxY+6fJAv6xMSL/rv1E/wc0SQF/Zr76vJS0/LyD7"
        "vnbcq79x9vG+qSMfQAzhoT8ilU7AY+rGP5FA/D+Q4+U8YpehP2iCYz858tU/6UQXPxbPij9m+7A/"
        "7g83v6WCGz6RpiLADO8EP3bW9T+yvPs/vXIrQKsw678vHbE/bhsRwEbq0T7S6Lo/VuCJP6q9CUAK"
        "2QbA3HjaP4o6M0DYnKFAYIDNvZkwsb5z6NW/UywqPz1Jmb+JMI6/4nlMvYI6ZL71hj89mKZcwHvh"
        "rL9nEw3AfvfBv3ND5D/El26+Q8OUvDr8ej9SunA/RMMAwPmUqr8Jzus/FJ9QPoUTcT/OkppA72kV"
        "QOUx275Ofae9gi+Ev2Eolz/CmWm//bF7QDZJbMCMNBRAGSwjwKKieT+0hNY9H0CXv58ZnT8INJS/"
        "arErv7V71D8i9JU/pZSKQAjXzj+fzgu/gIc6wIDukT9ZJDU+/GmCvja17L/HaNI+eoIjv8pdy7/S"
        "qIBARvO9vyuVXD7FE5i+kkI7QN0NGkBkMOTA4ztzwF7Wab8uRvq/9RSyvt/v7j9E4VzA+wQ9Py1I"
        "xz6BvN8/n6Q4v2H/Bb+9btK+wZk8P79SOsDYMrm/2YpJQBKXvL8P7yS/elpqP94PCcDNAO4/CF0t"
        "vz1td8Adxea/zIcJP0TXC0CzqHc9AoaXwG7vbcBat2m+CaOrvsSZED8qBII/pZOpP7kRKb9zbA1A"
        "3imqvhs4jT/Wrq0/2wcSv2a3F0Bwqly+xgMZP/f6c0BK7BS/kxEmP4FDZ0BS7DFAqcNNQNmXer8D"
        "GCm/rL8uwEK/JL912CXAEjpwwAA/yb2G3z7Av5+CQAxTiL9XQgA/JWpKv3o8DT/FCAO/ekd3vsin"
        "V7/qNBrAHYNRPyCWPb/fgadA4IG3PkIcjkD8OYq+/CKfwNMm1D+Sk8A/GaoZP3u1JkAtJlvA9iaj"
        "v6NQNUC5tCg/mRWYwCxNLsD9HpC/UGBAPnNnT0C4aK6/3qOSvZxQub/1l7A/uHiDv/0uqr8F9UzA"
        "mI6Xv2lzmb6wwRU/vHTiP4ggpr/zO+e/Z++0P+dVsT7PjzrAJvcKwPlt8r82MjRAveqsv51PU75t"
        "P3vAlOwaPjtKBsCEkEs/QdLIv3iKKEBDSWHAKPQeQIT3er/hb6Q7+B+RPqf5+D9rryrAyPHBP5+L"
        "i7/yi09Aa5w+vzgpur9T/ow+qbBoP8zJZb1ovfQ/Y/LxP7VRhL8FbQpAbq17v8Aysr9ZC6g/Kqb3"
        "P3yLND9lspM/YO/zP+KqIr/wwxpA/g+2P+l3iD+tnOU/iVgqvzk8qD95c1q/D36hv8s7MT+zFw8+"
        "Yp8pQO0njj9jAzS//+2gP/nnaMB2zmDA2qMKwMOdxz+q5rU/qPQXv721ir9yNYc/IBwJQNlDEUD8"
        "9Lc/8rqXP892jj5QwFfA9yWWP+9P5j+5jHi/aqUTwPGzoMCo3+c/y4C9v3w9AL9j3uE/zy+hQIJz"
        "FL/u1Y0/rZb/PqKjCEC80qfAOULUP7Kr5b6U+WW+ZQ3cv4gNlr+vhxhAE3wAQM7Jb8DXxw6/oghM"
        "wAem1L9d1fK/HO+0vxv3rL772de/pt7fP+a8vT/FR1w+na6xP3s69T97CPs/ivizPkNNJMC+Vfy/"
        "7HCiQP4h/78f8++/1/enPgBIob8Mykq/TicqwHIRlMDvhNq/eXlAQN4l0T9qhb0/g/dyv9JpcL+z"
        "TLi/+Tj7P24RD0Arcgc/t5QTP0PCIcDndVu+uQ2xP2MsxL9lp5e+f7UdQGZMCz8mk6E/SmMavrf9"
        "1D77XYO+ab2hP4TnJT+MrxG+goyrvnPObT+Uaq2/pS5RwB13dT8LYca+3uNdvPR6J8DMFbU+fnJi"
        "vdPtv74HrbW/hKysP17yQT/Pdk5AZI6TvwfLBr+6NNG/8rNDQK4g47/Y+v0+yQfhPZeOVEA4GQI/"
        "fueGQG1pa0BOH1nA74yvQC8X/z+7KZS9iP0UwHAhIsD4RZA/21eZO4IOFsAWm+0/a9aeP2L8Y0Cl"
        "7CzA/OAtQAvPyr0JodM+o2BOP3N5WECG5sI/bzGYwMCvJT6tdIo+pM8gQLfSmcCeBS9AorG4PuZ3"
        "IcDq9CG/i+hrPkA4lz9qPoE/TKrzvtOx0b8JKwm+wsj+vnb0xr/DcjdA/0/bv/ykekD+Ys8/6Ow9"
        "wDMwnL9fO9a//6P2PzQC7z5Xe5E/Ej4FP/60FUDESkk/4xDdv6BFsz6jL1BAUNoDvy/wHb+puAFA"
        "q4uPQCnHVb1OmV++NBQ9QBpSCcDyerK/VeozQCJtwL8AnQ4/wRsQvlZCuD/fOIJAOpDAP0vQXb6I"
        "Zpq/jAmUwDAeZT5jRvq/IdiKPyZJCECVbBm9NRf/vjeEEr8E/MU/2cQTP5rKjr9dlD9At985wPVD"
        "kT+pfLg+0jGIwEYEjz85z6C/Yoziv+g9lT/BFcy+P5yywG36wr+Rss4/J28XvQHYuT+xJeK/5mMS"
        "QNucMsCgieq+MEeuPoorc0D1r9S+DjyIQMuumMCOmFi/K4UkwCzQQr8qweM+RmVtwM9Htz5b0SjA"
        "/9cvQJoRdsAFM6m+BY3GP3aDW7+E/sU/BuIZPHaipb8wyYq/DdebP99BZT8Nu3A+gHltv6ebhMBi"
        "SQ6/FonFP7Lrlj+p1zM/sNRLQI3VQsCt/w/AbplQQFLPkr/NBOu/AyIVve/zxr6tXTS/h+MTQARR"
        "4z/UDH2/fFCIuxMrpD8mCbg9FKSgv1WzlL93OoU/O8CKwPMZTUCR2KU/8wlBP+KsAkDMNzjAPEh2"
        "vMUqJL4+CqFAoxXYvxfRNkB/7aFAzZXjPS40Xr/lRgPAhXwNwA57u78Q42A9RGRIwPSHTT8OJhDA"
        "1yLLv1VuWsBekwFAfAieQBPcuz0Ue4C/trOBPwneLD+/zAa+x5ypQOWwsT+4p1s/paN3Pq7A8j+8"
        "PWC+p1IrQOwlmz4BOYI+HGREQPwVjj/bNhJAp0lKPPvMK8CWkKJA9F6tP0ielL8TjY8/OagcvzHC"
        "wL/oCylAahCWvyTBk0CcgVJATZ1Cv0pHNcClN4o/E48rQGkVL0DDsRJAzG82PyOfIb/rqMy/BWPb"
        "v3Yepz6ul/096iadP8KO7z9ci1a9s57NPtYhIED4/ys/i4sGP2cTSr5b8ldAY9fwv/2bi70WCv+/"
        "w2mgP8cpsb7FV/a/SaidPoaT+r/pZN8/H3Alvz0WgL/Pq9A/apYhvt7I2D8WPkg/M0yAwOYrgr92"
        "GHlAyaPSvvvG3z9Sgog/H4aMv6LoAsC3FQe/5cM4v9AJVj5X8SRAUB24P1y8pb8Sv5w/FMBnPwzK"
        "jMAzI0lAS4ULQE0i8j+O05W/Nxm7vushTUCYnyVAMyVjQLvQoj8+BiJAE3SUQBWpdT96r1s/2oRg"
        "v8ZbDz8f9YM/xOu6QLUvv7+cI+c+GbEJQFaWWcA8ohM/"
    ), dtype=np.float32).copy().reshape([1, 3, 32, 32])


def _ref_pytorch(mb, x):
    import torch, onnx2torch
    m = onnx2torch.convert(onnx.load_from_string(mb)).eval()
    with torch.no_grad():
        out = m(torch.from_numpy(x))
    if isinstance(out, (list, tuple)): out = out[0]
    return out.detach().cpu().float().numpy().ravel()


def _rel_l2(a, b):
    a = a.astype(np.float64).ravel(); b = b.astype(np.float64).ravel()
    return float(np.linalg.norm(a - b) / max(np.linalg.norm(a), np.linalg.norm(b), 1e-12))


def _run(backend, mb, x):
    try:
        if backend == "onnxruntime":
            import onnxruntime as ort
            opts = ort.SessionOptions()
            opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
            sess = ort.InferenceSession(mb, opts, providers=["CPUExecutionProvider"])
            return np.asarray(sess.run(None, {INPUT_NAME: x})[0]).ravel(), None
        if backend == "openvino":
            import openvino as ov
            core = ov.Core()
            compiled = core.compile_model(core.read_model(io.BytesIO(mb)), "CPU")
            out = compiled([x])
            return np.asarray(list(out.values())[0]).ravel(), None
        if backend in ("tensorflow", "xla"):
            sys.path.insert(0, "/home/binduan/myspace/trion")
            from trion.oracle.tf_backend import TFBackend
            r = TFBackend().run(onnx.load_from_string(mb), {INPUT_NAME: x}, optimized=(backend == "xla"))
            return (r.output.ravel(), None) if r.output is not None else (None, r.error or "fail")
        if backend == "tvm":
            sys.path.insert(0, "/home/binduan/myspace/trion")
            from trion.oracle.tvm_backend import TVMBackend
            r = TVMBackend().run(onnx.load_from_string(mb), {INPUT_NAME: x}, optimized=True)
            return (r.output.ravel(), None) if r.output is not None else (None, r.error or "fail")
        if backend == "torchscript":
            import torch, onnx2torch
            m = onnx2torch.convert(onnx.load_from_string(mb)).eval()
            t = torch.from_numpy(x)
            scripted = torch.jit.trace(m, (t,))
            frozen = torch.jit.optimize_for_inference(torch.jit.freeze(scripted))
            with torch.no_grad():
                out = frozen(t)
            if isinstance(out, (list, tuple)): out = out[0]
            return out.detach().numpy().ravel(), None
        if backend == "torch_compile":
            import torch, onnx2torch
            m = onnx2torch.convert(onnx.load_from_string(mb)).eval()
            compiled = torch.compile(m, mode="reduce-overhead", fullgraph=False)
            with torch.no_grad():
                out = compiled(torch.from_numpy(x))
            if isinstance(out, (list, tuple)): out = out[0]
            return out.detach().numpy().ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:100]}"
    return None, "no driver"


def main():
    mb = build_model()
    x = _input()
    try:
        ref = _ref_pytorch(mb, x)
    except Exception as e:
        print(f"ref failed: {e}"); return 2
    any_bug = False
    print(f"Bug ID: minimized")
    print(f"Backends: {BACKENDS}  Tolerance: {TOLERANCE}")
    for b in BACKENDS:
        out, err = _run(b, mb, x)
        if err:
            print(f"  [{b}] CRASH: {err}   -> BUG REPRODUCED")
            any_bug = True; continue
        d = _rel_l2(out, ref)
        verdict = "REPRODUCED" if d > TOLERANCE else "ok"
        print(f"  [{b}] rel_L2 vs pytorch_ref = {d:.4e}   -> {verdict}")
        if d > TOLERANCE: any_bug = True
    PASS = not any_bug
    print(f"PASS={PASS}")
    if not PASS:
        print("BUG REPRODUCED"); return 0
    print("not reproduced"); return 1


if __name__ == "__main__":
    sys.exit(main())
