#!/usr/bin/env python3
"""
Bug ID     : bug_000210
Source     : Trion campaign v3 (fuzzing)
Compiler   : tensorflow, xla
Patterns   : RMSNorm + Resize align_corners
Root cause : Transpose + RMSNorm + MatMul + Resize(linear,align_corners)
Tolerance  : 0.1

Exit 0 = BUG REPRODUCED  |  Exit 1 = not reproduced  |  Exit 2 = missing deps
"""
from __future__ import annotations
import base64, io, os, sys
import numpy as np

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")

try:
    import onnx
    from onnx import helper, numpy_helper, TensorProto
except ImportError as e:
    print(f"missing deps: {e}"); sys.exit(2)

TOLERANCE = 0.1
BACKENDS = ['tensorflow', 'xla']
OPSET = 17
IR_VERSION = 8
INPUT_NAME = 'model_input'
OUTPUT_NAME = 'n400_resi_out'
INPUT_SHAPE = [1, 3, 32, 32]
OUTPUT_SHAPE = [1, 3, 64, 64]

# ------------------------------------------------------------------
# Initializers (weights/constants from the fuzzer-discovered model)
# ------------------------------------------------------------------
def _inits() -> list:
    i_0 = numpy_helper.from_array(np.array([9.999999974752427e-07], dtype=np.float32).reshape([1]), 'n100_rms_eps')
    i_1 = numpy_helper.from_array(np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype=np.float32).reshape([32]), 'n100_rms_g')
    i_2 = numpy_helper.from_array(np.frombuffer(base64.b64decode(
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    ), dtype=np.float32).copy().reshape([1, 3, 32, 32]), 'n200_mze_zeros')
    i_3 = numpy_helper.from_array(np.frombuffer(base64.b64decode(
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
        "ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9m"
        "ZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zm"
        "hj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaG"
        "P2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/ZmaGP2Zmhj9mZoY/"
    ), dtype=np.float32).copy().reshape([1, 3, 32, 32]), 'n200_mze_scale')
    i_4 = numpy_helper.from_array(np.frombuffer(base64.b64decode(
        "uEFyvmXtsTzV89o+tC4OPSdpCT+aSdA+JLPTPcAxKL41r9s+Dl7gPTiEqr75KpW8desXPfFR4L0R"
        "wkG+56LTvVHygD2XdHU+CrMWvkaKE7+7pns+W77lPUBFQ74YvWC+bTu3PjgvAr9gLY49lIKFPsdU"
        "1T3l5um8wlUGPr69Ib74vIq+5lmrvnjSEj1kKsi+gcpkPsElr77kFKc9zHWavq+cdLzsHMO9oiSO"
        "PmF39j5/ns28RswjPuK0fr0ecy8+qKDfPQUHt73EujE+4/5GPgSxMT5Y/b89khiIPtKEkT3yxHG+"
        "MZw5vrLzdL2ltds8PxcVv9rNPL7reoo9KtowPUOrUr7oKJa93zlcPtMmFT5TMTw+jxljPjuZpj4c"
        "cle+fPT9vfQrVb6gLyS/c9ToPUO5Hj7DKpm8jfU3vnvB+j3zVcK+AjWUvv8Ghr6tyBq+HD4hPwqw"
        "nT7dqBs+O2Q2vsJGLD46qIq9h2fivcKDkL3Zrl6+3He2Pji7Lb7DmJU+UUHGPvyksD0TgFI+E9Ee"
        "vm0sI75d1ww/9RYhv7TvhT2DTjA+l+mUvcWvlT4CbCY9OAm5PitXT7zpt8c7WQOcvdOpBr6bbcc+"
        "OvcavrX9yD5itzI+gWRxvIRABj5r4IC9/T7dPUcIgb6MXKY+mlq2PncnhDxXZwI9OfYSPGoiqr5i"
        "IKY+ueFqvrefnzw7YYO8vOhIvtSQOz6pyKm+iSeUPcnigD0VtRS+dYY8PrUjfr55+MQ8XyePPply"
        "vL1cAeS9baQavsBV1L2Qs8g+eRaOPjozIj9oWtm+d/QqPfZ0tr0WmGu9jvtQvnLifL2vs2q8Vkkv"
        "Pqz+Iz7XIBI/qOUcPu2ggD7Lowm9XhGQvU0YGj2QGBE9RpyyvgtiID6dI7K9Ou0MPvdhHz6lEnS9"
        "MESCvoK4Y77vZpG94gu7PpW4HT6RYP0+RRlzu9h8Xr0NKAU+CNLRvewYK75gzRI+0v27vcGyXz04"
        "S42+/E5cPVXwAL6WgMM9xNDrPHUJTr8P3369lxCTPXmkiTw1DyE+7BhivRvfWr4J8pY+kAIEOkfH"
        "Br2ZYUE+4idzPTsHHD0ltVQ9ZdSkPKTFR77fFj8+kuQePLW0nb0YM3c+BtzcvX292r4+lSs9Vkvt"
        "voITrD6/JSe+2zQ4PmA2I75GR2Y+NtqjPoMJ/L7L0uI83/lTPhwy+z2+sIG9jfTaPlG3NTxkVJK9"
        "4r+XPZlJ2D73rWa+JSVdPf/IP77LPUg+8udsPtAs7r4fzUo+sS/NvUp4RT5ClLe+gyxsPEaVDz5h"
        "HAK/G4VpvsL7ZT4prjm+9tXmvRU8Hb4BUx6+TTp9PeekrT4xqw2+4AP8PZJdOz5tG/w8qJqKPcOB"
        "/L65vZQ9YTEFP2qVoD7DNCI+QDHJPiOClT2c3ZE9EIQLvzequT7Hwi6/dZLJvfTsIj7l7ic+A7nE"
        "PjxXH739D1u+LSoavRl6rj0GIrS9CmiIPkE3mz6qqtQ+lmx7vq40nr10aCO+3eHTvc3ABD98Eqw9"
        "y5aDPtL/Ez6FdqA+rN2APfA0pb5P6YA+Vq+1vTqCc719rTe+FSKKPsFKID5Qepu+XQw6vbRPnj70"
        "6Ko+0Gq+vnPAlT6xmYa9Y1SCPfyw9b3JoJs94p/dO+Lolz01ORG+bGjJvpBLj75xYzw9OqCZPcx5"
        "xD3TjSO+xLHYvoFJiL4RTbE+jJQwPnfmrr1YmsI9VO9Rug3U+7wD8Mw9WxiJvess7D1DArK+XWOl"
        "PVaqqD6+MaS+loq7vQOZrbx8XZY+kKSUPKbcKb4/5jQ+9Y2SvjfijL74TS88srYzPtQznL7Y30q9"
        "xrJMPu5n1r5UH0W7aX2QvcUx777quKy85MGTPREF3j7iFkc9nLdrPnmM2j7Soac+mVRkvt63or1u"
        "u6G+s7NlvnH4b759bdq+4JeNPnbdN72aKyS+/6wpvch0Dr501lw+HVTuO9PvYz4pNYG+d1rKvLze"
        "Nb4rW8Y+K5+BPpQgrbyfWms93LaLPV/jgr3n6Q8/T76FvJGEDb27k5e9QIqkvd3djbzUjzw8He9b"
        "PkzLqz1lGZy9/40xvl111b52Nhq7zxcKvud1hz52oMG+hQnMPVRCHL9uZ8o+ZxtevnJfir2XyxU+"
        "q90MP7mepb0j1SO/PVOGPi+ndb1K1pq+K+leO/faBr3lADI9R4d8vqQhvr4iAGY+H6VcvpCDdz7+"
        "zH4852+kvSDTBr5kE+K+g34qvGrGrr2xaFK+/6MhPgtDDT4DSYU+k9d3PZXKqL11oS6+eDgSvlgx"
        "qr4JGgI+xyJIvnRnEL7UPqI+CdZ0PoRwPr0MZpc+Klv4PYu55j1kjCE/IxEHP+1hmz2m5ZS+eLfD"
        "vj98gD7ryCm943zYPntHJz5Rirq9IZTQPbjQ6zz0usI+gyqEvmuYbr7Mtxw+T4ervcPniz5iF9u+"
        "4J3rvJddIL54gB6+Mjk0vvoo8z64MC0/FZCgPgCGDT6wXZG+a26ovgFeeT56cXq9hWETvuWPnr7s"
        "w/O+nFeUPRYRcL2y5Z89zkksPiRleL2PPK69ECxtPPu5gr2lx8M9bH/uOyHqHz5TsLM9BKgUvvuO"
        "Oj585VU+svdsvluhzj6rSuw9Vn+FukGTBz+y+CI+ftyWvlJTqj3eWRG+YZe3vhHAdT5BEB4+J7EG"
        "vT/ZHb9P2lG9MMTmvdwgkL6rApe9PJ0NPyrSoz6GOcW+Ruqsvf+0pr02gSe9ljTyvpwvhD6ExJ2+"
        "JyyHPtH9gz2j18W94gpuvW0e7j4jdtw+pOQFPnIpnbyydU4/oIZDvi+11b3IN48+79q8Pu5zOT3H"
        "2oc+pG6uPdPSfb1Yu549uzs9vxiUmj4GnhG97kmcPh+4oD0Nigw+6VEYPkwDkr6Ap6w9ThDaPcGG"
        "zD42r6E9l02ePCy5qD4xfBE89PitPcWxcT7O8ui+wSdLPTqaWzslIAC+3KyyvghAiL296ok9zdTL"
        "vUBh+T1axIy+I2hUPgDSkz2AQ90+JKKbviTz8D7HxUM+eSVHPvEYrz5SvT6+spcRPvONIL65NN09"
        "bRyKvqZ8pb6zcNq+96GDvp6SGb49hHe+bbECPfJ5pr2XOS89EJ9GvCRFhz2g0Q6+AG1BPbJqQj6q"
        "mVM9C6IWPpH7xj0slWI+du2Zvh6VVz6zQSe9r40rvc/quL3+SaS7k0wTPjeRGz1zRX2+HsXgPi4N"
        "1b5GJS++5E4kvcHApz4bFfa8O4AZPgdkhL4wNzS+W6tNvpLYHz6JXXg+baVXPWiwiL5z4Co+d73B"
        "vU6xk76ZRWW+zN6ePuA8Z73hMo++iVK3PiccPrwyJ5O+/OIrP+w7gT5mIzw7bULmvdKIg70SIMQ+"
        "Sh+mPb7+nD5cQJM8H6vxPZ3kp723AF++Wy4BvXGq0D5ty7U9MnEbv5mpRz4Y+p0+QJsUve0kuD5E"
        "xYQ+qN8wvYBPvD1WoC+9hSlovsaUiL7LvZ4+zF0rPtKS/L0Fu3++yUDjPd2w87z2MHo+tiuSPqje"
        "KT6caYM+NWeJPdErlT0KGRI/9f1huwrjXz4egIW9ayi8PZGCHb4Uj7E9/6ZnPvwJmru80Go+K6iP"
        "vjGAZz7GlhI9WdCOPRgYe75ukIg+FLNavI0npD7iOBq+hW+Zvvvqvz4ithS+d7t0PoRfDT4sDPY+"
        "3rmKvu7ADb7G1Ow+Yx9IPj9QrTzM2Xy+MgbkurljA76KUN0+GyGGvk4XG76ANGi+C0QPPuEKtj7p"
        "a3A+ldp0vZLjhTyLiZ4+ZQGePjd8kz4Pp2A+TcOyvYlEoz6Ae7I9185gvTACEr7uuTS+h9qMvj7J"
        "kD574ry8zZwtPLbtqT5QNJW+SaatPUIus739CgQ+mP4Fv6xy6j3fomQ+7c1uPhxZRb5Z7Ba+UOwD"
        "vjhEsr6rga49nYf2vlHsJ74+Rc++KRUxP81Opb7tVq29/mYFPufqlb6Dk0G+gtUDPgZ48D51Bwu/"
        "ZvMdvlgYi75EQcQ9i0skveXSebx9KkI/qY2ePq4rUj0ILE0+FAy5PQ7qdj4dZHg+E5FMvj6RIj5n"
        "W24+ntIqPkiKmz2m6nU+3ofJPszQfj1fn1g+bcKrPozKnz1sJdg8Qw+5PvS0rj2k1Wk+Sr4svehO"
        "9j4FOWO+x1wVv4EPvj4NMhc+xhxTPROl1j0Y8Js+6rGMPLE/lT3W6IC93a8FP3MGaT1lv7A9r6GA"
        "vlBcxT5ntIm+ygGhvQFB/j0Z+ts+/fFmvXMGdD46ICO+MZaVPeFHGr2miti9z+JLPae6Eb0YC0C+"
        "fZeKPSs23D5GPvU9gGwSvjgdkj5Lyba9kVa/Pt5nh76QVYi994G2PRcDEb5VhaS9SpBTvYLmgr4W"
        "YvC9Eo9JPveWADus6dE92PD2vl/jwb1hVvQ9KchOPq9Jer5/0gk+0SoRv1CvA74OV8E9nJCoPQq+"
        "X7xFkAS+J1ZgPnrRVr7dlQ6+nosxPij9B77ztIs+nEtqvkDlDL7ydU073TAQPs6FIj6IZns+QXum"
        "Pd+Rgr4fGWs+FVuEPvSuGz5KPs08REGKPlR+gz5tJ64+KbgZPrczZz7KUvu8SFyaPYJXbD2Hss69"
        "KVA+Pu+gzL7JDMO9basFPox2AD88qL+9tysHvhhDO76ptrC99gCBPgppvr6MQeA83QGWPttqW70F"
        "kLO9mt4Nvp36Sj51n8q9416XvUnC4728BwU+NShpvpm8Sb7ERWi+vEfGPEHqFr64Czk+S6RhPhT/"
        "rL4TL/K+U2fmPmh/sb4CtQq+CpKdPZbP+j5LfJ++iBJWPn+zMzzKmRG+nwk+Pd4oLj5Ks66++m7a"
        "vLK9Bj4rM+W+GKGLPkx5Ir6e0O68FSCfvlK7ej07sk64HVNrvtKeiz5UYr8+NZiRviXfZzoCf4u+"
        "ZXgKPvTtrT6OfLM+sP6ovvpfPD5H9p87a25yPVLyszx9Tmq+P5mkvgkOhL25lqu+q38HPrcNNr/g"
        "Ndi+PZkZvrtUMz7yZ0m9mQ6UPre3T728+JE9SfKTPvWhJb4wkh++mJonvq3LT76RcCu+CQYgPf5C"
        "uT5NIc0+fAkoPRNAc759pgC/77ktPh1Fiz431bO9PIZlPuP9Sb5zYmY+XUhFPqOEuz65C6U9SPMf"
        "Por9Wr6mFSi+db7gPqx+CzzbpZE+3uS2vhyrcb3momG+1B8JPnOVHD78IHo+3y81PfZqGz7BoGi+"
        "SO/QPZJ47L0tjLu+VXKGPjxDGT3PIAg+3KOMveWIMLwHWmG+0s8hPiY6hD5KhDA+GWVgO9Oorj4R"
        "5Y8+dDzePdjy1L7LkB0+asd1vjK6JT4aP5q+6YGLvXVKvj6WjGo+1xu5PixwubtvQO4+1UYwPocS"
        "mb5Tchi/gRgeOx+yhr5NSDq/44loPiF5pr5Hmpi+HInFPn4lwT58Hp6+SUXdPIN5xrs8hmY+B5lA"
        "vvIvnL3b5OI96boqvnYPmz6fa/w+Dobiuy+x4D4/sOE+X6abvN1ivT7ikH0+jGbAPg=="
    ), dtype=np.float32).copy().reshape([1, 1, 32, 32]), 'n300_mm4d_w')
    i_5 = numpy_helper.from_array(np.array([], dtype=np.float32).reshape([0]), 'n400_resi_roi')
    i_6 = numpy_helper.from_array(np.array([1.0, 1.0, 2.0, 2.0], dtype=np.float32).reshape([4]), 'n400_resi_scales')
    return [i_0, i_1, i_2, i_3, i_4, i_5, i_6]

# ------------------------------------------------------------------
# Graph nodes
# ------------------------------------------------------------------
def _nodes() -> list:
    return [
        helper.make_node('Transpose', inputs=['model_input'], outputs=['n0_ths_out'], perm=[0, 1, 3, 2]),
        helper.make_node('Mul', inputs=['n0_ths_out', 'n0_ths_out'], outputs=['n100_rms_sq']),
        helper.make_node('ReduceMean', inputs=['n100_rms_sq'], outputs=['n100_rms_mean'], axes=[-1], keepdims=1),
        helper.make_node('Add', inputs=['n100_rms_mean', 'n100_rms_eps'], outputs=['n100_rms_add']),
        helper.make_node('Sqrt', inputs=['n100_rms_add'], outputs=['n100_rms_sqrt']),
        helper.make_node('Div', inputs=['n0_ths_out', 'n100_rms_sqrt'], outputs=['n100_rms_sc']),
        helper.make_node('Mul', inputs=['n100_rms_sc', 'n100_rms_g'], outputs=['n100_rms_out']),
        helper.make_node('Mul', inputs=['n100_rms_out', 'n200_mze_zeros'], outputs=['n200_mze_mz']),
        helper.make_node('Add', inputs=['n200_mze_mz', 'n200_mze_scale'], outputs=['n200_mze_out']),
        helper.make_node('MatMul', inputs=['n200_mze_out', 'n300_mm4d_w'], outputs=['n300_mm4d_out']),
        helper.make_node('Resize', inputs=['n300_mm4d_out', 'n400_resi_roi', 'n400_resi_scales'], outputs=['n400_resi_out'], coordinate_transformation_mode='align_corners', mode='linear'),
    ]

# ------------------------------------------------------------------
# Model builder
# ------------------------------------------------------------------
def build_model() -> bytes:
    inputs_info  = [helper.make_tensor_value_info(INPUT_NAME, TensorProto.FLOAT, INPUT_SHAPE)]
    outputs_info = [helper.make_tensor_value_info(OUTPUT_NAME, TensorProto.FLOAT, OUTPUT_SHAPE)]
    graph = helper.make_graph(_nodes(), "bug_000210", inputs_info, outputs_info, initializer=_inits())
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", OPSET)])
    model.ir_version = IR_VERSION
    return model.SerializeToString()


# ------------------------------------------------------------------
# Input tensor (from the failing fuzzer sample)
# ------------------------------------------------------------------
def _input() -> np.ndarray:
    return np.frombuffer(base64.b64decode(
        "5G4kvwx53r8PZqA/xubTPXcoib+MzwM+/S2Cv0ulCT5sMsG+uyfIv8tdaz8XVRO/Z1z3PiUVRr/g"
        "FxLAncuBP8ZC3b5wugI+awQIP0tYyj/Ff7Q9/uJlPoZFlD/O/tg/74FGPyVyez/qJAs/8BrTvsN7"
        "xj+q0IS+YzvKPyXGG78cPRi/auUGvlhZ0r/0HBxA0oaav+jmBL+IEhE/6Ji1PsXIHr8gbfI/9K8t"
        "v8dh3jqL856/LyUMvydSgr+/0oy/NNZTP3qBHD6Tmyy/VcWvvaQoK79S4Ku/k3ENv5cNAMB2fIM/"
        "hH++vy/0t79Tl+0/FP4DvnoIKr8VFW49X20QP3cEJD+QQYu+R7h3P/uhuz9KvWk/XcOevgkWgr8K"
        "kJ4/k4+lPzntmT+BsCe8GXe+P6ZLl780O8++y27OvhPwWT4PdM6/rgYFP8E/yb65smU+2r1IPwVG"
        "WT9niJU+dEwrvSg75z6JtpI/nMPuvxd/Nz/3eOc/xz08PW/ES7/reww9a/vIvzdSvr68Rua9Gb0m"
        "Pxe+4T4CiTg/85nuPx9cJD+owdQ/YQbFPpC1IMAQTSO+wam2P6BAgT9iEDU/2kigPy1ITL+6oKW/"
        "4XPfPnztM7/9Wru/K5NgPyN7cT7dWpK/SaXkvjeLc74PO8k+FMtWv4pfYD5pZ6o+URt+v/Q0DL5U"
        "vTVAXmTevMZimj4sfR+/Wz1PP8JIhr9CW2o/QjDhvnQYPz9oYTu/3BNOv6fmNT9/dJ++8B5gPpt1"
        "Ej1oEKk/q4HfPmhe6L9zn+88tp2nvpMcPz+C78k+UtOrPov94D6S8s4/HS9EPnEhij/KykY/G/rW"
        "v38CIb6i8N0+znr1Pi9xAD5QcHs/c2Sqv6S8LT+QYwo/ZpwMP08Loj+NOMk9/ZyWPTp4Zb+kGui/"
        "buzuv6F0OL7wcVk/2niEPo390T+4MvW+XkSevi0jpb4zgzI//H7LPuznBD8MGv0+K7pHP+P6eT8k"
        "REe/yuUEP9u99T92V8C+8O5XPkCNED9ZNhe9jh+7P7fnjb6+Xri/9sX2PgwK3b63ub08ClPVPgbA"
        "Eb1QLRO/z/GGvgVa9L7WYTS/d7Q0vwc6GL/U27G8NRgZvogLij2Y9bS+MzUTv1BFXD+ef+c/sV53"
        "P8gGWT95Upg8rBnzPpkKo7pIRbC+h32sPtk+i7wOOE4/zOQAQB99oD5+GqU/V9M8PUAip7/pxem8"
        "fzy6P2tXw761NYk/BE0fP7XYKr+ht8E+32Ziv3F9IL+kye88RAs6vw7fib4RXaY+gi8eP+0Mdz+a"
        "pApA9K60PyQt7T4jogNA893WvjgdSb7frbu/hA3EvSf9Db96enC+r0Wpv/TmNr+uNe48h6AXv7DX"
        "rT/pWX08h5iCv9telT6CP+w+W4uLPwWqcL70f82/6STFvyWqnT/QUA8/D3fSP84xk74nMeA/Ke1A"
        "P1liJb+WNHk/B1+WvlhquT5PcM8+Ask1v/cJnL+eMIC+obPEvrJndD/aXmy//gsAPzIw9b4Cih6+"
        "q+Lgv+zexb+dSr++BVKDPtLLhD/UjZo/6zvdvs/i6L9D/HW8P/gpPiovjr8vdIG/5t0uwDNbDT9n"
        "Xds+kIKNv8kb2L7MRsq+zJF/v6UQjD9twp8+E/JJv5z8AD8Xk/i+3uWdP2b3OL+AK4o/amAtPuVR"
        "6b+q2xQ/3EIdP5EzPL8wkka/BRPuvz/o+L9HgZo/p6cWP+iECj8Vs64+nNGavl2xGz/15DG/5m/q"
        "viSZgj+hd7k/XIfRPXo2Hr/Bfi8/mbQ5vhBbcr+z6wy9xMJrv1VINb+ZtLU+MufQP9eGGb+UZYq9"
        "eOBBP10Hfz7AEjo9njLXvv7OXT+rFAdAAuiwvr0SVD/Sxb2/t7SsP3qLwryETqc/27UfvSiIHD/g"
        "Hjk/++cLv5nwzj6gbnQ/B62YPy/jIr8IETS/6gsQQNHAxb+Qn9I+eoMovzV1M74K7rC81aFbPwAO"
        "Ez8GXq09VIMbvxyJQT8Nj4E/2aeXPvxD+D7uGbA/jASKP+F5gL9AJGo/aSNJPn5Nvj9GDBk/jeSK"
        "v+cYUz1k/1u/EkGMPiSEXb/55p4/sKGrP5uK6D7Tac086ImnPqPYlb68k+G/aUayvt/psD4nq8A+"
        "aWpfvztd27/ZpG4+sGUbv5Y3RLyeLue+9Mmnvudm0b+leY+/iOG9v53GQj9W0zFAUyC0PuKXp79r"
        "9oi/gU0kv1RnRj87L5g/LwXhPtTtGj/hRgfALcv6P+suXL8okQI+KZ69PrPxNT9CY8c/tidWv2sc"
        "I0Borge/f9D9PxVRq78aRQM/hzhIvxG0E7/FJUy+SMcFwKz1PD9tr3a/aHG5Ps/41j+t6Mm/Fi3C"
        "PznnIr9oZvc9JTMlv+R7gr9R+iy/CihrPxdHGb8t+yM/sKSgv0qdjb8gCZi/GbQgvl39cb8XoE4/"
        "NahQP7CRyT+Pw5i9+hSZPtOc1795pAS/owwVv8qt5j7HSXA+u8ZCPvYQWb4Ikh6/MuyNP2dV3z4e"
        "lOU/xJW4ve0knL61FvI+uNfSv7411b+qSxE8ExRvP4Hrzz4XLJy9qGdxP33YBz+0rAfA8JPKPlmE"
        "j78/38I/N0vQvyQ38z2/n4+92CUcPy9PCcCZgku+lVIEQB44gD7tuqu+i4M5PzMMlb9G8gC/T76O"
        "vwpHAj9834y/8CMXwNidbL4DERXAzAPUP5x7IT/UF8+/DGGfv90qGb7NKCw/O6OqPxNDE7/LiIi/"
        "x0CIPq9qi70DVOQ+4zDWPgLMx73gurK/pN+qPxxZCr/EWhM/YNRKPo7R1D+fWpi/NzGrvnS+Nz5f"
        "ORU/ZqVEvbcc0D8goYW/j5pJP5P3DcDb6xm/nj6xv7VYvD/Yj9C/skUTwNTdfb5b3HA+VatQv9YU"
        "7r5ycc4/DnyQvhq/5b1y18Y/h/GxP9rxLD0CYwC/LTicP8A0nz9SgF2/tbA3v2zCOD9m7ca/SxXI"
        "vja27b86s4W/rDvsPbOrwT99Epm+r5+yv3rMbD/TEkS+rYd2P1KV178MKVA/qUTBPx0ofj7VTb87"
        "k2b2PWNxAUDpocG8bXOxv61eKj4WeD6+kzIrP66NEMDV0jo/mBuav9Y5h78+g88+FmDSPic5h78n"
        "jGu+H76YPv6tDb9OEtG+4RVsv/ld5T6pvG6/IfCqvjv98T9u57M/lzTVP7fzvb70mEc/Sd+Mv45E"
        "0j+zED0/rhCUPzkN4L/KMvG+Eq1mv8lc7j5Vrtu+gyTKvi4ZxT6jnaE/2yzlviTrYj/Nq7y/7n9o"
        "P1Ow8z5ATrq/zaSMP92yhD+qp5o+pHgDv2uxqL98wz8/xnjbvhzL+j8I7hU/LHaBPS7B2b01wBm/"
        "XBk0v44M277rlo8+I9YmwAWv3z7Yqly/h0Fnvs89rb8+c0c9kV6HP4JjKr+/gs6+1BcKvxjfCL+L"
        "MdS/uEWAPlA2LD/WHjC+E6z8vmbW47/ALpS/Q/8kwHypXD5/Wta/x/CxvtHM6T6t9x+/tn03PVrP"
        "1j8Ch+E8QgQjv02nhb+Zdlq/NefeP64Asj+HXC0/EAODv3oByr/LNsC/4cRwPwoWNj9b/OI+/CY3"
        "viy4GL9nhna/haAKvj4Rcr/Ffle/hB3ov7RLp77EaMU+TFR2PCrXT77sOVW/pNQkvx033r3savS+"
        "l3pgPqJTkL+gV4y/58kWvyuR/z6DWAe/joRuvwqwk7/8FTA/RuQPv6R6tz9M8ha+RViGvRgAFb+K"
        "7GK/tLC3vqldlD3wJGi++KzOv/PnQb1YEQs/xPE2v43iNL6Qtsg+YU+wvm+GfL/KD3A+cB/SP5uu"
        "Bb4B0JC+QxKeP6tuJL4wG4o+L3EKP29n9z5uux7A4aq2vzEGXz4ljN0/ORjSP7dji78wXjU/WPhT"
        "Pntuor5nzGQ/DlD8vWZpBz2eVhQ+wkwAvm6GBsBEl4e+tWHLPehJx75LKAu/h314P4DFFL8xh1O/"
        "1KeSPvDSc7+OLUs+pgZAP4RLvb5bE84/3BcNvVU3zz/aJLk/v9R7vmhbqb7oGdW+Ywt3v2ijGECz"
        "CCU+0X4uv7Rflr8ilGO/tDMVPlTgbL8WfAA+2JSSv0a1kDw8VMc/2wnqvz8z2z8hPq+/Q80avwNY"
        "Oj8KTpY/qMEgP1boU7/DuY+/cGrRv4V/D74PP5E/TY1svxgE1T9RwG6/aWAZPv/2PD/Ibpw6Bft4"
        "v6YDgL+c2fk+EaUJv/8zpj0yiDq/+stnPxUkDz91RLM+gjAuP31QOL9/cY6/99uFP8NMar+eTzA/"
        "Fcn1PtyWJD/Yc24/YOdRv6RFBj9RkU+/XGWpP7+lQr8+sVw/TzCnv4oOm74X59O9lkkgP/5MMj/t"
        "Uw0/pgQQv1LEdL9RV7s+LlhDPV93wD97Fc4/qixSPyxRkT7T9S4/u/ENPqGKoD41XwC/nJ80v/Gk"
        "cT+gBQs/O17FvxbIqj//yw4/l8wSP+dyKT6+PrA+ZD2KP1MbNL/2+Cm/EE2bPp/bMj/MzzG/tNt9"
        "v8QYKb8N27o+Q+eeP6QV5z9CsTY/VLwGP2Rurj9iJ4G+cNudP1QvUT7cUXw/A3A5PwK+rz20BEs/"
        "WcCkPyWbK78ggkk/VmExP4Ws+b5HmZs/myQ1P1zpdz8w1RG/v8K4v+/2AcDdhog+WSxpP/mM6j9R"
        "SjI+IMeavsmnv77gA0o/GzjVPshXFz+FjUo/gNRfQDKWS78tzyo+6BRlP14UDkAxV+6/Gloqvgwf"
        "lD/O/3m/Kku7vr/nrD6prv49Mh8GPoclnj+0Oqk9cnj1vn1MJ7+YbH8+qz4FP2Auej4nZdA/127F"
        "vpqLD7/YdHo+V1gwPx/4Yr7Qh+4+K3LwvsL+Tr6I4wu/3bnCPrxQDL+HUtk/YPgHv/1Knz/3pza/"
        "mlWXvlat9buxLgq/V79xPp/Kcz/p9Ua/RUFQv4PapT4vG+Y/Pgg0Pazy6L0OWtk+UdL7v4Mgh75x"
        "/nO/P8M9P7fvEb/u70Q/hDIav85e5D0N2ig/s74Vu0nSP76psjS/f89GvzbwgL8cAo0+deAZv88Q"
        "CL+Gp4I/onNTP71l0j9nVVu/dMj/PoHPPL/a2TK/ARDiP3gt3z6pwjW/8ug2v0A8kz92zXa/75nZ"
        "vm+5Kb+KXVQ/Fq6NPsTV2T1R7DVAsYSwPneblz/tD94/LzevvjYSVb9N3Y0/u9jAPV/8ub+w88G+"
        "3PwDQJtM5b/IZIs/1q20v61M5L4Qd0RAkw8AwH31qb/KOlm/wOmCv7iSyT8LLlg9wuifPx5JwL/N"
        "r7I/jS6cPh6nD7+3X5w/q9Auv9fYeb9cpV0/n0zGv72S1z9h9yM/BM22v0QmKT+kiTM+5ju0vztg"
        "rb/Pkam/nWNCwJFfub+N6NO/TPO0PgYs4L/K6mu/8dbWPnaQiD8KJos/oLRnvoy+RD+xtRm/UgtT"
        "P5+34L+owsG+lKzhPkag0j1b9E6/SzmmP++FtL9SXww+3S64P44W8r5m1/2/GPSBvxtKUj9rCnW/"
        "FiUEP0aiA0AL8mU+SDsAvogykb0z6cM/eIUyPvbsED/NRCi+ToTnve+SAj96NTQ/hDE3P+HRHb+J"
        "+GS/hfSYv/Fqez8F0CU/DpqevTZZo74d3W2+ZFeQv3nmCr/5NV6/lg11Pzcfgr143u4+0Q9WP5c3"
        "Xz8Xx0k/6j5fvmrHSz/Y9YY/2dHZv6olpL1f1k++SNhCPy7fAz8EcW4/lfBRvmyL8L+ZATU//K3g"
        "vUGOaL7a+nu/zDbQP9D7HUBbbLI/Ny2Uv7MZ1D0/G6U9VnmXvg4+77+dqCk+TUDKv4N7C78rwhW9"
        "AltOvmjHob9lcg+/uE+av6mYmb/qrja/Lwo5vyxCyL+HCXs9ltyJvoszI79uqK6+DvzIP0f+hr79"
        "k2W/5XqTP1zFl75fXy0/BFLvvvUoe7+N2kg/mvOZPsjzyb/7XsA+0SuvPyBJPj+5/1C/d541P/FQ"
        "Aj4ki/Q/1t0yP7avOz3AVPu+1obbv6iJUT4V0Nq/YWCJvVmvhj6AlF8/STSyv8JGQb9XRTu/Zjk6"
        "PchIDT/0r7w+hbUFPnUs7j7wehm/8TXWPWK9ab5KNwE+jKCGv0JvLT6mKPW+fpuov+U5wL98PEi/"
        "RonwP5ktf79Fsdi+mo2YP1wdrr+nBlm/HHorPg/MVD8Ncai/wJzrPUS/ab/SNDu/OY1Zv1vAPr3B"
        "9l4/+79IPyajYj8DCoK+M6m7PKBVwj4Zw1U/jDwRwOU5JL4qejw/2pSxv+SLmb+rDrk/Pt3nPjEB"
        "W7/vCRG/qyv2v2UqRz/iXrI+BRKgPoiYlr/nWwnApWeKPwmFPb70TwjAWqUGPyVuE75eKwG/yMdp"
        "v9k2jD9sYGY/fBShvZd6t71y5iu/EQuKPxHTpj6mAVo+rAD8PoDMjj4eryO/ThiQP4WGvT6QqUM9"
        "ZlbuvxipG788Ehq9MomaPSly1b56KqY9xGPGP1RHqz+I3gi9omInP/sQp71Yj7M/paVcwHi2CEDA"
        "TSK/Z7KqvpoUd75CnSVA8IZ2PiqkRj//NaM/+JMKv98yED8/WmS+Th6aPzWPuTzURQ6/5XMiwA8p"
        "Oz8DE8O+C0I1v2Tc2T486NU9cGIaPjY8ej+MUw0/Dn3oPvAe2j7G6g6+pCK3v7AVCr8Wkcu/Rbho"
        "P4Flrz3pECY+61Nfv169E79wXCs9Rx5Mv31KCb+8GWw+8UMmPQ9onL5dTZq+L1dpPl1tkb8E/zu/"
        "aXVQvxjHQr/Z8LO/TExFPy6eRT2GQIC+CPv3P62e6r9jD6a/PaMgv5Ot1b9et34+2idsv2Wc3r7Q"
        "S9s9Fuotv4TYOT2lBlW+XgUEP3zB/r8Fvs++234FP751Lj8Qo8G+FmQrwCTAlj7bRgY/81cHP/rD"
        "87//AyO/YP3qPuG71D/MqRHArcGgPhLFpL7wK3O/3qHHveFyc75P3Zs/W2nrP2vCYkD8uD+87lNO"
        "vEU1fr+unpw/ftiVvyPGnjsQzZU/T9y+Pyq4Tz+gu4u+3Tw/P2aXwr5TtvE+5lIZvytXBT8j1SY/"
        "VSD3v/5QYb7t38k/iSTnPjCvnL8Sm7M/txo+Pyklpj+eOrA/tY/AvflKkr7Weq2+RQIgvjiFm79x"
        "qFI7kYpYv/JOqz0KrI8+4aSVv54cEsCNuQ1AVqoUu0w+zD524Ju+o/IrP+bsXz0Jwom+JjxmP0Ct"
        "lT4yMq2/vEqsPV6qUr+nnKE9ikHtP6VnCL9B2ta+QQK3PnlJXz9Jq5E/u2iYvrrn6b1cAZU/Klyg"
        "P+bvIDzeWBM/LRGGPyUpfT76hbu+EWIDP5x/0b8Fy2c9LVsHv7WBqj/jZp6/yMCsPsp3YL9MI/O+"
        "2NG0Pes5QD8Q7zC/9xGEPFuWab8jbKO+32htvzGwur+l+f6+0VX/Pm82hT++OaY/b2l9vhfP078U"
        "uXa/AqPHOgU7OT/yPlO7DT/mPv38jD5wRMk/IzY0P7w53T9VhW4/gB5NvQ4Unr50Qma/s0bzvvkl"
        "OT8b6Bq+IIC3PrTooT8VboM+9Ksiv7AArr4ATA5AXTIfPRSukT5DS5++/H4zP60/4T5SSj++dPEi"
        "vbbhwL8idOG+r8WGPy9+Wz8gXZe+nzaVPrw2Lj8iG+W+vLcfQBeSHr9AWrG+JfCyvvMIq757wDw/"
        "4LlLv12yeT/PU1484IU8PzyCm74KepQ+j3OSv61DOL/r7Rg/CVivP5i+fT/uE4o+sIalvnWpnD+g"
        "+WM/+BfHvjp6vr+O7IO+RBsOvxttw7+lGAm/oUOwv8c5nz1M1oQ/xVBJP6sOpL+F7Cu/MhlWP8yv"
        "uz8mZiy+zhcLP0y8K77AWALAOfzVv5ugnj87Ize+Geq5P6V9JbwgvmI/5skpvSB1Hb8mMdG/UuY8"
        "wPd7cz/Jiom+2/6CPxyHgL9fCai/3oXhv6aXJb0MXWm/tyWFP99Lm79E8cE/bYWYP641fb9YFgxA"
        "aOWNvNat67+Vph279ReQvp/AeL229Lw+0IAZv/DVvT9ojFg8vvyEP3gwD8Bw9dU92pSpP79TY7+F"
        "aQrAUWsBv4RWXr57QIo/D6z9O1Bw9T4iQtc/5Ug0vurEWr87CVw+v3gIP2j6Uz/Rcmq/gS3bvyHB"
        "nj5S1Og+mEqAv8Nvb79NKy9AauoBP01Nez4vYLM/XKkFvgnrFL/M3hk/d0NKP+kiuj+IuaO+fEgR"
        "vmqrX7xDf4K9mXqjPha9hL5+fGU/7I6AP60x4b4cjJ6/GSuVP43dvD/HUws/GjcWP4lmjT90l0m+"
        "Y5hKvzp6JcBn3Sc/xfdGvyanvL9B8JI/tpqCv/RtS7/1kmo/VHa7P6utjj8vB2C/AWNpPd4rWD4a"
        "mdS8u7wdv/WDMb/KIvi+YtimPyYQPb4ptec/CIYvP8x9xz+9qKo+GdRLvb7ntD8CF9w/NODPvkcc"
        "xj8jqOY9Ad3Bv9n2Vb1bB6o/6v6Qvzn2wz5kHKc++cEcQDuoEz9zhI6/Djmlv6nEeL9u5vg+RaBb"
        "vwPGKT4v9I+/1epkvcnUir+HJqq9/LoFPWP7eD9vjU+/ChAkPwkQKb6mCxs/KFL3vzlYvb5JFK6+"
        "5DnFP/ysV76KL2+/FcbAvpQlbL+BU5o/jzoFPqyEHj/+8aa/UrqJP6CRBb9cRtE+mfimvqfrub8H"
        "3Oe+8qwsP1eTG8DHK0+/kdYLv1BP877eF0m+jbG5Pze1tzyWVBu+NVgGP5yClz8DZ9q/D9EWujOR"
        "ET89l0M/e4flvmFICkBYETq/T8OqPWRHPr7b4t2+qkDZP1LFq753KqG+HzQLvovBI0CC3gdAc8+s"
        "P4NEnr/k3Eo/1nXePtp3lz2Bk0s/UQoLvlmecT/Fqke+EIJkvwIyCr+wgMQ/csYcPlUu0r+Td/K+"
        "cjTmveQ3rj+PMHG+SmRwv/tMpD9pE6q/2WIIP7wCXz+kjo+/1GoevxOcDz8JF4M902UGP3MtrT9m"
        "YAO/32rNP8qpzL9AsGw/bBZBP/iVi74NVzo/9Wnlv5Kzmz/DB8M/fjB/v4V3iL/REde+lx8IwNq+"
        "0r9ONM8/9YYWv76NgD/Tlpq+TW7eP3DFgD8emGI/ad6TvjMeMb73Wzi/xKdjP+vrIT9f4xG/eUri"
        "vzQHjD1vjLM9R/73v9hc+717Lmy/H7pOP/v7eD+rxbU/ZG0pPql3wD/SVLc/GIg+v4UgGT9+/Va9"
        "N9cDPwNq4T91tyE+cbzBP42TOz9ov8+/rNeQPmdAkj6B1Ag/pOEGwLiMs78KQuQ/kiITvy5kC76S"
        "Cpg/58paPkIFMj3y4CS/FC01PnI1uD5zoPa+FW5ZvrdwjrxsFKs+cYFVv4N37j6QUwI/311hP1BA"
        "Ir/fdjA/OMeOPqF+xb6z0Zi+Ol+gvqLAE7+XgwBAgumxP5Pdw70z9gu+6Y+hv/We9z5LmmA/W9Om"
        "vvfDTL6s8iC/7422P5tgXj87g5s+ZwoKP6e40j6Tslu/qN53v3ezD73bRbU/sG2kP6ORE0C3XDK/"
        "YNqlvmlfJb4YmJO+lWcXP/OeEcAo/P6+xNzyPvq6Fz9V8Gc/3QNIP39RIMBonnE+ZOvFP3k+fD8D"
        "gFI/qs9uv189Gr//v1C/M9aXv39Kaj9eqTK+Fxmev71P7b6+MW69QI9pvyNBJ0CYLnI9Kkc1wFuW"
        "sD4wIiy+IwatvmwSzL/tpOK9zcKXv0j32z4CmqG9k4+Pv06L5r/vRxTAdvAqPu4Zh7+R1SQ+h7MI"
        "QHcMgz/RLaQ9TnElv8GGAz5jniw/xEfRvk/Y2r9NJKw9HU8dv/47cz/oqd0+a2YEwLrA3b9cSGs/"
        "nRC5vwYv8z8uYuA/WQjgPtSHuz+t0rw/5sMUv1PAQb/s+/6/TjVfv26OKT8oDHc+HLC6PuN5G78V"
        "lrK+xI0WP5qDC79IGy0/l+0uv1ugnL4eIbG/aZlyPT10s78lh/w+PsErv7wH0D7Md5W+EJB+vw3R"
        "v797hBC/NLtjv3y/F74K3Nc/AgEQwF6twj8VwQ29Elysvzkyx7+aCR4/+5F2PzKk4b5i45w/xmxa"
        "P+mvEz4d5gM/G96Xv3USkT9cwpw+674TP/q8Zr4Vxg+/wbqIPit3Ej8qUg7AwK+eviiBvD5xuOg/"
        "Im8rvKbNHz9zk62/QnODPm3L6T5Xfs6/MG0cvxLdo75mElK/n8FTv04iDsCQ6Cu+t2ejPyncQL8E"
        "Sym/07xjv11GlD/x/mw+iTMZPzTVoT/jhnW+Pw0tP0K4jj9GIaW+rzOKv//xqD+iJii/q2gLPgyB"
        "oT4udKE+CNf/P9D2O775KV4/FGLVv86TYD8E7U4/yY0AQD5T676HtzA/TtivPy4wAkBuwSU+RzeV"
        "v8n7ob+uaVu/+wHUPxnQZ799tS2/7v6LvaCpJb+aRLy/TPK4vhcKsb/jKpm/0hwKP3fw775jgIa/"
        "013PP/j0G79fkva+H31hP5ccgT622hE/s/SVPmc4cL92iYu/SlSLPyzAlzy/jJ+/CeNrP+8zQj+H"
        "PZa/uNsrP2eFjj+qHw8/FJeSPncE6T5buoG+Zn7yvrLNzD8LG98/jvP7Pp04Yb783CO/o3ynvhbl"
        "jD9/Ali/ARDWvKNZaT+X3WK9fJTlP+NyAT3EIMg9SuGZPqQ8F7yW8+S/5Ltevqskwz/dEUg/0eYj"
        "P1G3lL4kgKe/+AO+PoYz079FWPM9rp37v9WEZL/IFLS/FOCcvk5aIb9gIGM/Rpu4vADqHz7JeSa/"
        "RX24Pt/3qD7VYIw/pm+ivzD007/fhCG/u+vKv4pC9D5e5GQ+z1f0P8HhNj9X+DG968AwQKTqJD6k"
        "a42//aMlP6NfKD2Fn2U+cZlFvk2NS7/MEiG92iPRPsJz1r84n+G+RJkkP9hOhr+y3CW/myFjvnDO"
        "/D+Fuvw8Ty+aPzHBVz9lsFI/akckPvpbzr/nJ0M94sDIvygrM0Db7lo/UvFevwbsHL/idEo+vWcF"
        "wCIbAEB0yew/QkaTv9NG0b/YALg8NJliv6qyIECu/s+/ds+PvgFcZr9BoIi/Z5kLP4tWGT+0Hj88"
        "mLRvPmZSNz+paha/XvzbP0bLH8APqyy/+k2BvfbIjr/RZVG/mLW8Pr8Zyj87yPm+WnPbvgucZD9S"
        "MpQ/6osmQLVhhb58l7u/nE4Zv0ncZz+IcHu/6ivgPyehAz2Kf28/gZmGPiTZmD8mhQG/JBEUwBnO"
        "fb+hS3m+y66OP7uaCD8aO72/xEHfP5Nhvr2JwZq/Q2Z7v4avPr9G+wNA7y8Cv2DdXT4fT2I+OvCt"
        "P0OiqDxHZqU//zjJPiDg6T+EPqo+oJ9SPLLzgD+TBBLAgzLhPl7fID8i0hvAtGCEP9vnoL5GVT49"
        "bKCuP4DQcL/iXna/VNJAPPsgG0DCoaK9HSBsP2Jmjr3qXWA/8NboP+Fcez4SsJc+RP2Zv9JSNj/Q"
        "tytA1himPudMTT/D/pO//m1qP+8eKD2ALha+8imkPxWctr/wxma9Pq6/vgX8kr+jnvu+VaQnv7E5"
        "DsDzMQy9DF6vvjLgfD/Vfju/hxCgP7snqz7AZFK/GbWcPzOdWr9+fue+pELbPsDxfz9hdxG/Mqdq"
        "vtMgFr8W/Gm+KquzPsFeWL2Fl8c/RTiWPz8OTr4sx/U/yxGmvm8tjT9xJSa+3FDJv8zThr+wagPA"
        "TFXKvgIOH8AOIyi/llK1P01tBz9qBqk/XydSPtFVmL/LuwrAFY2vPJCNgj5MxCE9WPrnv7tMWz5h"
        "pIk+QMSEv2yV5r7VGac+Qjl8PsI9k78HK7S/zpqVvvRVGcCsFJe+A28bv27oATvwWYq/ayMEwD0x"
        "X7/E60K/x63NvyhfRD/BvfY/mmYdv1+Zor/kD2U/qnuOP4i0xr4ByYg/gDKYv/WWLr/4Cjw/qZuJ"
        "vgWYAz4hQ2e//35hP6FSD78asoC+1rjovvXbn7/CQDy+iVXYPmSeIj9wjQQ/ejDQv8ViCUChj8c/"
        "FyVNPLGfUT3s0M8/ai4RwDLb0r/IkGK/LsNQv0kmXL3JS42/6NBZP7Lhtj+dLvO/h+GOv3uJTj8I"
        "4IO+CIfhPlv0aj4UDjS9w161Pr6gI7/KtDi/chyGPzWqdL4+GCS/LbesP8M0rj8GQQO/CYJGPpL3"
        "pT/Emuq+J0IKvvyK5r7ShJo/pH6Mv0C5mT6Ocd6+6tVrP3U5Ub8XEtE+1ha/PtoJSD8y/gQ9N/iY"
        "P9gawL+6izg/LlkDPy2Jsz6KmlE+AQeSv/W82T7M8cs/0DExvnP6C0D2i+Q+xgsJv4FKX75hXTY/"
        "v4M7v7LTFr98Bbs+tX23Pygh7L0I6H+/qAPEvVzxSz9M54w/PJdZvq9/Db9w3Ma+sTw9P8ongb/M"
        "w5A/CGwoPSU6xz4OSe4+iRfOvknPlD5smyvA8nCyPUNQ5T5WA7Q/D+O1P1vp2z4pI3E/M3miP1ws"
        "3D0p2Nw+Wk0oP5VsrL/7wZK//Uz3PxPzjL9wp5y/NHMpwKhpgz9s+gPAfmJ5P/Ian7+L5KM+z3OT"
        "v/QKXr+fey8/70AGPjGThz41Yzc/bIDuvitv8z1XqJq/klyWvxZlkT6lCTc/QGQTv7Yl1j7r3rM+"
        "59vEP6zB0z53my2/w15FPtSjFj6h2JE/QNKMOk+WtD+VtDK/SkrTv/pwvb4KJhA/w1sGQF+tF79d"
        "Fho/naH4PvLzRD+AZg6/FRnlPsMOp74umnG/OtkIv7D/f757PgfAM2HTvvQ6o76ZwFk/9hiRPtrY"
        "gz9aRGk+fSg9v0wVWrtbDH4/UpALQKRufL9kgu4+i/QZP/ayFb9xF2g/13OqP9k6/j9tSly/XmYl"
        "P2sv5b86484/KDcRQPfrjL/s/Mc8p8nqPbyjYL8AWOU+Qi3dvjf7uT8WFcC/QjAhQByksT8H3mk/"
        "Jb0hQGMxjz/r88++uTp5PlySn78ZSEE/AJDEPzVLPL+ugRG/e94Lv8PmrL6zGW6/uX6OP4p5vr6M"
        "hJo7D+CQvWMhzj9TtvC+xKVlP9LRnD82BX09cGM3P2D7xT6VXeS9b0o7P+Ll47/sumY/Z0oSv6un"
        "jz+ED0g+40aQP1ULnj6/+2W+oSVXv0CncL9zXYs/WndmvkkHw78uENs+X0YNv5i2bT8Mm2U/twif"
        "P6aEcL7LGy+/2wNOP+bCqT8AtYY/a/4mvwzUyT2FfQk/nodJvqK42j9CFIU/eChAP+HUl78KZ9k+"
        "p9Iwv0Xy+D7CH5s/DnxoPgA8g77Dvba/DieuPwkEkr4tnYS/TyGeP2DSF798ZNk9bvhtvb5DyL3e"
        "u+Q+dq2jP717b78Z7su/UI01vk+YDb2Oo54/MN6iPQPyUUAwm5S/HbIJPjzfHT80Yxk+mhkmv+YV"
        "yL7g7hA/sAdbv+KC0b7EJ3k/yhumvD/RVD69JnA/eDk6P1uosb8Oorw/pdu0vr3Ibr8ebK0/R+mR"
        "P1Jy7r2nlfk/maPNP4jtU8BgpL++18W+Pw1fQ7/GxpM9lW3FP2kMo7/wSDi/hOMIwKdLGj+zig6+"
        "7BvlPSvkSr4fjGY+zRPNvgryhj9tnk6/zXKAv/ye7j47ZFg+UB/Wv2cMZT4rjvG9b2Hvvy88tj5R"
        "kGg/Ya+LvrF/P78CgJ2/G8LfvoYdK75b/ti/CLEUv9a9tD4qXXg/D3yAv3qjh780o/I/BxQUPhEA"
        "4D2etEK+1heuP9RzZ7/TqM69vclTv4iwnj6pLmW/CpLWPiCcDT/4xLS+AAc5P1TsVD7GkZa/cpJq"
        "PjLVqj8V0qq+C5EBwI9jCT9ReI29cGvPv2lJDL9beT49f8Yzv9ex6z7u/Ru/NCOEvpRi2r/YBTs/"
        "9bk4v+WoN8AMOGG/ChQfP4NJLD/aoga/kUk7Pv9cEL9QMMo+9GRFv0Sk0j0RemY/AICzP0mY8L6o"
        "MP++ZMsIPwhGZ7/ffrY/wfowP+z/m76f5py/RgC9PovCc76oDcA9uY2sPz9qu72h2Rw/zztoviDf"
        "aD4tIxM/Wjk/v2va4D1I3SI/NyY1P91dIr8Hmym/zbCfv3c6br0l0zc/zK6jvAj2X7+t9IY92PBy"
        "v/6q1T8ZiMS+EFqAvtiE/b3AJ96/w1qcvleyQb+sx6I/8L+/v/24nL07lqK/ruGKv3mhEsCKDHK+"
        "c0+tv30is79R4hZAEX7oPs6Uhr7CHeI/YB4Hv0agIkBeKes+vXcMPhoQKT0Yaas/ZOOrveXAtz8j"
        "gP29j9aOP2NziD9QfB9Aog+bvwUdJj+W9ivAp4kLP4fW8D+aiQc+eGFwvvBrML75t7C/6/ynP/83"
        "w771jpg/hWV/Py1aUT/NkpG/4IlhPixvKTuWYcS/vtq5vtp9Y7/uBQPAu1FRv99xmz8kGK0/+6EE"
        "PjO2Yj8hd4I+mqk2PynPiT04r2o+ggyHP7tyXT9cL9U9E6DEv8uDIL+432W/fj4rvpUKLb+W5jY+"
        "ozbkPzodzT+iqbA/CuvVvnsn27ym6cW8dEYYPyJYGj9JK08/XgiMP06KUz/TaSk/ASyOPx5pSr8K"
        "h6s+GQsXPw+COb5Ym1k/YdYbP+g6rD/1/ke/0vQvPifJDr9oH7Q/9mNjPgJAFz9mmaO+Ujw7P12x"
        "mr/lXNq/2ySsvyNA7b9T0x8/ubSDPoB5fz/3ERI/03JxvxIIOL99JLc/PMTkvX6lC8BnypK/vBpn"
        "v1pW/b4XmE0/e9JNPzlt8j9Yb5s/qay9P335RT7QXFw/E0TVPulrfL4ig6U+N3nnv/Uwb78GPIa/"
        "jokrPrxaMj+YRww/sHKhv/+i+L4kToM9svWDPnk9Lb89+la/6tDoPuKLnT3H3hq/i2+7v0URMj7d"
        "dKW8abLJP6y4ej3lsIg9UeglPhseYr68Vxw/Jk+ePvC/1D+yIiu/hHNtPwpfCcC9xSM/IO4iv0XG"
        "qD5H7ra+SNa/vikzab5FRY0/CMvyPo+gI78naVs+jpIlP1/ym71M2nS/eGGcvBFLGb8vkxzA76wk"
        "wOnhoD7eW5i/yoc4vjXlnr/8m1Y/ukimv/asDj+NAuw+6ImyP9nnvD9hSfA/fiPVPiVsBT+WYYW/"
        "RzAoP/QWlL9NTlC+/jW0v57ekT9b96w+ZdMDQN6IDj/8oXm+xQJTv7rNX7+MseK+4vrYPXy2pT/z"
        "Nvy+NS9lP6shaj9I0ea/1wONv8ot1r3+QlO/OJVDv3MpM0BF+nq/hQSLv4y5xr+I6lc+T5/Ov1Wc"
        "WD99xpU/cMyJP0joQj/sZqS9poFiP5msIb84uRq/ZQRvPgWKsD5IQOG+Kx+SPdBopT+0//U/IFdS"
        "P6M53b8+2J+/GYUoPohWFEBbsh0/JbNgP/1Kpr9QVRA908BRPsHFVb4Wvcq9O/Ruv2DB5L9YHkK/"
        "eNEVP/wd0D1lbjQ/6Ab+vubatD6vyB0/21WBOuYWoT+QWGC/RVhBP4mcHb8PaTI/FiVdv0FVvD4z"
        "1M2+AMKQvr/PqT8BwZG//pcJv44vhL90MrS/PZwkPltS1jx+Y4e/xvl1vz/A6D2udVK/VtBiv59V"
        "nT9+vu49RGhEPx8s0b5gZCE/O9XJv5tgNz7JhwjAhJCIv/T/tL9rSk++JiU4P9XkKL9eJSM/m34B"
        "QG+dBT8sNDpAQ8qTPo14Lj+zoNs+QJy4PRDGJb9ChFq/wTccvjCXJz8oO929bVgHv5viWb8RufC+"
        "o1UrPmQ3iz4Ueje/4/wAP5Cso73h4o4/fMNgvnztoj8FswVAzsulvuzYZL+t/uM+2VKGPjN4uz8n"
        "l7E/e5x8vh1CqD/Kaq4/zOthv0fGkj+L0MA+6RqfPyBTNz//5AO+7KEnv+q7gj34DjA9pde9PBy+"
        "dj9knu29KjOAPhNvKD/ehbM/LGCZPY39iL51U/2+vWIpv58iRb8EQRZA1wxQPlq/3z+MS5S/nRnn"
        "PuEVsr9to4M/ToU0Pm8Y4D7ZNvK9N0jVPmVeSj8nYgQ/u5NBwObTSb4NND0/Q5MnP/ozGTuU85g+"
        "/+31v0dTuj67EnA/q7Mnv8pLDz+QGRE+VYinv71XaD+aJaO/ss1lP+OMYL/RYqs/sju8v3kpir+e"
        "EY0++P2MvqOlMj/f4pU/vwT1vwkEsb+6PcM/Ck4zP8j5eL7r9oK9zpe/vs1fpD7LdJG/1aEwPiwZ"
        "8z7MPBy/EKWjvqtGpb+4v8q/VWSEvnncOD8ue0c/cyQfv2nWcj5PnaE+UbDjvZUTlz/gF+0/A9qC"
        "PoEHuT+lm5y/vltiP3a0K7/Elue+DXiNv7kXhT3b6oY/pv1BPnEi175WBwZAkJiKvxf5OD9UD+a/"
        "gfLlv6HPhr1K1Cy/HkqGPmuYdT8/soo+ZgGFP/H0Mb6Da40/PeYEv4d+0D/Th+e/hQe/P7tRjD5Q"
        "Hrk/7ZR5v9N+TL+AUrW//e4YPfDqj79xJoe/5nEKvt5MQ773Wi4+aot7vyUaOD/twZm/ppY7QBiX"
        "uL8hm8c+oKcFP/Ke8D/UHM+/KXlpP08apz+Cu4A/vR1SP4b4pj9Hgf+99E+gPirk3L83URS/ewuv"
        "P1HjCD7PcJ0+nujOvq71ur8R4SI/h7UNvwkJZb/Txd2/"
    ), dtype=np.float32).copy().reshape([1, 3, 32, 32])


# ------------------------------------------------------------------
# Reference: pure PyTorch eager via onnx2torch
# ------------------------------------------------------------------
def _ref_pytorch(model_bytes: bytes, x: np.ndarray) -> np.ndarray:
    import torch, onnx2torch
    m = onnx2torch.convert(onnx.load_from_string(model_bytes)).eval()
    with torch.no_grad():
        out = m(torch.from_numpy(x))
    if isinstance(out, (list, tuple)): out = out[0]
    return out.detach().cpu().float().numpy().ravel()


def _rel_l2(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, np.float64).ravel(); b = np.asarray(b, np.float64).ravel()
    return float(np.linalg.norm(a - b) / max(np.linalg.norm(a), np.linalg.norm(b), 1e-12))


# ------------------------------------------------------------------
# Backend drivers
# ------------------------------------------------------------------
def _run_onnxruntime(model_bytes, x):
    import onnxruntime as ort
    opts = ort.SessionOptions()
    opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
    try:
        sess = ort.InferenceSession(model_bytes, opts, providers=["CPUExecutionProvider"])
        return np.asarray(sess.run(None, {INPUT_NAME: x})[0]).ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:120]}"


def _run_openvino(model_bytes, x):
    try:
        import openvino as ov
        core = ov.Core()
        compiled = core.compile_model(core.read_model(io.BytesIO(model_bytes)), "CPU")
        out = compiled([x])
        return np.asarray(list(out.values())[0]).ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:120]}"


def _run_tensorflow(model_bytes, x, *, jit=False):
    try:
        sys.path.insert(0, "/home/binduan/myspace/trion")
        from trion.oracle.tf_backend import TFBackend
        r = TFBackend().run(onnx.load_from_string(model_bytes), {INPUT_NAME: x}, optimized=jit)
        if r.output is None: return None, (r.error or "run returned None")[:120]
        return r.output.ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:120]}"


def _run_xla(model_bytes, x):
    return _run_tensorflow(model_bytes, x, jit=True)


def _run_torchscript(model_bytes, x):
    try:
        import torch, onnx2torch
        m = onnx2torch.convert(onnx.load_from_string(model_bytes)).eval()
        t = torch.from_numpy(x)
        scripted = torch.jit.trace(m, (t,))
        frozen = torch.jit.optimize_for_inference(torch.jit.freeze(scripted))
        with torch.no_grad():
            out = frozen(t)
        if isinstance(out, (list, tuple)): out = out[0]
        return out.detach().cpu().float().numpy().ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:120]}"


def _run_torch_compile(model_bytes, x):
    try:
        import torch, onnx2torch
        m = onnx2torch.convert(onnx.load_from_string(model_bytes)).eval()
        compiled = torch.compile(m, mode="reduce-overhead", fullgraph=False)
        with torch.no_grad():
            out = compiled(torch.from_numpy(x))
        if isinstance(out, (list, tuple)): out = out[0]
        return out.detach().cpu().float().numpy().ravel(), None
    except Exception as e:
        return None, f"{type(e).__name__}: {str(e)[:120]}"


RUNNERS = {
    "onnxruntime":   _run_onnxruntime,
    "openvino":      _run_openvino,
    "tensorflow":    _run_tensorflow,
    "xla":           _run_xla,
    "torchscript":   _run_torchscript,
    "torch_compile": _run_torch_compile,
}


def main() -> int:
    try:
        model_bytes = build_model()
        x = _input()
        ref = _ref_pytorch(model_bytes, x)
    except Exception as e:
        print(f"setup failed: {type(e).__name__}: {e}"); return 2

    print(f"Bug ID:    {__doc__.splitlines()[2].split(':',1)[1].strip()}")
    print(f"Backends:  {BACKENDS}")
    print(f"Tolerance: {TOLERANCE}")

    any_bug = False
    for backend in BACKENDS:
        run = RUNNERS.get(backend)
        if run is None:
            print(f"  [{backend}] no driver"); continue
        out, err = run(model_bytes, x)
        if err is not None:
            print(f"  [{backend}] CRASH: {err}   →   BUG REPRODUCED")
            any_bug = True
            continue
        diff = _rel_l2(out, ref)
        verdict = "REPRODUCED" if diff > TOLERANCE else "ok"
        print(f"  [{backend}] rel_L2 vs pytorch_ref = {diff:.4e}   →   {verdict}")
        if diff > TOLERANCE:
            any_bug = True

    PASS = not any_bug
    print(f"PASS={PASS}")
    if not PASS:
        print("BUG REPRODUCED"); return 0
    print("not reproduced"); return 1


if __name__ == "__main__":
    sys.exit(main())
