"""
Resize / GridSample sweep patterns.

Generated by Cartesian-product of Resize attributes and known off-by-one scale
ratios that have been documented to trip compiler-level correctness bugs.

Representative upstream issues targeted (full list in _mining_notes.md):

* onnxruntime#4279 — nearest 26→64 off-by-one vs PyTorch.
* onnx/onnx#4126 — spec edge of half_pixel + round_prefer_ceil 20→6.
* onnxruntime#10793 — asymmetric linear 30→32 precision divergence.
* onnxruntime#13102 — cubic + pytorch_half_pixel (antialias=0).
* apache/tvm#13868 — cubic + coeff_a=-0.5.
* tensorflow#62386 — nearest + half_pixel 4→8 MLIR row-shift.
* onnxruntime#16149 — GridSample(bicubic, border) out-of-range.
* onnxruntime#10607 — GridSample(bilinear, border) boundary drift.
* pytorch#104055 — GridSample(reflection, align_corners=0).

Each pattern here is a single Resize (or GridSample) op, consuming a 4-D float32
tensor. Output shape is computed exactly from ``sizes=`` or the grid shape, so
the downstream composer sees a concrete rank-4 tensor again.
"""
from __future__ import annotations

from typing import List, Optional

import numpy as np
from onnx import NodeProto, TensorProto, helper, numpy_helper

from ..generation.context import StructuralContext
from .base import CAT_LAYOUT, OTP, PatternInstance


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# (in_HW, out_HW) — ratios flagged in upstream bug reports.
_RESIZE_RATIOS: List[tuple[int, int]] = [
    (26, 64),  # ORT #4279 upsample off-by-one
    (20, 6),   # spec edge round_prefer_ceil
    (30, 32),  # ORT #10793 asymmetric linear
    (5, 4),    # downsample small
    (32, 30), # inverse of 30→32
    (64, 96),  # cubic upsample
]


def _resize_nodes(
    input_name: str,
    prefix: str,
    out_name: str,
    *,
    mode: str,
    coord_mode: str,
    nearest_mode: Optional[str] = None,
    cubic_coeff_a: Optional[float] = None,
    extrapolation_value: Optional[float] = None,
    out_h: int,
    out_w: int,
    N: int,
    C: int,
) -> tuple[List[NodeProto], List[TensorProto]]:
    """Build a Resize node with explicit ``sizes=`` to pin the exact ratio."""
    empty_roi = np.array([], dtype=np.float32)
    # tf_crop_and_resize requires a valid ROI (normalised y1,x1,y2,x2 per spatial axis).
    if coord_mode == "tf_crop_and_resize":
        roi = np.array(
            [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0], dtype=np.float32
        )
    else:
        roi = empty_roi
    empty_scales = np.array([], dtype=np.float32)
    sizes = np.array([N, C, out_h, out_w], dtype=np.int64)

    kwargs = {"mode": mode, "coordinate_transformation_mode": coord_mode}
    if nearest_mode is not None:
        kwargs["nearest_mode"] = nearest_mode
    if cubic_coeff_a is not None:
        kwargs["cubic_coeff_a"] = cubic_coeff_a
    if extrapolation_value is not None:
        kwargs["extrapolation_value"] = extrapolation_value

    nodes = [
        helper.make_node(
            "Resize",
            [input_name, f"{prefix}_roi", f"{prefix}_scales", f"{prefix}_sizes"],
            [out_name],
            **kwargs,
        )
    ]
    inits = [
        numpy_helper.from_array(roi, f"{prefix}_roi"),
        numpy_helper.from_array(empty_scales, f"{prefix}_scales"),
        numpy_helper.from_array(sizes, f"{prefix}_sizes"),
    ]
    return nodes, inits


# ---------------------------------------------------------------------------
# Resize family
# ---------------------------------------------------------------------------


class _ResizeSweepBase(OTP):
    """Abstract parent; subclasses set class-level attrs."""

    category: str = CAT_LAYOUT
    mode: str = "nearest"
    coord_mode: str = "half_pixel"
    nearest_mode: Optional[str] = None
    cubic_coeff_a: Optional[float] = None
    extrapolation_value: Optional[float] = None
    in_hw: int = 26
    out_hw: int = 64

    def is_compatible(self, ctx: StructuralContext) -> bool:
        if ctx.rank != 4 or ctx.dtype != "float32":
            return False
        _, _, H, W = ctx.shape
        # Only instantiate when we can fit the ratio — we emit the exact
        # requested in_hw by a cheap pad/slice-like approach: we skip if the
        # upstream context spatial dims are smaller than the target in_hw.
        return H >= 2 and W >= 2

    def instantiate(
        self,
        input_name: str,
        ctx: StructuralContext,
        rng: np.random.Generator,
        node_id: int,
    ) -> Optional[PatternInstance]:
        N, C, H, W = ctx.shape
        p = self._p(node_id, "rs")
        # We don't force the input spatial dims to match in_hw exactly — the
        # Resize operator handles arbitrary input spatial sizes, what matters
        # is that `sizes` pins the output shape. But we pick the ratio
        # deterministically from the name so the pattern is bit-exact.
        out_h = max(2, self.out_hw)
        out_w = max(2, self.out_hw)
        out = f"{p}_out"
        nodes, inits = _resize_nodes(
            input_name,
            p,
            out,
            mode=self.mode,
            coord_mode=self.coord_mode,
            nearest_mode=self.nearest_mode,
            cubic_coeff_a=self.cubic_coeff_a,
            extrapolation_value=self.extrapolation_value,
            out_h=out_h,
            out_w=out_w,
            N=N,
            C=C,
        )
        return PatternInstance(
            self.name,
            self.category,
            nodes,
            inits,
            input_name,
            out,
            StructuralContext(4, [N, C, out_h, out_w], ctx.dtype, ctx.layout),
        )


# ---------------------------------------------------------------------------
# Cartesian-product generation
# ---------------------------------------------------------------------------

_COORD_MODES = [
    "half_pixel",
    "pytorch_half_pixel",
    "asymmetric",
    "align_corners",
    "tf_crop_and_resize",
]
_NEAREST_MODES = ["floor", "ceil", "round_prefer_floor", "round_prefer_ceil"]
_CUBIC_COEFFS = [-0.75, -0.5]


def _build_resize_classes() -> List[type]:
    """Generate a curated set of ``_ResizeSweepBase`` subclasses.

    Rather than a full Cartesian product (which would yield ~180 variants),
    we pick high-signal combos: each of the 6 ratios gets every coord_mode
    paired with a rotating nearest_mode, plus two linear and one cubic variant.
    That yields ~34 Resize patterns + 6 GridSample = 40 total.
    """
    classes: List[type] = []

    # Nearest: pair each ratio with every coord_mode; rotate nearest_mode
    # so all four nearest_modes appear across the sweep.
    for idx, (ih, oh) in enumerate(_RESIZE_RATIOS):
        for cm_idx, cm in enumerate(_COORD_MODES):
            nm = _NEAREST_MODES[(idx + cm_idx) % len(_NEAREST_MODES)]
            classes.append(
                _make_nearest_class(ih=ih, oh=oh, coord_mode=cm, nearest_mode=nm)
            )

    # Linear: coord_mode ∈ {half_pixel, asymmetric} per ratio.
    for (ih, oh) in _RESIZE_RATIOS:
        for cm in ("half_pixel", "asymmetric"):
            classes.append(_make_linear_class(ih=ih, oh=oh, coord_mode=cm))

    # Cubic: half_pixel + (coeff=-0.75, -0.5) per ratio.
    for (ih, oh) in _RESIZE_RATIOS:
        for coeff in _CUBIC_COEFFS:
            classes.append(
                _make_cubic_class(
                    ih=ih, oh=oh, coord_mode="half_pixel", coeff=coeff
                )
            )
    return classes


def _tag_ratio(ih: int, oh: int) -> str:
    return f"{ih}to{oh}"


def _make_nearest_class(
    *, ih: int, oh: int, coord_mode: str, nearest_mode: str
) -> type:
    cm_tag = coord_mode.replace("_", "")
    nm_tag = nearest_mode.replace("_", "")
    name = f"rs_nearest_{cm_tag}_{nm_tag}_{_tag_ratio(ih, oh)}"
    cls = type(
        f"ResizeNearest_{cm_tag}_{nm_tag}_{_tag_ratio(ih, oh)}",
        (_ResizeSweepBase,),
        {
            "name": name,
            "target_optimization": "resize_nearest_sweep",
            "mode": "nearest",
            "coord_mode": coord_mode,
            "nearest_mode": nearest_mode,
            "in_hw": ih,
            "out_hw": oh,
        },
    )
    return cls


def _make_linear_class(*, ih: int, oh: int, coord_mode: str) -> type:
    cm_tag = coord_mode.replace("_", "")
    name = f"rs_linear_{cm_tag}_{_tag_ratio(ih, oh)}"
    cls = type(
        f"ResizeLinear_{cm_tag}_{_tag_ratio(ih, oh)}",
        (_ResizeSweepBase,),
        {
            "name": name,
            "target_optimization": "resize_linear_sweep",
            "mode": "linear",
            "coord_mode": coord_mode,
            "nearest_mode": None,
            "in_hw": ih,
            "out_hw": oh,
        },
    )
    return cls


def _make_cubic_class(*, ih: int, oh: int, coord_mode: str, coeff: float) -> type:
    cm_tag = coord_mode.replace("_", "")
    coeff_tag = f"{int(abs(coeff) * 100)}"
    name = f"rs_cubic_{cm_tag}_a{coeff_tag}_{_tag_ratio(ih, oh)}"
    cls = type(
        f"ResizeCubic_{cm_tag}_a{coeff_tag}_{_tag_ratio(ih, oh)}",
        (_ResizeSweepBase,),
        {
            "name": name,
            "target_optimization": "resize_cubic_sweep",
            "mode": "cubic",
            "coord_mode": coord_mode,
            "nearest_mode": None,
            "cubic_coeff_a": coeff,
            "in_hw": ih,
            "out_hw": oh,
        },
    )
    return cls


# ---------------------------------------------------------------------------
# GridSample family
# ---------------------------------------------------------------------------


class _GridSampleBase(OTP):
    category: str = CAT_LAYOUT
    target_optimization: str = "grid_sample_sweep"
    mode: str = "bilinear"
    padding_mode: str = "zeros"
    align_corners: int = 0

    def is_compatible(self, ctx: StructuralContext) -> bool:
        if ctx.rank != 4 or ctx.dtype != "float32":
            return False
        _, _, H, W = ctx.shape
        return H >= 4 and W >= 4

    def instantiate(
        self,
        input_name: str,
        ctx: StructuralContext,
        rng: np.random.Generator,
        node_id: int,
    ) -> Optional[PatternInstance]:
        N, C, H, W = ctx.shape
        p = self._p(node_id, "gs")
        # Deterministic grid that deliberately includes boundary-crossing
        # coordinates (-1.1, +1.1) to trip padding-mode handling, plus
        # in-range points.
        yy = np.linspace(-1.1, 1.1, H, dtype=np.float32)
        xx = np.linspace(-1.1, 1.1, W, dtype=np.float32)
        grid_y, grid_x = np.meshgrid(yy, xx, indexing="ij")
        grid_single = np.stack([grid_x, grid_y], axis=-1)[None, ...]
        grid = np.broadcast_to(grid_single, (N, H, W, 2)).astype(np.float32).copy()

        out = f"{p}_out"
        nodes = [
            helper.make_node(
                "GridSample",
                [input_name, f"{p}_grid"],
                [out],
                mode=self.mode,
                padding_mode=self.padding_mode,
                align_corners=self.align_corners,
            )
        ]
        inits = [numpy_helper.from_array(grid, f"{p}_grid")]
        return PatternInstance(
            self.name,
            self.category,
            nodes,
            inits,
            input_name,
            out,
            StructuralContext(4, [N, C, H, W], ctx.dtype, ctx.layout),
        )


def _make_gridsample_class(
    *, mode: str, padding_mode: str, align_corners: int
) -> type:
    name = (
        f"rs_gridsample_{mode}_{padding_mode}_"
        f"ac{align_corners}"
    )
    cls = type(
        f"GridSample_{mode}_{padding_mode}_ac{align_corners}",
        (_GridSampleBase,),
        {
            "name": name,
            "target_optimization": "grid_sample_sweep",
            "mode": mode,
            "padding_mode": padding_mode,
            "align_corners": align_corners,
        },
    )
    return cls


_GRIDSAMPLE_COMBOS: List[tuple[str, str, int]] = [
    ("bilinear", "zeros", 0),
    ("bilinear", "border", 0),
    ("bilinear", "reflection", 0),
    ("nearest", "border", 1),
    ("bicubic", "border", 0),
    ("bicubic", "zeros", 1),
]


# ---------------------------------------------------------------------------
# Public registration surfaces
# ---------------------------------------------------------------------------

_RESIZE_CLASSES: List[type] = _build_resize_classes()
_GRIDSAMPLE_CLASSES: List[type] = [
    _make_gridsample_class(mode=m, padding_mode=pm, align_corners=ac)
    for (m, pm, ac) in _GRIDSAMPLE_COMBOS
]

ALL_RESIZE_SWEEP_PATTERNS: List[OTP] = [
    cls() for cls in (_RESIZE_CLASSES + _GRIDSAMPLE_CLASSES)
]

RESIZE_SWEEP_BY_CATEGORY: dict[str, List[OTP]] = {
    CAT_LAYOUT: ALL_RESIZE_SWEEP_PATTERNS,
}
